notifi-network/notifi-sdk-ts

packages/notifi-axios-adapter/lib/mutations/createAlertImpl.ts
packages/notifi-axios-adapter/lib/utils/axiosRequest.ts
packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/models/Alert.ts
packages/notifi-core/lib/operations/CreateAlert.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

`groupName` is an optional parameter for Alert creation
it defaults to "default"

Add support for groupName

---

package-lock.json
packages/notifi-node-sample/lib/index.ts
packages/notifi-node/README.md
packages/notifi-node/lib/client/NotifiClient.spec.ts
packages/notifi-node/lib/client/NotifiClient.ts
packages/notifi-node/lib/index.ts
packages/notifi-node/lib/mutations/ManagedAlert.ts
packages/notifi-node/lib/mutations/WalletBlockchain.ts
packages/notifi-node/lib/mutations/createDirectPushAlertImpl.ts
packages/notifi-node/lib/mutations/createTenantUserImpl.ts
packages/notifi-node/lib/mutations/deleteDirectPushAlertImpl.ts
packages/notifi-node/lib/mutations/index.ts
packages/notifi-node/lib/mutations/sendMessageImpl.ts
packages/notifi-node/lib/types/DirectTenantMessage.ts
packages/notifi-node/lib/types/index.ts
packages/notifi-node/package.json

There are some new server-side capabilities for supporting Direct Push messages.
Expose these via the client:
- createTenantUser
- createDirectPushAlert
- sendDirectPush

Support Direct Push Messages

---

packages/notifi-node/lib/client/NotifiClient.ts

Allow the client to configure a template

Expose template to node sdk

---

package-lock.json
packages/notifi-node/lib/client/NotifiClient.ts

Allow client to specify different targets for different channels

Split targets

---

packages/notifi-node/lib/client/NotifiClient.ts

Expose template params on health

---

packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

If we have a source, we should be using the applicable filters to
identify the filter
This will be a patch release

Use applicableFilters for created source

---

packages/notifi-react-card/lib/components/NotifiFooter.tsx

This is the new url for the updated FAQ

Update FAQ url in footer

---

packages/notifi-react-card/lib/components/NotifiCard.tsx
packages/notifi-react-card/lib/components/NotifiTelegramInput.tsx
packages/notifi-react-card/lib/components/index.ts
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

- Expose `keepSubscriptionData` so we don't delete targetGroup when unsubscribing from alerts
- add Telegram Input component
- expose a `logIn` function to fetch data
- expose `isAuthenticated` and `isInitialized`

Incremental improvements to notifi-react-card

---

package-lock.json
packages/notifi-axios-adapter/lib/NotifiAxiosService.ts
packages/notifi-axios-adapter/lib/fragments/index.ts
packages/notifi-axios-adapter/lib/fragments/userFragment.ts
packages/notifi-axios-adapter/lib/fragments/userTopicFragment.ts
packages/notifi-axios-adapter/lib/mutations/broadcastMessageImpl.ts
packages/notifi-axios-adapter/lib/queries/getTopicsImpl.ts
packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/NotifiService.ts
packages/notifi-core/lib/models/User.ts
packages/notifi-core/lib/models/UserTopic.ts
packages/notifi-core/lib/models/index.ts
packages/notifi-core/lib/operations/BroadcastMessage.ts
packages/notifi-core/lib/operations/GetTopics.ts
packages/notifi-core/lib/operations/index.ts
packages/notifi-react-card/lib/components/NotifiCard.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-hooks/README.md
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts
packages/notifi-react-hooks/lib/utils/fetchDataImpl.ts
packages/notifi-react-hooks/lib/utils/storage.ts
packages/notifi-react-hooks/package.json

Also added an example to README
This set of changes allows the user to get the `UserTopic` associated with the user and also to send a broadcast message.
The requirement is that a JWT is acquired with the `UserMessenger` role -- I've exposed logIn and logOut methods for this purpose.

Add Broadcast Message to SDK

---

packages/notifi-react-card/README.md

The import statement is incorrect in the sample!
Closes #36

Update import statements in README

---

packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

There's some state changes to be updated when login completes that we are doing in loginfromdapp but not in completeloginviatxn
Update it so that we're doing all of the relevant state changes in both.

Update client state on CompleteLogin

---

packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts
packages/notifi-react-hooks/lib/utils/storage.ts

We should add a react linter in the SDK v2

Clean up dependency arrays

---

package-lock.json
package.json
packages/notifi-core/lib/NotifiClient.ts
packages/notifi-react-card/lib/components/NotifiCard.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/package.json

Add the sendTransaction and connection dependencies to React Card
Expose a `setUseHardwareLogIn` in context

Hardware support

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/fragments/NotificationHistoryEntryFragment.gql.ts
packages/notifi-graphql/lib/gql/fragments/PageInfoFragment.gql.ts
packages/notifi-graphql/lib/gql/queries/getNotificationHistory.gql.ts
packages/notifi-graphql/lib/operations/GetNotificationHistory.ts
packages/notifi-graphql/lib/operations/index.ts

Expose through the notification history.
For now, fetch just details for Broadcast

Add get Notification History

---

packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-graphql/lib/NotifiService.ts

- Properly pass Headers type (array of array is secretly unsupported)
- Remove cache in ensureSourceGroup (results in wonkiness, need a better scheme)

Minor fixes to Frontend-Client

---

packages/notifi-frontend-client/README.md

Markdown documentation of the READ.ME of the frontend-client package
Check here for the markdown rendering:
[NotifiSDK ReadMe.pdf](https://github.com/notifi-network/notifi-sdk-ts/files/9650269/NotifiSDK.ReadMe.pdf)

Initial Frontend Client Package Documentation

---

package-lock.json
packages/notifi-react-card/lib/components/subscription/EventTypeBroadcastRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeDirectPushRow.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/defaults.css
packages/notifi-react-card/lib/components/subscription/index.ts
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

This row is very similar to the broadcast one.

Add direct push row

---

package-lock.json
package.json
packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts

- Created a standard config and client instance for Solana for the frontend-client package

Solana Config and Client for frontend-client package

---

package-lock.json
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-frontend-client/lib/storage/InMemoryStorageDriver.ts
packages/notifi-frontend-client/lib/storage/index.ts
packages/notifi-node/lib/client/NotifiClient.ts
packages/notifi-node/lib/mutations/createDirectPushAlertImpl.ts
packages/notifi-node/package.json

add small fixes for clients
- add in-memory storage for clients taht don't uspport local storage
- do not instantiate rejected Promise in default code path
- remove telegram ID from createDirectPushAlert

Various fixes

---

package-lock.json
package.json
packages/notifi-react-card/lib/components/NotifiSmsInput.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/defaults.css
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/lib/utils/phoneUtils.ts
packages/notifi-react-card/package.json
packages/notifi-react-card/tsconfig.json

Creates a dropdown for the SMS Input.
- Adds new phone input dropdown to iterate based off country codes.
dark mode: 
Demo:
https://user-images.githubusercontent.com/105258726/193683673-b5adb981-3a0e-41ca-beb7-034df013a26e.mov

Updates sms input to dropdown. Allows multiple country codes.

---

packages/notifi-node/lib/queries/getTenantConnectedWalletImpl.ts
packages/notifi-node/lib/types/UserWithAlerts.ts

Add ID to UserWithAlerts

---

packages/notifi-core/lib/operations/CreateSource.ts

adds bonfida to createing source types so we can also create them if they're not found

creates typings

---

packages/notifi-react-card/lib/components/subscription/FetchedStateCard.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCard.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/defaults.css

Darkmode:
Lightmode:
Differing text:
Missing label:

creates input separators

---

packages/notifi-react-hooks/README.md

updates readme to handle useNotifiClient params

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/operations/LogInFromDapp.ts
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/context/NotifiContext.tsx
packages/notifi-react-card/package.json
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Added Polygon, Arbitrum, and Binance

Add additional supported EVM chains

---

packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/EditCardView.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/lib/utils/AlertConfiguration.ts

https://user-images.githubusercontent.com/105258726/196400654-e848c436-eaf8-445c-9572-8230815c85bb.mov

updates subscribe method

---

packages/notifi-react-card/lib/components/subscription/defaults.css
packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx

Virtual Container:
https://user-images.githubusercontent.com/108922885/197699984-6c045d5a-5a04-4804-8c68-9fc64b806878.mov

PR-1472 [2/x] Create Virtual Container

---

package-lock.json
packages/notifi-react-card/lib/assets/backArrow.tsx
packages/notifi-react-card/package.json

- Added react-virtuoso dependency
- Renamed kebab-case properties to camelCase for Reactisms

Small fixes

---

packages/notifi-axios-adapter/lib/queries/getNotificationHistoryImpl.ts
packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx
packages/notifi-react-card/lib/utils/constants.ts
packages/notifi-react-card/package.json

Demo Video (Alert History with Virtual Scroll and confirm pagination through Network calls - Please note I was setting the MESSAGES_PER_PAGE constant to 8 in this video for demo purposes):
https://user-images.githubusercontent.com/108922885/198110163-f79c584d-c05a-4662-b0b3-9635bb8072a7.mov

PR-1472 - [3/3] - Alert History Pagination 

---

packages/notifi-axios-adapter/lib/NotifiAxiosService.ts
packages/notifi-axios-adapter/lib/fragments/conversationMessagePageInfoFragment.ts
packages/notifi-axios-adapter/lib/queries/getConversationMessagesImpl.ts
packages/notifi-axios-adapter/package-lock.json
packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/NotifiService.ts
packages/notifi-core/lib/models/ConversationMessages.ts
packages/notifi-core/lib/operations/GetConversationMessages.ts
packages/notifi-core/lib/operations/index.ts
packages/notifi-react-card/lib/hooks/useIntercomChat.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Jennifer and I pair programming on this

[MVP-1599] - [1/x] set up getConversationMessage query and function implementation - without polling

---

packages/notifi-axios-adapter/lib/NotifiAxiosService.ts
packages/notifi-axios-adapter/lib/fragments/conversationMessageFragment.ts
packages/notifi-axios-adapter/lib/mutations/sendConversationMessagesImpl.ts
packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/NotifiService.ts
packages/notifi-core/lib/operations/SendConversationMessages.ts
packages/notifi-core/lib/operations/index.ts
packages/notifi-react-card/lib/components/intercom/ChatMessageSection.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomChatWindowContainer.tsx
packages/notifi-react-card/lib/components/intercom/SendMessageSection.tsx
packages/notifi-react-card/lib/hooks/useIntercomChat.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

When use hit the send button, firing ConversationMessageMutationCreate query to update conversation messages.
Test:
Story:
https://notifi.atlassian.net/browse/MVP-1630

[MVP-1630 ] Send Message Implement

---

packages/notifi-react-card/lib/components/intercom/ChatMessageSection.tsx
packages/notifi-react-card/lib/components/intercom/ChatWindowHeader.tsx
packages/notifi-react-card/lib/components/intercom/ChatWindowIntroSection.tsx
packages/notifi-react-card/lib/components/intercom/IntercomCard.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomCard.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomCardContainer.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomChatWindowContainer.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomFTUNotificationTargetSection.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCardContainer.tsx
packages/notifi-react-card/lib/hooks/IntercomCardConfig.ts
packages/notifi-react-card/lib/hooks/useIntercomCard.ts

Add the configuration created on the Config Tool to the Intercom Card
Test:
Story:
https://notifi.atlassian.net/jira/software/c/projects/MVP/boards/1?modal=detail&selectedIssue=MVP-1641&sprint=51

[MVP-1641] pipe intercom card with config

---

packages/notifi-react-card/lib/utils/AlertHistoryUtils.tsx

Alert Details Card
We need to update the timestamp logic
if it's today, show time
if it's after today and within this week, show weekday,
if greater than a week, show month and date

updates display logic for alert history

---

packages/notifi-react-card/lib/components/intercom/ChatMessageSection.tsx
packages/notifi-react-card/lib/hooks/useIntercomChat.ts

day bubble showed in the chat for each conversation feed
add isSameDate params to check on showing date or not for each feed
test:
story:
https://notifi.atlassian.net/browse/MVP-1638

[MVP-1638] fix day bubble in chat only needs to show once per day

---

packages/notifi-react-card/lib/utils/AlertConfiguration.ts

Test:
Story:
https://notifi.atlassian.net/browse/MVP-1687

[MVP-1687] fix create chat alert for intercom card

---

packages/notifi-react-card/lib/components/subscription/defaults.css

Test:
Story:
https://notifi.atlassian.net/browse/MVP-1695

[MVP-1695]fix: textarea need to be fixed and can not be resized

---

packages/notifi-axios-adapter/lib/mutations/createSupportConversationImpl.ts
packages/notifi-core/lib/models/SupportConversation.ts
packages/notifi-react-card/lib/components/intercom/IntercomCard.tsx
packages/notifi-react-card/lib/components/intercom/MessageGroup.tsx
packages/notifi-react-card/lib/components/subscription/defaults.css
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx

add backgroundImageUrl as createSupportConversation mutation response
Test:
Story:
https://notifi.atlassian.net/browse/MVP-1701

[MVP-1701] show support staff avatar

---

packages/notifi-react-card/lib/components/intercom/IntercomCard.tsx
packages/notifi-react-card/lib/components/intercom/MessageGroup.tsx
packages/notifi-react-card/lib/components/subscription/defaults.css
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx

update to get avatarData and avatarDataTYpe for showing support staff avatar from conversationMessage.conversationParticipant instead of from conversation.participant
test:

update to get avatarData and avatarDataType from conversationMessage.

---

packages/notifi-react-card/README.md

Add documentation on how to utilize NEAR in react-card

Add NEAR Documentation

---

packages/notifi-react-card/lib/components/subscription/EventTypeHealthCheckRow.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx

user need to create the liquidation alert on react subscription card
hook up with create/update alert API when user toggles the button
https://notifi.atlassian.net/jira/software/c/projects/MVP/boards/1?modal=detail&selectedIssue=MVP-1828

[MVP-1828] connect API for creating liquidation alert

---

package-lock.json
packages/notifi-axios-utils/lib/utils/notifiConfigs.ts
packages/notifi-node/lib/client/NotifiClient.ts
packages/notifi-node/lib/client/createSubscriptionClient.ts
packages/notifi-node/lib/client/index.ts
packages/notifi-node/lib/client/subscribeTenantEntityUpdated.ts
packages/notifi-node/lib/queries/getTenantUserImpl.ts
packages/notifi-node/lib/types/TenantConnectedWallet.ts
packages/notifi-node/lib/types/TenantUser.ts
packages/notifi-node/lib/types/TenantUserAlert.ts
packages/notifi-node/lib/types/index.ts
packages/notifi-node/package.json

test script:
```js
const axios = require('axios');
const notifi = require('@notifi-network/notifi-node');
const dotenv = require('dotenv');
const createClient = async (env) => {
const axiosInstance = notifi.createAxiosInstance(axios, env);
const client = new notifi.NotifiClient(axiosInstance);
return client;
};
const getToken = async (client, sid, secret) => {
console.log('logging in');
const result = await client.logIn({ sid, secret });
console.log('getToken', result);
return result.token;
}
const createSubscriptionClient = async (env, token) => {
const subscriptionClient = notifi.createSubscriptionClient(env, token);
return subscriptionClient;
}
const getSubscription = async (subscriptionClient) => {
await notifi.subscribeTenantEntityUpdated(subscriptionClient, (val) => { …
```

TenantUser and Subscription

---

packages/notifi-react-card/lib/components/intercom/IntercomCard.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomCard.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomFTUNotificationTargetSection.tsx
packages/notifi-react-card/lib/components/subscription/FetchedStateCard.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCard.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/EditCardView.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/InputFields.tsx
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx

We didn't have a a place to update the copy for text fields
Updated some of hte props to allow a user to pass in text.
added an additional field for `InputsFields` to include placeholder text.

Placeholder updates

---

packages/notifi-core/lib/models/NotificationHistory.ts
packages/notifi-react-card/lib/assets/RatioCheckIcon.tsx
packages/notifi-react-card/lib/components/AlertHistory/AlertDetailsCard.tsx
packages/notifi-react-card/lib/components/AlertHistory/AlertNotificationRow.tsx
packages/notifi-react-card/lib/components/AlertHistory/HealthValueOverThresholdEventRenderer.tsx
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/EventTypeHealthCheckRow.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/AlertListPreview.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/AlertsPanel.tsx
packages/notifi-react-card/lib/hooks/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx

this PR is for merging all the changes in hao/MVP-1810 branch to main(changes have been approved)

add health check alert in alerts panel

---

packages/notifi-react-card/lib/components/NotifiSmsDropdownOption.tsx
packages/notifi-react-card/lib/components/NotifiSmsInput.tsx
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/constants/countryData.tsx

[MVP-1702](https://notifi.atlassian.net/browse/MVP-1702)
- Country code dropdown improvement
[MVP-1702]: https://notifi.atlassian.net/browse/MVP-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MVP-1702 country code dropdown improvement

---

packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/queries/getSourceConnection.gql.ts
packages/notifi-graphql/lib/operations/GetSourceConnection.ts
packages/notifi-graphql/lib/operations/index.ts
packages/notifi-node/lib/client/NotifiClient.ts

There's a new paginated endpoint for sources. Expose that through the node SDK

Add getSourceConnection

---

packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/EventTypeCustomHealthCheckRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeCustomToggleRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeTradingPairsRow.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/AlertsPanel.tsx
packages/notifi-react-card/lib/hooks/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/lib/utils/AlertConfiguration.ts
packages/notifi-react-example/package.json

Created handling custom event types
Testing:
Use custom filter toggle type to mimic a topic like broadcast topics.
sent test message with custom topic type id

Custom topic type

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/operations/LogInFromDapp.ts
packages/notifi-react-card/README.md
packages/notifi-react-card/lib/context/NotifiContext.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/utils/types/AlertHistoryTypes.tsx
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

did this to set up a future integration

adds avalanche to sdk notifi context

---

packages/notifi-react-card/lib/components/subscription/EventTypeCustomToggleRow.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/AlertsPanel.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/lib/utils/AlertConfiguration.ts

this was due to not handling sourceAddress value or refs.

update alertConfiguration for customToggles

---

packages/notifi-react-card/lib/components/NotifiDisclosureStatement.tsx
packages/notifi-react-card/lib/components/NotifiFooter.tsx
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCard.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCardContainer.tsx

Disclosure copy update

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/operations/CreateSource.ts
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/EventTypeWalletBalanceRow.tsx
packages/notifi-react-card/lib/components/subscription/index.ts
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/AlertsPanel.tsx
packages/notifi-react-card/lib/hooks/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/lib/utils/AlertConfiguration.ts
packages/notifi-react-card/lib/utils/walletUtils.ts
packages/notifi-react-example/src/MultiWalletTest/MultiWalletTest.tsx
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

- Consolidate logic in createAlert vs instantSubscribe
- Add support for walletBalance eventType
- Add support for AlertConfiguration with multiple sources
- Use connectedWallets to create sources
tested with multiwallettest dc08714b8b014ee79aec3ea650e34091

Add support for balance alerts

---

packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/lib/utils/stringUtils.ts

https://user-images.githubusercontent.com/105258726/220763538-130eb42e-87d0-488c-af3a-9219c88480f1.mov

updates telegram prefixing with symbol

---

packages/notifi-react-card/lib/assets/ChatAlertIcon.tsx
packages/notifi-react-card/lib/assets/PenIcon.tsx
packages/notifi-react-card/lib/components/AlertHistory/AlertDetailsCard.tsx
packages/notifi-react-card/lib/components/NotifiLogo.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/AlertListPreview.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/AlertsPanel.tsx

- Fix warnings emitted to console: missing key props, kebab-cased React props
- Add Renderers for DetailsCard -- we should probably come up with a way to dedupe with AlertHistoryView but until then explicitly add all of hte supported types

Fix minor issues

---

packages/notifi-react-card/lib/components/common/LoadingStateCard.tsx
packages/notifi-react-card/lib/components/common/Spinner.tsx
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCard.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCardContainer.tsx
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx

we had removed previous implementations of css here.
https://user-images.githubusercontent.com/105258726/221660396-5c094665-aee4-46d1-b7cf-dfe2d80d3a63.mov

updates loading state card css

---

packages/notifi-react-card/lib/components/AlertHistory/GenericDetailRenderer.tsx

Updates generic class name for icons

updates generic detail icon classnames

---

packages/notifi-react-card/lib/components/defaults.css

adds default padding and also removes padding size on btns

---

packages/notifi-react-card/lib/components/subscription/EventTypeWalletBalanceRow.tsx

https://user-images.githubusercontent.com/105258726/225466120-e193d079-840c-4c2a-a099-8bd1ec870af6.mov

adds optismistic rendering for walletBalance

---

packages/notifi-react-card/lib/components/defaults.css

MVP-2281: Update styling of destination container

---

packages/notifi-react-card/lib/components/defaults.css

MVP-2281-patch: Change alert toggle color of status inactive

---

packages/notifi-react-card/lib/constants/countryData.tsx

updates canada and us

---

packages/notifi-react-card/lib/components/AlertHistory/DAOProposalChangedEventRenderer.tsx
packages/notifi-react-card/lib/components/AlertHistory/NftAuctionChangedEventRenderer.tsx
packages/notifi-react-card/lib/components/AlertHistory/WalletActivityReportsEventRenderer.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCardContainer.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/hooks/SubscriptionCardConfig.ts
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx

Added a way to pass titles from the config tool.
if there are no config tool titles, it should default what is implemented in the codebase.
if there are no titles implemented from the codebase, defaults to standard titles.
https://user-images.githubusercontent.com/105258726/226432211-c20addd8-ee2c-4bae-bba1-00a3191882b4.mov

Title addition

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/models/NotificationHistory.ts
packages/notifi-core/lib/models/WalletBlockchain.ts
packages/notifi-core/lib/operations/CreateSource.ts
packages/notifi-react-card/README.md
packages/notifi-react-card/lib/context/NotifiContext.tsx
packages/notifi-react-card/lib/utils/walletUtils.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Not to be merged till Optimism mainnet approval

Support Optimism on SDK

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/models/DiscordTarget.ts
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/UserInfoPanel.tsx
packages/notifi-react-card/lib/context/NotifiContext.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-example/src/index.tsx

Discord discriminator update

---

package-lock.json
packages/notifi-react-card/README.md
packages/notifi-react-example/README.md
packages/notifi-react-example/package.json
packages/notifi-react-example/src/AcalaWalletContextProvider.tsx
packages/notifi-react-example/src/App.tsx
packages/notifi-react-example/src/NotifiCard/DemoPreviewCard.tsx
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx
packages/notifi-react-example/src/NotifiCard/PolkadotCard.tsx
packages/notifi-react-example/src/NotifiCard/SolanaCard.tsx
packages/notifi-react-example/src/NotifiCard/WalletConnectCard.tsx
packages/notifi-react-example/src/SolanaWalletProvider.tsx
packages/notifi-react-example/src/WalletConnectProvider.tsx
packages/notifi-react-example/src/index.tsx

1. Add WalletConnect example to notifi-react-example / Classify supported Blockchains (wallets) by switchable view.
2. Update the README.md of notifi-react-card to showcase WalletConnect.
3. Update the README.md of notifi-react-example
https://user-images.githubusercontent.com/127958634/229663169-c51575d5-6ec7-411c-9443-c991620a59df.mov

MVP-2364: WalletConnect support in SDK

---

package-lock.json
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/UserInfoPanel.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Updated infinite render loop issue caused by listening to missing targets data and setDiscordTarget triggering each other.
also added tooltip to update text for sms if they've typed 'stop'

Discord fixes

---

packages/notifi-react-card/lib/utils/NotificationHistoryUtils.tsx

- Add minus to balance change event details for outgoing transactions

Add minus to outgoing transactions

---

package-lock.json
packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/models/WalletBlockchain.ts
packages/notifi-core/lib/operations/CreateSource.ts
packages/notifi-react-card/lib/context/NotifiContext.tsx
packages/notifi-react-card/lib/utils/walletUtils.ts
packages/notifi-react-example/package.json
packages/notifi-react-example/src/EthosWalletProvider.tsx
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx
packages/notifi-react-example/src/NotifiCard/SuiNotifiCard.tsx
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Check on the video below to see how to work: 
https://user-images.githubusercontent.com/127958634/230806335-744fea45-c796-4057-ba34-3f781a4c3711.mp4

eric/MVP-2362: Support SUI chain

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts
packages/notifi-frontend-client/lib/models/FilterOptions.ts
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-frontend-client/lib/storage/InMemoryStorageDriver.ts
packages/notifi-frontend-client/lib/storage/LocalForageStorageDriver.ts
packages/notifi-frontend-client/lib/utils/resolveRef.ts

Add EVM login info to ClientConfiguration
Add support for custom event types

Update NotifiFrontendClient for DeltaPrime

---

packages/notifi-frontend-client/lib/client/ensureSource.ts

There are some additional issues in the NotifiFrontendClient which results in possible failures. Patch the discovered issues, optimizing for least changes.

Fix various issues in NotifiFrontendClient

---

packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

uuid doesnt work with vite. fortunately, we shouldnt need to pass in a randomly generated id. in the subscribe method, we create one with the name default anyways.

remove uuid

---

packages/notifi-react-card/README.md

Add Sui Doc in notifi-react-card README.md

Add Sui doc

---

packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/UserInfoPanel.tsx

wrong destination error message was displaying for tg

updates tg tooltip message

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts

Hello,
I think you forgot to add '0x' to signature

Fix incorrect signature - hex format signature

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts

1. Instead of copy-pasting type `SignMessageParams`, import it from `@notifi-network/notifi-core`
2. Implement a getter to get the userState. It is the replacement of the following 4 states in useNotifiClient (Check the detail in [SPIKE DOC](https://docs.colorfullife.ml/notifi/sdk-consolidate#step1-implement-getter-to-get-the-userstate)):
- isAuthenticated
- isInitialized
- expiry
- isTokenExpired
3. Implement `subscribeWallet` method in `NotifiFrontendClient` class. It is the replacement of original `subscribeWallet` method in `useNotifiSubscribe`

MVP-2512: Implement userState getter and subscribeWallet method in NotifiFrontendClient

---

packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/queries/fetchData.gql.ts
packages/notifi-graphql/lib/operations/FetchData.ts
packages/notifi-graphql/lib/operations/index.ts

As title, Add a new fetchData service into notifi-graphql

MVP-2513-patch: Add FetchDataService in notifi-gql

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts

1. Implement the updateWallets method in FrontendClient to be consumed by notifi-card.
2. Create new EventTypeItem for `WalletBalance`.
3. Implement `ensureWalletBalanceSources` and `getWalletBalanceSourceFilter`
***MERGE AFTER MVP-2513***
Need to also add example in notifi-react-example after MVP-2513 merged

MVP-2524: Implement updateWallets to FrontendClient

---

packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts

Implement XMTPTopicTypeItem type and its related helper functions that will be consumed by notifi-react-card

MVP-2529: Add XMTPTopicTypeItem to frontend client

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts
packages/notifi-frontend-client/lib/storage/InMemoryStorageDriver.ts
packages/notifi-frontend-client/lib/storage/LocalForageStorageDriver.ts

1. newSuiClient
2. condition check to add prefix in storage driver (memory & indexDB) 
3. SUI _signMessage/login method in NotifiFrontendClient
4. newSuiConfig

MVP-2534: Add NotifiSuiConfiguration and related methods in notifi-frontend-client

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts
packages/notifi-frontend-client/lib/storage/InMemoryStorageDriver.ts
packages/notifi-frontend-client/lib/storage/LocalForageStorageDriver.ts

1. newAcalaClient
2. condition check to add prefix in storage driver (memory & indexDB)
3. ACALA _signMessage/login method in NotifiFrontendClient
4. newAcalaConfig

MVP-2533: Add NotifiAcalaConfiguration and related methods in notifi-frontend-client

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts
packages/notifi-frontend-client/lib/storage/InMemoryStorageDriver.ts
packages/notifi-frontend-client/lib/storage/LocalForageStorageDriver.ts

1. newNearClient
2. condition check to add prefix in storage driver (memory & indexDB)
3. Near _signMessage/login method in NotifiFrontendClient
3. newNearConfig

MVP-2535: Add NotifiNearConfiguration and related methods in notifi-frontend-client

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts
packages/notifi-frontend-client/lib/storage/InMemoryStorageDriver.ts
packages/notifi-frontend-client/lib/storage/LocalForageStorageDriver.ts

1. newInjectiveClient
2. condition check to add prefix in storage driver (memory & indexDB)
3. Injective _signMessage/ login method in NotifiFrontendClient
4. newInjectiveConfig

MVP-2536: Add NotifiInjectiveConfiguration and related methods in notifi-frontclient

---

package-lock.json
packages/notifi-react-card/lib/components/common/ErrorStateCard.tsx
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/intercom/NotifiIntercomCardContainer.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCardContainer.tsx
packages/notifi-react-card/lib/utils/errorUtils.ts

https://user-images.githubusercontent.com/105258726/235272079-b92ab881-5e6a-42e3-9a3f-6a85d57fd3cd.mov

updates error handling

---

packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts
packages/notifi-frontend-client/lib/storage/InMemoryStorageDriver.ts
packages/notifi-frontend-client/lib/storage/LocalForageStorageDriver.ts

1. DRY storage code
2. Add configure newNotifiStorage -- default to localForage, but have an option for in-memory.

MVP-2555: Optimize frontendClient storage

---

packages/notifi-react-card/lib/hooks/useSubscriptionCard.ts

Implement 'frontendClient' object in 'useSubscriptionCard

MVP-2574 -Add 'frontEndClient' in 'useSubscriptionCard'(notifi-react-card)

---

packages/notifi-core/lib/models/NotificationHistory.ts
packages/notifi-graphql/lib/gql/fragments/NotificationHistoryEntryFragment.gql.ts
packages/notifi-react-card/lib/components/AlertHistory/AlertDetailsCard.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx
packages/notifi-react-card/lib/utils/NotificationHistoryUtils.tsx

'NotificationHistoryEntry' types consolidation (notifi-react-card/ notifi-graphql/ notifi-core) (For MVP-2591)

MVP-2592: 'NotificationHistoryEntry' types consolidation

---

packages/notifi-core/lib/models/ConnectedWallet.ts
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCard.tsx
packages/notifi-react-card/lib/context/NotifiClientContext.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

1. Cosolidate ConnectedWallet in core using graphql
2. Implment copyAuthorization method in NotifiFrontendClient
3. Implement the following 3 methods  in NotifiSubscriptionContext
- `Initial` effect/ 
- `render` method/ 
- `copyAuths` method
**NOTE**
The `render` and "inital fetch" logic of frontendClient is consolidated in `NotifiSubscriptionContext` in order to reduce the structural complexity. 
Another option is creating one more hook.

MVP-2578: "Initial fetchData" + "render" using frontendClient object (notifi-react-card)

---

packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx

If isCanaryActive === true , use frontendClient to fetch historyEntries

MVP-2591: "frontendClient" in AlertHistoryView (notifi-react-card)

---

packages/notifi-react-card/lib/components/subscription/subscription-card-views/ExpiredTokenViewCard.tsx

Implement 'frontendClient' object. When isCanaryActive === true, login with frontendClient

MVP-2601: Implement 'frontendClient' in ExpiredTokenViewCard component

---

packages/notifi-react-card/lib/components/subscription/EventTypeDirectPushRow.tsx
packages/notifi-react-card/lib/utils/frontendClient.ts

Implement subscribeAlert/ unsubscribeAlert using frontendClient
**NOTE**
Blocker: Not to merge until MVP-2585 is merged to main.

MVP-2586: 'subscribeAlert' method using frontendClient in EventTypeDirectPushRow  (notifi-react-card)

---

packages/notifi-react-card/lib/components/subscription/EventTypeCustomHealthCheckRow.tsx

Implement 'subscribeAlert/ unsubscrigbeAlert' that allowed client to subscribe alert using either hooks or frontendClient
https://user-images.githubusercontent.com/127958634/236739634-2f0575fe-37ce-4536-ae1f-c012e5334a3f.mp4

MVP-2609: 'subscribeAlert' method using frontendClient in 'EvnntTypeCustomHealthCheckRow' component

---

packages/notifi-react-card/lib/components/subscription/EventTypeCustomToggleRow.tsx

Implement 'subscribeAlert/ unsubscrigbeAlert' in `EventTypeCustomToggleRow` that allowed client to subscribe alert using either hooks or frontendClient

MVP-2608: 'subscribeAlert' method in EventTypeCustomToggleRow

---

packages/notifi-react-card/lib/components/subscription/EventTypePriceChangeRow.tsx

Implement 'subscribeAlert/ unsubscrigbeAlert' in EventTypePriceChangeRow that allowed client to subscribe alert using either hooks or frontendClient

MVP-2603: 'subscribeAlert'  in 'EventTypePriceChangeRow' 

---

packages/notifi-react-card/lib/components/subscription/EventTypeXMTPRow.tsx

Implement 'subscribeAlert/ unsubscrigbeAlert' in EventTypeXMTPRow that allowed client to subscribe alert using either hooks or frontendClient

MVP-2607: Add (un)subscribeAlert to EventTypeXMTPRow

---

packages/notifi-react-card/lib/components/subscription/EventTypeWalletBalanceRow.tsx

Implement 'subscribeAlert/ unsubscrigbeAlert' in EventTypeWalletBalanceRow that allowed client to subscribe alert using either hooks or frontendClient

MVP-2604: 'subscribeAlert' method in 'EvntTypeWalletBalanceRow'

---

packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-react-card/lib/components/subscription/EventTypeTradingPairsRow.tsx

Implement 'subscribeAlert/ unsubscrigbeAlert' in `EventTypeTradingPairsRow` that allowed client to subscribe alert using either hooks or frontendClient
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/5cfb2945-4b54-43d6-ad14-fb1278cbdd92

MVP-2605 'subscribeAlert' method in 'EvntTypeTradingPairsRow'

---

packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/utils/frontendClient.ts

Implement 'subscribeAlerts/ renewTargetGroup' in EventTypeXMTPRow that allowed client to subscribe alert and renewTargetGroup using either hooks or frontendClient

MVP-2610: 'subscribeAlerts' & 'renewTargetGroup' using frontendClient in NotifSubscribeButton

---

packages/notifi-react-card/lib/components/subscription/subscription-card-views/VerifyWalletView.tsx

Implement 'subscribeAlerts' and 'renewWallets' methos in `VerifyWalletView` that allowed client to subscribe alerts and renewWallets using either hooks or frontendClient

MVP-2611: Add 'SubscribeAlerts' and 'renewWallets' mehtod in VerifyWalletView

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Expose a reload function which:
- forces refetch of data
- updates the rendered data

Add Reload method to useNotifiSubscribe

---

packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

instant subscribe didnt have a try catch that would lead to a stuck loading state.
for example, if create source failed, the card would be stuck.

updates try catch for loading state

---

packages/notifi-axios-adapter/lib/fragments/sourceFragment.ts
packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-graphql/lib/gql/fragments/SourceFragment.gql.ts
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

The fusionEventTypeId needs to be fetched and compared.
We also need to resolve all the right config values in the frontend client

Fix Fusion Source Creation

---

packages/notifi-react-card/lib/components/subscription/EventTypeFusionHealthCheckRow.tsx

Fix the issue that the toggle check status does not change after clicking.

MVP-2744-patch: Fix FusionHealthCheck toggle switch

---

packages/notifi-frontend-client/README.md

Update the doc of frontend-client

MVP-2814: update README.md of notifi-frontend-client

---

packages/notifi-react-example/src/NotifiCard/KeplrCard.tsx
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx
packages/notifi-react-example/src/NotifiContextWrapper/KeplrNotifiContextWrapper.tsx
packages/notifi-react-example/src/NotifiContextWrapper/index.ts

Add Keplr example of consuming `useNotifiSubscriptionContext`/ `useNotifiClientCotext` outside of `NotifiSubscriptionCard`

MVP-2773#4: Keplr example consuming useNotifiSubscriptionContext/NotifiClientContext

---

packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx
packages/notifi-react-example/src/NotifiCard/SuiNotifiCard.tsx
packages/notifi-react-example/src/NotifiContextWrapper/SuiNotifiContextWrapper.tsx
packages/notifi-react-example/src/NotifiContextWrapper/index.ts

Add SUI example of consuming useNotifiSubscriptionContext/NotifiClientCotext outside of `NotifiSubscriptionCard`

MVP-2773#1: SUI example consuming  useNotifiSubscriptionContext/NotifiClientCotext

---

package-lock.json
packages/notifi-axios-utils/package.json
packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/models/WalletBlockchain.ts
packages/notifi-core/package.json
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts
packages/notifi-graphql/package.json
packages/notifi-react-card/lib/context/NotifiContext.tsx
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts
packages/notifi-react-hooks/package.json

Osmosis is another Cosmos chain, similar to Injective

Add support for 'Osmosis' value

---

packages/notifi-react-example/src/NotifiCard/MetamaskCard.tsx
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx
packages/notifi-react-example/src/NotifiContextWrapper/MetamaskNotifiContextWrapper.tsx
packages/notifi-react-example/src/NotifiContextWrapper/index.ts

We need a Metamask wallet support in our example. It will make future integration SDK (EVM) test easier.

MVP-2837: Create Metamask wallet example case

---

packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/utils/AlertConfiguration.ts

Not sure why we don't support this -- simple piping of things through

Add support for AlertFrequency in Fusion alerts

---

packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

The internal method already supports a null config, just support it in the batch api

Support deleting in subscribe

---

packages/notifi-axios-adapter/lib/fragments/notificationHistoryEntryFragment.ts
packages/notifi-graphql/lib/gql/fragments/NotificationHistoryEntryFragment.gql.ts

Support `eventDetailsJson` in `GenericEventDetails`

Add new GenericEventDetails property 'eventDetailsJson'

---

packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx
packages/notifi-react-card/lib/context/NotifiClientContext.tsx
packages/notifi-react-card/lib/context/NotifiContext.tsx
packages/notifi-react-card/lib/utils/frontendClient.ts
packages/notifi-react-example/src/NotifiCard/MetamaskCard.tsx
packages/notifi-react-example/src/NotifiContextWrapper/MetamaskNotifiContextWrapper.tsx
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts
packages/notifi-react-hooks/lib/utils/fetchDataImpl.ts

we don't want to tell TS to ignore a potentially undefined value but we should just run a check for it. we should handle them explicitly

removes non null assertions and cleans up unused variables

---

packages/notifi-react-card/lib/components/defaults.css

1. Description font detail(signupView)
2. bell color (Emp…tyHisotryView)
3. NotifiUserInfoPanelContainer background color

MVP-3035: Optimizae style

---

packages/notifi-react-card/lib/components/subscription/EventTypeCustomHealthCheckRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeFusionHealthCheckRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeHealthCheckRow.tsx

See the demo video below (Can be adopted to 1. CustomHealthCheck 2. HealthCheck 3. FusionHealthCheck)
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/17e13abc-7898-446a-952c-e0cb0a9dc382

MVP-3034: Auto input "%" while inputing custom value

---

packages/notifi-axios-adapter/lib/NotifiAxiosService.ts
packages/notifi-axios-adapter/lib/queries/getUnreadNotificationHistoryCountImpl.ts
packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/NotifiService.ts
packages/notifi-core/lib/operations/GetUnreadNotificationHistoryCount.ts
packages/notifi-core/lib/operations/index.ts
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/queries/getUnreadNotificationHistoryCount.gql.ts
packages/notifi-graphql/lib/operations/GetUnreadNotificationHistoryCount.ts
packages/notifi-graphql/lib/operations/index.ts
packages/notifi-react-example/src/FrontendClient/SolanaFrontendClient.tsx
packages/notifi-react-example/src/NotifiCard/SolanaCard.tsx
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

MVP-3179: support new query GetUnreadNotificationHistoryCount in SDK

---

packages/notifi-axios-adapter/lib/NotifiAxiosService.ts
packages/notifi-axios-adapter/lib/fragments/fusionNotificationHistoryEntryFragment.ts
packages/notifi-axios-adapter/lib/fragments/index.ts
packages/notifi-axios-adapter/lib/queries/getFusionNotificationHistoryImpl.ts
packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/NotifiService.ts
packages/notifi-core/lib/models/FusionNotificationHistory.ts
packages/notifi-core/lib/models/index.ts
packages/notifi-core/lib/operations/GetFusionNotificationHistory.ts
packages/notifi-core/lib/operations/index.ts
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/fragments/FusionNotificationHistoryEntryFragment.gql.ts
packages/notifi-graphql/lib/gql/queries/getFusionNotificationHistory.gql.ts
packages/notifi-graphql/lib/operations/GetFusionNotificationHistory.ts
packages/notifi-graphql/lib/operations/index.ts
packages/notifi-react-example/src/FrontendClient/SolanaFrontendClient.tsx
packages/notifi-react-example/src/NotifiCard/SolanaCard.tsx
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Add query method (frontend-client/ hooks)
Add demo (react-card/ frontend-client)

MVP-3198: support new query GetFusionNotificationHistory in SDK

---

packages/notifi-axios-adapter/lib/NotifiAxiosService.ts
packages/notifi-axios-adapter/lib/mutations/markFusionNotificationHistoryAsRead.ts
packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/NotifiService.ts
packages/notifi-core/lib/operations/MarkFusionNotificationHistoryAsRead.ts
packages/notifi-core/lib/operations/index.ts
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/mutations/markFusionNotificationHistoryAsRead.gql.ts
packages/notifi-graphql/lib/operations/MarkFusionNotificationHistoryAsRead.ts
packages/notifi-graphql/lib/operations/index.ts
packages/notifi-react-example/src/FrontendClient/SolanaFrontendClient.tsx
packages/notifi-react-example/src/NotifiCard/SolanaCard.tsx
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Add mutation methods (frontend-client/ hooks)
Add demo (react-card/ frontend-client)

MVP-3180: support new mutation MarkFusionNotificationHistoryAsRead

---

packages/notifi-frontend-client/lib/client/ensureSource.ts

fix wrong filter for fusionMutltiThreshold based on https://github.com/notifi-network/notifi-sdk-ts/pull/383#pullrequestreview-1625765497

fix filter for multithreshold

---

packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx
packages/notifi-react-card/lib/hooks/index.ts
packages/notifi-react-card/lib/hooks/useUnreadState.ts
packages/notifi-react-example/public/bell-icon.svg
packages/notifi-react-example/src/FrontendClient/SolanaFrontendClient.tsx
packages/notifi-react-example/src/NotifiCard/BellButton.module.css
packages/notifi-react-example/src/NotifiCard/BellButton.tsx
packages/notifi-react-example/src/NotifiCard/KeplrCard.tsx
packages/notifi-react-example/src/NotifiCard/MetamaskCard.tsx
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx
packages/notifi-react-example/src/NotifiCard/PolkadotCard.tsx
packages/notifi-react-example/src/NotifiCard/SolanaCard.tsx
packages/notifi-react-example/src/NotifiCard/SuiNotifiCard.tsx
packages/notifi-react-example/src/NotifiCard/WalletConnectCard.tsx
packages/notifi-react-example/src/NotifiContextWrapper/SolanaNotifiContextWrapper.tsx

- Add unread count number badge support 
- Add examples
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/96bd8998-df59-4064-a5fc-0b15f2040246

MVP-3317: Number badge in SDK

---

packages/notifi-frontend-client/lib/client/ensureTarget.ts
packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/PreviewCard.tsx
packages/notifi-react-card/lib/hooks/useIsTargetsExist.ts
packages/notifi-react-hooks/lib/utils/ensureTarget.ts

Use the hard-coded string "Default" for all discord targets

Only allow 'Default' for Discord targets

---

packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCard.tsx

Fix that the discord verify status not updating after verifying successfully
Checkout the video below
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/efc1b327-6c5d-40ad-b9cf-565be86bc117

CS-242: fix discord target auto update after verifying

---

packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/ExpiredTokenViewCard.tsx
packages/notifi-react-card/lib/hooks/useFrontendClientLogin.ts

We were missing the hardware login check for frontendClient in react-card

Use the right method for hardware login

---

packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/components/subscription/EventTypeFusionHealthCheckRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeFusionMultiThresholdRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeFusionToggleRow.tsx
packages/notifi-react-card/lib/hooks/SubscriptionCardConfig.ts

Just for Fusion for now
In the future we will move to a backend "Toggle" entity

Add support for displayname override

---

packages/notifi-react-card/lib/components/ConfigAlertModal.tsx
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/AlertsPanel.tsx

See the demo video below
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/9721f392-1d20-477a-bee0-d78a4773754d
This is only one out of total flows of New FTU. We will merge together all done (MVP-3437/ MVP-3438/ MVP-3439).

MVP-3437: Add new FTU flow for tenants which do not require destination

---

package-lock.json
packages/notifi-axios-adapter/lib/fragments/fusionNotificationHistoryEntryFragment.ts
packages/notifi-axios-adapter/lib/fragments/notificationHistoryEntryFragment.ts
packages/notifi-graphql/lib/gql/fragments/FusionNotificationHistoryEntryFragment.gql.ts
packages/notifi-graphql/lib/gql/fragments/NotificationHistoryEntryFragment.gql.ts
packages/notifi-react-card/lib/components/AlertHistory/AlertDetailsCard.tsx
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/utils/NotificationHistoryUtils.tsx
packages/notifi-react-card/package.json

- Support `messageHtml` in `BroadcastMessageEventDetails` (`notifi-graphql` & `notifi-axios-adaptor`)
- Support displaying hyperlink in History Detail View
Check out demo video below:
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/ae8a6189-d851-46e3-994c-760ea6cd3522

MVP-3381: Support messageHtml(broadcast) in SDK/ Render messageHtml in Detail View

---

package-lock.json
package.json
packages/notifi-react-card/lib/components/ConfigAlertModal.tsx
packages/notifi-react-card/lib/components/ConfigDestinationModal.tsx
packages/notifi-react-card/lib/components/NotifiEmailInput.tsx
packages/notifi-react-card/lib/components/NotifiTelegramInput.tsx
packages/notifi-react-card/lib/components/SignupBanner.tsx
packages/notifi-react-card/lib/components/VerifyBanner.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCard.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/PreviewCard.tsx
packages/notifi-react-example/.gitignore
packages/notifi-react-example/cypress.config.ts
packages/notifi-react-example/cypress/component/NotifiSubscriptionCard.cy.tsx
packages/notifi-react-example/cypress/fixtures/confirmedTargetGroup.json
packages/notifi-react-example/cypress/fixtures/notConfirmedTargetGroup.json
packages/notifi-react-example/cypress/fixtures/test-tenantConfig.json
packages/notifi-react-example/cypress/support/commands.tsx
packages/notifi-react-example/cypress/support/component-index.html
packages/notifi-react-example/cypress/support/component.ts
packages/notifi-react-example/cypress/tsconfig.json
packages/notifi-react-example/cypress/utils/graphql-utils.ts
packages/notifi-react-example/cypress/utils/index.ts
packages/notifi-react-example/package.json

1. MVP-3440 (commit 0e76b91): Establish Cypress environment
2. MVP-3441 (commit 42cf1ac): Refactor and finish test script for singup process (First Time User)
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/81834a50-f0ff-4760-b360-0bae77a997cd

MVP-3440 + MVP-3441: Cypress e2e test setup + test script for signup process

---

.github/workflows/cypress.yml
packages/notifi-graphql/codegen.yml
packages/notifi-graphql/package.json
packages/notifi-react-example/cypress.config.ts
packages/notifi-react-example/cypress/component/NotifiSubscriptionCard.cy.tsx
packages/notifi-react-example/package.json

As title, Add github action for cypress e2e CI

MVP-3442: CI for cypress E2E test

---

package-lock.json
packages/notifi-frontend-client/package.json
packages/notifi-graphql/codegen.yml
packages/notifi-graphql/package.json
packages/notifi-node/package.json
packages/notifi-react-card/lib/components/AlertHistory/AlertDetailsCard.tsx
packages/notifi-react-example/config-overrides.js
packages/notifi-react-example/package.json

Update graphql-request to fix the weird `sed` workaround

Update some dependencies

---

.github/pull_request_template.md
README.md

Add SDK E2E documentation in root README.md.

MVP-3443:  cypress E2E documentation

---

.github/pull_request_template.md

Remove some welcome text to avoid breaking the format
No need
N/A

chore: modify pr template

---

packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/components/subscription/EventTypeBroadcastRow.tsx

Add the displayName override for broadcast topic
No need
MVP-3742

MVP-3742: Add displayNameOverride for broadcast topic

---

packages/notifi-graphql/lib/gql/fragments/NotificationHistoryEntryFragment.gql.ts
packages/notifi-graphql/lib/gql/fragments/TenantUserAlertFragment.gql.ts

These are new types that are introduced to the API

Add new fields to GQL

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/mutations/updateUserSettings.gql.ts
packages/notifi-graphql/lib/gql/queries/getUserSettings.gql.ts
packages/notifi-graphql/lib/operations/GetUserSettings.ts
packages/notifi-graphql/lib/operations/UpdateUserSettings.ts
packages/notifi-graphql/lib/operations/index.ts
packages/notifi-react-example/src/FrontendClient/SolanaFrontendClient.tsx

Support new endpoints: userSettings & updateUserSettings
No need, just make sure gql package can be built.
MVP-3751

MVP-3751: Support new endpoints: userSettings & updateUserSettings

---

packages/notifi-graphql/lib/gql/fragments/FusionNotificationHistoryEntryFragment.gql.ts

Add missing fields - `targetTemplatesJson` and `templateVariablesJson` to Fusion notification history fragment.
Ready
Not needed
Not applicable

Add target info to DirectTenantMessageEventDetails response

---

packages/notifi-react-example/src/NotifiContextWrapper/MetamaskNotifiContextWrapper.tsx

`@notifi-network/notifi-react-example` supports EVM multi-chain switching.  
No need
MVP-3803
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/4ccd6fdf-348c-47a4-a1b8-c2b301b6e8b4
- DEMO video:

MVP-3803: notifi-react-example EVM multi-chain support

---

packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/PreviewCard.tsx

As handling too much conditional cardView logic , `subscriptionCardV1.tsx` becomes more and more difficult to follow and maintain. we need to refactor SubscriptionCardV1. 
This PR is specifically for `PreviewCard`
No Need
MVP-3832

SDK3.0/MVP-3832: Refactor cardView Preview

---

packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/ExpiredTokenViewCard.tsx

As handling too much conditional cardView logic , `subscriptionCardV1.tsx` becomes more and more difficult to follow and maintain. we need to refactor SubscriptionCardV1. 
This PR is specifically for `ExpiredTokenViewCard`
No Need
MVP-3832

SDK3.0/MVP-3649: Refactor cardView expired

---

.gitignore
packages/notifi-node-sample/README.md
packages/notifi-node-sample/lib/index.ts

Update the notifi-node-sample:
1. input arg of sendDirectPush endpoint
2. README.md
No Need (It is server code)
MVP-3865

MVP-3865: Update notifi-node-sample directPush with docs

---

packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/EditCardView.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/VerifyWalletView.tsx
packages/notifi-react-example/src/NotifiCard/SolanaCard.tsx

As handling too much conditional cardView logic , `subscriptionCardV1.tsx` becomes inefficient,  difficult to follow and maintain. we need to refactor SubscriptionCardV1. 
This PR is specifically for `EditCardView.tsx` & `VerifyWalletView.tsx`
No Need (TEST PASS)
MVP-3648 & MVP-3650

SDK3.0/MVP-3648+3650: Refactor cardView signup/edit/verify/onboarding view

---

packages/notifi-react-card/lib/components/subscription/EventTypeCustomHealthCheckRow.tsx

Fix wrong thresholdDirection value

---

packages/notifi-react-example/src/FrontendClient/InjectiveMetamaskFrontendClient.tsx
packages/notifi-react-example/src/FrontendClient/KeplrFrontendClient.tsx
packages/notifi-react-example/src/FrontendClient/PolkadotFrontendClient.tsx
packages/notifi-react-example/src/FrontendClient/SolanaFrontendClient.tsx
packages/notifi-react-example/src/FrontendClient/SuiFrontendClient.tsx
packages/notifi-react-example/src/FrontendClient/WalletConnectFrontendClient.tsx
packages/notifi-react-example/src/NotifiCard/KeplrCard.tsx
packages/notifi-react-example/src/NotifiCard/MetamaskCard.tsx
packages/notifi-react-example/src/NotifiCard/PolkadotCard.tsx
packages/notifi-react-example/src/NotifiCard/SolanaCard.tsx
packages/notifi-react-example/src/NotifiCard/SuiNotifiCard.tsx
packages/notifi-react-example/src/NotifiCard/WalletConnectCard.tsx
packages/notifi-react-example/src/NotifiContextWrapper/AcalaNotifiContextWrapper.tsx
packages/notifi-react-example/src/NotifiContextWrapper/KeplrNotifiContextWrapper.tsx
packages/notifi-react-example/src/NotifiContextWrapper/MetamaskNotifiContextWrapper.tsx
packages/notifi-react-example/src/NotifiContextWrapper/SolanaNotifiContextWrapper.tsx
packages/notifi-react-example/src/NotifiContextWrapper/SuiNotifiContextWrapper.tsx
packages/notifi-react-example/src/NotifiContextWrapper/WalletConnectNotifiContextWrapper.tsx
packages/notifi-react-example/src/walletProviders/EvmWalletProvider.tsx

As title: fix notifi-react-example .env type error
No need (Test passed)
MVP-3912

MVP-3912: fix notifi-react-example .env type error

---

packages/notifi-frontend-client/lib/storage/InMemoryStorageDriver.ts
packages/notifi-frontend-client/lib/storage/LocalForageStorageDriver.ts
packages/notifi-frontend-client/lib/storage/NotifiFrontendStorage.ts

Add config.walletBlockchain as part of JWT key
No need (TEST PASSED)
MVP-3899

MVP-3899:  Add config.walletBlockchain as part of JWT key

---

packages/notifi-axios-adapter/lib/fragments/fusionNotificationHistoryEntryFragment.ts
packages/notifi-axios-adapter/lib/fragments/notificationHistoryEntryFragment.ts
packages/notifi-dataplane/lib/NotifiDataplaneClient.ts
packages/notifi-dataplane/lib/index.ts
packages/notifi-dataplane/lib/types/FusionMessage.ts
packages/notifi-dataplane/lib/types/PublishFusionMessageResponse.ts
packages/notifi-dataplane/lib/types/index.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/fragments/FusionNotificationHistoryEntryFragment.gql.ts
packages/notifi-graphql/lib/gql/fragments/NotificationHistoryEntryFragment.gql.ts
packages/notifi-node-sample/README.md
packages/notifi-node-sample/lib/index.ts
packages/notifi-node/lib/client/NotifiClient.ts
packages/notifi-node/lib/client/createDpapiClient.ts
packages/notifi-node/lib/client/createNotifiService.ts
packages/notifi-react-card/lib/utils/NotificationHistoryUtils.tsx

1. SDK card being able to render fusion markdownHtml
2. SDK node-sample able to publishFusionEvent
3. Add doc to showcase how to publishFusionMessage & Video demo
No need
MVP-3941
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/11ddc05c-c80b-4972-9c8a-44e43c0d7c12

MVP-3941: Fusion DP html rendering/ Add fusionDP example

---

packages/notifi-react-card/lib/components/NotifiTelegramInput.tsx

fix: wrong classname

---

packages/notifi-axios-adapter/lib/fragments/fusionNotificationHistoryEntryFragment.ts
packages/notifi-axios-adapter/lib/fragments/notificationHistoryEntryFragment.ts
packages/notifi-graphql/lib/gql/fragments/FusionNotificationHistoryEntryFragment.gql.ts
packages/notifi-graphql/lib/gql/fragments/NotificationHistoryEntryFragment.gql.ts

As title:  fix Discriminated union (__typename) of  does not exist
No need (TEST PASSED)
MVP-3940

MVP-3940: fix Discriminated union (__typename) of  does not exist

---

packages/notifi-dataplane/lib/types/FusionMessage.ts
packages/notifi-node-sample/README.md
packages/notifi-node-sample/lib/index.ts

As title: Optimize variablesJson type in FusionMessage type
No need
MVP-3952

MVP-3952: Optimize variablesJson type in FusionMessage type

---

package-lock.json
package.json
packages/notifi-dapp-example/package.json
packages/notifi-dapp-example/src/app/layout.tsx
packages/notifi-dapp-example/src/app/notifi/page.tsx
packages/notifi-dapp-example/src/context/wallet/KeplrWalletProvider.tsx
packages/notifi-dapp-example/tailwind.config.ts

- Fix @trivago/prettier-plugin-sort-imports regression issue being not able to order nextjs "use client"
- Utilize cosmos-kit for wallet context provider
- Add blockchain (Injective) related logic
No need
MVP-3975

OpenDefi/MVP-3975: Wallet provider: Keplr + Injective

---

packages/notifi-core/lib/models/WalletBlockchain.ts
packages/notifi-react-card/lib/context/NotifiContext.tsx

fix Base chain support by adding baseParams in NotifiContext

fix Base Chain support

---

packages/notifi-dapp-example/src/app/globals.css
packages/notifi-dapp-example/src/app/layout.tsx
packages/notifi-dapp-example/src/app/notifi/layout.tsx
packages/notifi-dapp-example/src/app/page.tsx
packages/notifi-dapp-example/src/components/LoadingGlobal.tsx
packages/notifi-dapp-example/src/context/GlobalStateContext.tsx
packages/notifi-dapp-example/src/context/notifi/NotifiCardContext.tsx
packages/notifi-dapp-example/src/context/wallet/CosmosWalletProvider.tsx
packages/notifi-dapp-example/tailwind.config.ts

OpenDefi/MVP-3998: Add connect wallet page/ Optimize context

---

packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts

- convert input EVM chain publickey to lowercase
> **NOTE** only frontend-client is updated (`hooks`'s client is deprecated)
No need (PASSED)
MVP-4071

MVP-4071: convert input EVM chain publickey to lowercase (FrontendClient)

---

packages/notifi-frontend-client/README.md

add example showcasing how to use inputs (frontend-client)
No need
MVP-4061

MVP-4061: add example showcasing how to use inputs (frontend-client)

---

packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx

initial state should be 'null' instead of 'Done')
No need (TEST PASSED)
MVP-4085
> **NOTE**: This can fix the dashboard flashing issue from MVP-3958 (#473 ) CC: @marukohao

MVP-4085: optimize card ftuStage

---

package-lock.json
packages/notifi-dapp-example/src/app/globals.css
packages/notifi-dapp-example/src/components/AlertSubscription.tsx
packages/notifi-dapp-example/src/components/AlertSubscriptionBlock.tsx
packages/notifi-dapp-example/src/components/AlertSubscriptionRow.tsx
packages/notifi-dapp-example/src/components/HistoryListRow.tsx
packages/notifi-dapp-example/src/components/Toggle.tsx
packages/notifi-dapp-example/src/context/notifi/NotifiCardContext.tsx
packages/notifi-dapp-example/src/hooks/useSubscribeAlert.ts
packages/notifi-dapp-example/tailwind.config.ts
packages/notifi-react-card/lib/components/subscription/index.ts

Add Alert Subscription view and its related components
No need
MVP-3964

OpenDefi/MVP-3964: Alert Subscription

---

package-lock.json
packages/notifi-dapp-example/package.json
packages/notifi-dapp-example/src/app/layout.tsx
packages/notifi-dapp-example/src/app/notifi/page.tsx
packages/notifi-dapp-example/src/app/page.tsx
packages/notifi-dapp-example/src/context/wallet/NotifiWalletProvider.tsx

Native browser extension integration
MVP-4158

OpenDefi/MVP-4158: Native browser extension integration

---

packages/notifi-dapp-example/src/components/AlertSubscription.tsx
packages/notifi-dapp-example/src/components/AlertSubscriptionBlock.tsx

Increase alert-subscription-block height
No need
N/a

Increase alert-subscription-block height

---

package-lock.json
package.json
packages/notifi-dapp-example/package.json
packages/notifi-dapp-example/src/app/layout.tsx
packages/notifi-dapp-example/src/app/notifi/page.tsx
packages/notifi-dapp-example/src/app/page.tsx
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-wallet-provider/README.md
packages/notifi-wallet-provider/lib/context/NotifiWallets.tsx
packages/notifi-wallet-provider/lib/context/index.ts
packages/notifi-wallet-provider/lib/index.ts
packages/notifi-wallet-provider/package.json
packages/notifi-wallet-provider/tsconfig.json

Decouple WalletProvider as an independent package
No need
MVP-4157

OpenDefi/MVP-4157: create notifi-wallet-provider monorepo

---

packages/notifi-dapp-example/src/app/layout.tsx
packages/notifi-dapp-example/src/context/wallet/NotifiWalletsWrapper.tsx
packages/notifi-wallet-provider/lib/context/NotifiWallets.tsx
packages/notifi-wallet-provider/lib/hooks/useKeplr.ts
packages/notifi-wallet-provider/lib/hooks/useMetamask.ts
packages/notifi-wallet-provider/lib/index.ts
packages/notifi-wallet-provider/lib/types.ts

Wallet custom hook/ Major refactor
No need
MVP-4153

OpenDefi/MVP-4153: Wallet custom hook/ Major refactor

---

packages/notifi-dapp-example/src/app/notifi/ftu/layout.tsx
packages/notifi-dapp-example/src/app/notifi/layout.tsx
packages/notifi-dapp-example/src/components/AlertSubscription.tsx
packages/notifi-dapp-example/src/components/ConfigAlertModal.tsx
packages/notifi-dapp-example/src/components/ConfigDestinationModal.tsx
packages/notifi-dapp-example/src/components/DashboardSideBar.tsx
packages/notifi-dapp-example/src/components/DummyAlertsModal.tsx
packages/notifi-dapp-example/src/components/HistoryList.tsx

fix ui feedbacks

---

packages/notifi-dapp-example/src/app/notifi/expiry/layout.tsx
packages/notifi-dapp-example/src/app/notifi/ftu/layout.tsx
packages/notifi-dapp-example/src/app/notifi/signup/layout.tsx
packages/notifi-dapp-example/src/app/page.tsx
packages/notifi-dapp-example/src/components/EcosystemHero.tsx

Injective notifications copy update

---

packages/notifi-dapp-example/src/app/notifi/expiry/page.tsx

Fix showing expiry warning when logining in
No need
MVP-4251

MVP-4251: Fix showing expiry warning when logining in

---

packages/notifi-dapp-example/src/app/notifi/expiry/page.tsx
packages/notifi-dapp-example/src/app/notifi/ftu/layout.tsx
packages/notifi-dapp-example/src/app/notifi/signup/layout.tsx
packages/notifi-dapp-example/src/app/page.tsx
packages/notifi-dapp-example/src/context/GlobalStateContext.tsx

fix the header layout and error message bar style

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/utils/index.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/mutations/createFusionAlerts.gql.ts
packages/notifi-graphql/lib/operations/CreateFusionAlerts.ts
packages/notifi-graphql/lib/operations/index.ts

- New Service method: createFusionAlerts
- New FrontendClient method: ensureFusionAlerts
No need
MVP-4261

MVP-4261: New NotifiService call createFusionAlerts

---

packages/notifi-dapp-example/src/app/notifi/expiry/page.tsx
packages/notifi-dapp-example/src/components/NotifiSignUpButton.tsx
packages/notifi-dapp-example/src/context/GlobalStateContext.tsx
packages/notifi-dapp-example/src/context/NotifiTenantConfigContext.tsx
packages/notifi-dapp-example/src/hooks/useNotifiHistory.ts
packages/notifi-dapp-example/src/hooks/useNotifiTargets.ts
packages/notifi-dapp-example/src/hooks/useNotifiTopics.ts

remove console.log text and expiry view modal persisting after login
No need
MVP-4251

MVP-4251-1: fix UAT feedbacks

---

packages/notifi-dapp-example/src/components/NotifiSignUpButton.tsx
packages/notifi-dapp-example/src/hooks/useNotifiTargets.ts
packages/notifi-dapp-example/src/hooks/useNotifiTopics.ts
packages/notifi-graphql/lib/NotifiService.ts

Impl new subscribeFusionAlerts
No need
MVP-4262

OpenDefi/MVP-4262: Impl new subscribeFusionAlerts

---

packages/notifi-dapp-example/react-app-env.d.ts
packages/notifi-dapp-example/src/components/MobilePromptModal.tsx
packages/notifi-dapp-example/src/context/InjectiveWalletContext.tsx

injectiveWallet.strategies.leap and injectiveWallet.strategies.phantom still returns true event if the browser haven't installed the extension
add leap and phantom wallets to MobilePromptModalProps

fix wallet.isInstalled does not work

---

lerna.json
package-lock.json
packages/notifi-axios-adapter/package.json
packages/notifi-axios-utils/package.json
packages/notifi-core/package.json
packages/notifi-dataplane/package.json
packages/notifi-frontend-client/package.json
packages/notifi-graphql/package.json
packages/notifi-node-sample/package.json
packages/notifi-node/package.json
packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/package.json
packages/notifi-react-hooks/package.json
packages/notifi-solana-hw-login/package.json

fixed jwt token issue fox XION

---

packages/notifi-dapp-example/src/components/InputFieldSlack.tsx
packages/notifi-dapp-example/src/context/NotifiTargetContext.tsx
packages/notifi-graphql/lib/gql/fragments/SlackTargetFragment.gql.ts

Add slack webhook

---

packages/notifi-dapp-example/src/components/MobilePromptModal.tsx
packages/notifi-dapp-example/src/components/WalletSelectModal.tsx
packages/notifi-dapp-example/src/utils/stringUtils.ts

update wallet name to match the wallet app name

---

packages/notifi-dapp-example/src/app/notifi/signup/layout.tsx
packages/notifi-dapp-example/src/components/SignUpButton.tsx
packages/notifi-dapp-example/src/context/NotifiFrontendClientContext.tsx
packages/notifi-dapp-example/src/context/NotifiTenantConfigContext.tsx
packages/notifi-dapp-example/src/context/NotifiUserSettingContext.tsx
packages/notifi-dapp-example/src/hooks/useNotifiRouter.ts

Connect to notifi service before clicking signup button. See demo video below
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/f760265e-d969-4a47-8102-2aabad0bfa38
No need
MVP-4376

OpenDefi/MVP-4376: Connect to notifi service before clicking signup button

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-graphql/lib/gql/fragments/TenantConfigFragment.gql.ts
packages/notifi-react-example/src/FrontendClient/SolanaFrontendClient.tsx

The following two repos will consume this method
- notifi-dapp-example (cc: @marukohao )
- notifi-card-modal (WIP)
No need
MVP-4346

MVP-4346: Add fetchTenantConfig client method

---

packages/notifi-dapp-example/src/app/notifi/signup/page.tsx
packages/notifi-dapp-example/src/components/SignUpButton.tsx
packages/notifi-dapp-example/src/context/NotifiTargetContext.tsx
packages/notifi-dapp-example/src/context/NotifiTopicContext.tsx
packages/notifi-dapp-example/src/context/NotifiUserSettingContext.tsx
packages/notifi-dapp-example/src/hooks/useNotifiRouter.ts
packages/notifi-wallet-provider/lib/hooks/useKeplr.ts
packages/notifi-wallet-provider/lib/hooks/useMetamask.ts

fix existing user flashing UX
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/ec69343b-44a9-4943-a5d3-0f06735561ff
No need

OpenDefi/MVP-4376-patch: fix existing user flashing UX

---

packages/notifi-dapp-example/src/components/VerifyBanner.tsx

fix verify banner text

---

packages/notifi-dapp-example/src/components/DummyAlertsModal.tsx

update home page dummy alerts copy

---

packages/notifi-dapp-example/src/app/notifi/signup/layout.tsx
packages/notifi-dapp-example/src/app/notifi/signup/page.tsx
packages/notifi-dapp-example/src/components/DummyAlertsModal.tsx
packages/notifi-dapp-example/src/components/InputFieldSlack.tsx
packages/notifi-dapp-example/src/components/MobilePromptModal.tsx
packages/notifi-dapp-example/src/components/SignUpButton.tsx
packages/notifi-dapp-example/src/components/VerifyBanner.tsx
packages/notifi-dapp-example/src/components/WalletSelectModal.tsx
packages/notifi-dapp-example/src/context/NotifiFrontendClientContext.tsx
packages/notifi-dapp-example/src/context/NotifiTargetContext.tsx
packages/notifi-dapp-example/src/context/NotifiTenantConfigContext.tsx
packages/notifi-dapp-example/src/context/NotifiTopicContext.tsx
packages/notifi-dapp-example/src/context/NotifiUserSettingContext.tsx
packages/notifi-dapp-example/src/hooks/useNotifiRouter.ts
packages/notifi-dapp-example/src/utils/stringUtils.ts
packages/notifi-graphql/lib/gql/fragments/SlackTargetFragment.gql.ts
packages/notifi-wallet-provider/lib/hooks/useKeplr.ts
packages/notifi-wallet-provider/lib/hooks/useMetamask.ts

Add back the following commit to catch up the updated `stage-open-defi` banch
* cc7f57f3  (HEAD -> stage-open-defi, origin/stage-open-defi) 8 hours ago update home page dummy alerts copy (#529) (GitHub)
* 183c50fb  12 hours ago fix verify banner text (#528) (GitHub)
* d7321f39  12 hours ago OpenDefi/MVP-4376-patch: fix existing user flashing UX (#526) (GitHub)
* ca0f966d  30 hours ago MVP-4376: Connect to notifi service before clicking signup button (#524) (GitHub)
* 3d36f0f2  2 days ago update wallet name to match the wallet app name (#523) (GitHub)
* d81e8765  (eric/stage-open-defi/check-ftu-before-signup) 3 days ago Add slack webhook (#520) (GitHub)
No need

Add back missing odf commits to main

---

packages/notifi-card-modal/lib/context/NotifiTargetContext.tsx

Add NotifiTargetContext
No need
MVP-4340

notifi-card-modal/MVP-4340: NotifiTargetContext

---

package-lock.json
packages/notifi-card-modal/lib/context/NotifiContextWrapper.tsx
packages/notifi-card-modal/lib/context/NotifiHistoryContext.tsx
packages/notifi-card-modal/lib/context/NotifiTenantConfigContext.tsx
packages/notifi-card-modal/lib/context/NotifiTopicContext.tsx
packages/notifi-card-modal/lib/context/index.ts
packages/notifi-card-modal/package.json
packages/notifi-frontend-client/lib/utils/index.ts
packages/notifi-frontend-client/lib/utils/typeUtils.ts

- NotifiTopicContext
- Draft NotifiHisotryContext
No need
MVP-4341

notifi-card-modal/MVP-4341:  NotifiTopicContext / NotifiHisotryContext

---

packages/notifi-dapp-example/src/components/DummyAlertsModal.tsx
packages/notifi-dapp-example/src/context/NotifiFrontendClientContext.tsx

update copy on home page

---

package-lock.json
packages/notifi-card-modal-example/src/app/globals.css
packages/notifi-react/lib/context/GlobalStateContext.tsx
packages/notifi-react/lib/context/NotifiContextProvider.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx
packages/notifi-react/lib/context/NotifiTopicContext.tsx
packages/notifi-react/lib/context/NotifiUserSettingContext.tsx
packages/notifi-react/lib/context/index.ts
packages/notifi-react/lib/style/index.css

Finalize context by adding new context `NotifiUserSettingContext`
> The context will be the replacement of the `notifi-dapp-example`'s context 
> Will build a canary version for context refactor of `notifi-dapp-example`
> CC: @marukohao 
No need
MVP-4342

notifi-react/MVP-4342(pre-mvp-4343): finalaize context

---

packages/notifi-dapp-example/src/context/NotifiFrontendClientContext.tsx

fix type error

---

packages/notifi-card-modal-example/src/app/notifi/components-example/page.tsx
packages/notifi-react/lib/components/Connect.tsx
packages/notifi-react/lib/components/ErrorGlobal.tsx
packages/notifi-react/lib/components/Ftu.tsx
packages/notifi-react/lib/components/Inbox.tsx
packages/notifi-react/lib/components/LoadingGlobal.tsx
packages/notifi-react/lib/components/NotifiCardModal.tsx
packages/notifi-react/lib/components/index.ts
packages/notifi-react/lib/index.ts
packages/notifi-react/lib/style/notifi-card-modal.css

notifi-react/MVP-4343-1: scaffolding card-modal basic components

---

packages/notifi-dapp-example/src/app/notifi/dashboard/page.tsx
packages/notifi-dapp-example/src/components/AlertSubscriptionBlock.tsx
packages/notifi-dapp-example/src/components/AlertSubscriptionRow.tsx
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts

Update alert subscription section style 

---

packages/notifi-dapp-example/src/app/notifi/dashboard/page.tsx
packages/notifi-dapp-example/src/app/notifi/expiry/page.tsx
packages/notifi-dapp-example/src/app/notifi/signup/page.tsx
packages/notifi-dapp-example/src/components/AlertSubscription.tsx
packages/notifi-dapp-example/src/components/AlertSubscriptionBlock.tsx
packages/notifi-dapp-example/src/components/ConfigAlertModal.tsx
packages/notifi-dapp-example/src/components/DashboardDestinations.tsx
packages/notifi-dapp-example/src/components/DashboardSideBar.tsx
packages/notifi-dapp-example/src/components/DestinationInfoPrompt.tsx
packages/notifi-dapp-example/src/components/DestinationPanel.tsx
packages/notifi-dapp-example/src/components/DummyAlertsModal.tsx
packages/notifi-dapp-example/src/context/GlobalStateContext.tsx
packages/notifi-dapp-example/src/context/NotifiTargetContext.tsx
packages/notifi-dapp-example/src/utils/notifiHistoryUtils.ts

address UI feedbacks

---

packages/notifi-dapp-example/src/app/notifi/signup/layout.tsx
packages/notifi-dapp-example/src/components/AlertSubscription.tsx
packages/notifi-dapp-example/src/components/ConfigAlertModal.tsx

fix alert subscription section layout in FTU

---

packages/notifi-dapp-example/src/components/MobilePromptModal.tsx
packages/notifi-wallet-provider/lib/hooks/useKeplr.ts
packages/notifi-wallet-provider/lib/hooks/useMetamask.ts

remove wallet error message and fix MobilePromptModal layout

---

packages/notifi-frontend-client/lib/models/FusionEvent.ts
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/hooks/SubscriptionCardConfig.ts
packages/notifi-react/lib/context/NotifiTargetContext.tsx
packages/notifi-react/lib/context/NotifiTopicContext.tsx

- Add `subscriptionValueOrRef: ValueOrRef<string>;` in  `fusionMetadata`
- Add `topicGroupName?: string;` in `fusionEventTypeItem`
- Optimize TargetContext and TopicContext
No need
MVP-4297 milestone#1 context

MVP-4297-1-patch: context optimize

---

packages/notifi-react/lib/components/TopicGroupRow.tsx

topic group: New component for Grouped topics: TopicGroupRow.tsx
No need
MVP-4528

MVP-4528: TopicGroupRow

---

packages/notifi-react/lib/components/TopicGroupOptions.tsx
packages/notifi-react/lib/components/TopicGroupRow.tsx
packages/notifi-react/lib/components/TopicOptions.tsx
packages/notifi-react/lib/components/TopicRow.tsx
packages/notifi-react/lib/context/NotifiTopicContext.tsx
packages/notifi-react/lib/hooks/useUserInputParmToFilterOption.tsx
packages/notifi-react/lib/utils/index.ts
packages/notifi-react/lib/utils/topic.ts

- New compnent TopicGroup Option
- Refactor & consolidate TopicGroupRow & TopcRow
No need
MVP-4529

notifi-react/MVP-4529

---

packages/notifi-frontend-client/lib/models/FusionEvent.ts
packages/notifi-frontend-client/lib/utils/resolveRef.ts

add back subscriptionValueOrRef?: ValueOrRef<ValueType> into fusionEventMetadata.uiConfig
No need

MVP-4297-2-patch: Update fusionEventMetadata interface

---

packages/notifi-react/lib/components/TopicOptions.tsx
packages/notifi-react/lib/components/TopicRow.tsx

- Finish up group targeting and major refactor
- WIP: Add component and logic in TopicList 
> @marukohao - Please use this one to implement dapp-example
No need
MVP-4530

notifi-react/MVP-4530: consolidate TopicGroupOptions and TopicOptions + Major refactor

---

packages/notifi-react/lib/components/SubscriptionValueInput.tsx
packages/notifi-react/lib/components/TopicList.tsx
packages/notifi-react/lib/style/index.css
packages/notifi-react/lib/style/subscription-value-input.css
packages/notifi-react/lib/utils/constants.ts

- MVP-4531: TopicList & functional test & Style
- MVP-4552: SubscriptionValueInput
No need
MVP-4531 / MVP-4552

MVP-4531+4552: (GMX-related) TopicList & SubscriptionValueInput component

---

packages/notifi-react/lib/context/NotifiContextProvider.tsx

Fix notifi-react NotifiContextProvider missing input
No need

Fix notifi-react NotifiContextProvider missing input

---

packages/notifi-react-card/lib/hooks/useUnreadState.ts
packages/notifi-react-example/src/NotifiCard/BellButton.tsx

Clear notification count on click of bell icon

---

packages/notifi-react/lib/assets/Icons.tsx
packages/notifi-react/lib/components/TopicStack.tsx
packages/notifi-react/lib/style/index.css
packages/notifi-react/lib/style/topic-list.css
packages/notifi-react/lib/utils/topic.ts

- New component `TopicStack`
- Optimize topic util for `isValidTopicGroup` cc: @marukohao 
No need
MVP-4569

notifi-react/MVP-4569: TopicStack & topicUtil refactor

---

packages/notifi-react/lib/context/NotifiTopicContext.tsx
packages/notifi-react/lib/utils/index.ts
packages/notifi-react/lib/utils/topic.ts

notifi-react: NotifiTopicContext / topic utils update for TopicStackRow 
> `notifi-dapp-example` needs this to implement its own StackRow (for GMX) 
> CC: @marukohao 
No need
MVP-4608

MVP-4608: notifi-react context update

---

packages/notifi-react/lib/utils/topic.ts

MVP-4620-patch: chore - optimization of covertOptionValue

---

packages/notifi-react/lib/components/TopicOptions.tsx
packages/notifi-react/lib/hooks/useTopicStackRowInput.tsx

notifi-react/MVP-4553-patch: TopicStackRow default option value to userInputParm's defaultValue

---

packages/notifi-react/lib/hooks/useTopicStackRowInput.tsx

MVP-4553-patch-2: convert defaultValue from BE format to FE format

---

packages/notifi-react/lib/components/TopicOptions.tsx
packages/notifi-react/lib/components/TopicStack.tsx
packages/notifi-react/lib/components/TopicStackRow.tsx
packages/notifi-react/lib/components/TopicStackRowInput.tsx
packages/notifi-react/lib/hooks/useUserInputParmToFilterOption.tsx

Update TopicRow & TopicStackRow related to valueType rendering logic
> **IMPORTANT**
> This PR is blocked by PR #564 
> Can only be merged after PR #564 is merged --> This is the reason `cypress build failed`
> The logic of this feature also need to be adopted in `notifi-dapp-example` (GMX) CC: @marukohao 
No need
MVP-4621

MVP-4621: Topic components update for valueType condition rendering

---

packages/notifi-react/lib/context/NotifiContextProvider.tsx
packages/notifi-react/lib/context/NotifiHistoryContext.tsx
packages/notifi-react/lib/index.ts

MVP-4331: Update NotifiHistoryContext for state change subscription

---

packages/notifi-card-modal-example/src/context/NotifiContext.tsx
packages/notifi-react/lib/assets/Icons.tsx
packages/notifi-react/lib/components/HistoryRow.tsx
packages/notifi-react/lib/components/InboxHistoryList.tsx
packages/notifi-react/lib/style/history.css
packages/notifi-react/lib/style/index.css
packages/notifi-react/lib/utils/constants.ts

Impl `HistoryRow` and `HistoryList` using `NotifiHistoryContext`.
> @marukohao per talk, to improve the performance, we will also need to refactor the history related section by consuming `NotifiHistoryContext`. This is the reference to impl it.
> This one not yet include the `markAsRead` section as it is still WIP. Will update soon with another PR.
No need
MVP-4634

notifi-react/MVP-4634: 

---

packages/notifi-dapp-example/src/app/notifi/dashboard/page.tsx
packages/notifi-dapp-example/src/components/DestinationPanel.tsx
packages/notifi-dapp-example/src/context/NotifiContextWrapper.tsx

EVM wallet address to lower-case

EVM wallet-address to lower-case

---

packages/notifi-react/lib/context/NotifiUserSettingContext.tsx

Add isInitialLoaded mechanism to `NotifiUserSettingContext` to fix ftu process flickering
No need
MVP-4331

MVP-4331-patch-2: fix ftu process flickering

---

packages/notifi-react/lib/context/NotifiTargetContext.tsx
packages/notifi-react/lib/index.ts
packages/notifi-react/lib/utils/index.ts
packages/notifi-react/lib/utils/target.ts

- Introduce `isInitalLoaded` mechanism so that it keeps in isLoading state if `frontendClientStatus` is not authed
- Introduce `hasTarget` util method 
No need
MVP-4331

MVP-4331-patch-3: Optimize NotifiTargetContex

---

packages/notifi-dapp-example/src/components/DestinationPanel.tsx
packages/notifi-dapp-example/src/components/InputFieldWallet.tsx

GMX Feedback for slides - 88 and 90

gmx feedback

---

packages/notifi-react/lib/context/NotifiTargetContext.tsx

Fix the target listener failure caused by previous [merged PR](https://github.com/notifi-network/notifi-sdk-ts/pull/580)
No need
MVP-4331

MVP-4331-patch-4: fix target listener

---

packages/notifi-react/lib/context/NotifiTargetContext.tsx
packages/notifi-react/lib/utils/target.ts

MVP-4331-patch-5: Optimize NotifiTargetContext & Add targetUtils

---

packages/notifi-react/lib/components/Inbox.tsx
packages/notifi-react/lib/components/InboxConfigTargetList.tsx
packages/notifi-react/lib/components/InboxConfigTopic.tsx
packages/notifi-react/lib/components/TargetCta.tsx
packages/notifi-react/lib/components/TargetList.tsx
packages/notifi-react/lib/components/TargetStateBanner.tsx
packages/notifi-react/lib/style/inbox.css
packages/notifi-react/lib/style/index.css
packages/notifi-react/lib/style/target-list.css
packages/notifi-react/lib/style/target-state-banner.css
packages/notifi-react/lib/utils/constants.ts

notifi-react/MVP-4639: InboxConfigTargetList

---

packages/notifi-dapp-example/src/app/notifi/layout.tsx
packages/notifi-wallet-provider/lib/context/NotifiWallets.tsx

inbox page reload issue fixed - slide 7

reload issue fixed

---

packages/notifi-card-modal-example/src/app/notifi/components-example/page.tsx
packages/notifi-react/lib/assets/Icons.tsx
packages/notifi-react/lib/components/FtuTargetEdit.tsx
packages/notifi-react/lib/components/Inbox.tsx
packages/notifi-react/lib/components/InboxConfigTargetEdit.tsx
packages/notifi-react/lib/components/InboxHistory.tsx
packages/notifi-react/lib/components/NotifiCardModal.tsx
packages/notifi-react/lib/components/TargetList.tsx
packages/notifi-react/lib/components/TargetStateBanner.tsx
packages/notifi-react/lib/hooks/useIsTargetInputValid.tsx
packages/notifi-react/lib/style/inbox.css
packages/notifi-react/lib/style/index.css
packages/notifi-react/lib/style/target-state-banner.css
packages/notifi-react/lib/utils/constants.ts

notifi-react/MVP-4640: InboxConfigTargetList

---

packages/notifi-wallet-provider/lib/hooks/useBinance.ts
packages/notifi-wallet-provider/lib/hooks/useInjectedWallet.ts
packages/notifi-wallet-provider/lib/hooks/useKeplr.ts
packages/notifi-wallet-provider/lib/hooks/useWagmiWallet.ts

sign-wallet failed message updated

sign-wallet failed message updated

---

package-lock.json
packages/notifi-dapp-example/package.json
packages/notifi-dapp-example/src/app/notifi/layout.tsx
packages/notifi-dapp-example/src/app/page.tsx
packages/notifi-dapp-example/src/components/HistoryListRow.tsx
packages/notifi-dapp-example/src/components/TopicOptions.tsx
packages/notifi-dapp-example/src/components/TopicRow.tsx
packages/notifi-dapp-example/src/components/TopicStackRow.tsx
packages/notifi-dapp-example/src/components/TopicStackRowInput.tsx
packages/notifi-dapp-example/src/context/NotifiContextWrapper.tsx
packages/notifi-dapp-example/src/hooks/useUserInputParmToFilterOption.tsx
packages/notifi-react/lib/context/NotifiHistoryContext.tsx

update history and alert row components to use fusionId to create alert

---

packages/notifi-dapp-example/src/components/WalletSelectModal.tsx
packages/notifi-wallet-provider/lib/hooks/useKeplr.ts
packages/notifi-wallet-provider/lib/hooks/useMetamask.ts

https://notifi.atlassian.net/browse/MVP-4767

fixed no-wallet-installed bug

---

package-lock.json
packages/notifi-react-example-v2/next.config.mjs
packages/notifi-react-example-v2/src/app/notifi/layout.tsx

notifi-react/MVP-4335-patch: Optimize notifi-react-example-v2 for deployment

---

packages/notifi-dataplane/lib/types/FusionMessage.ts

Add back idempotency key as optional to fusion message

---

packages/notifi-react-example-v2/src/app/notifi/components-example/page.tsx
packages/notifi-react/lib/style/topic-list.css

notifi-react/MVP-4335-patch-3: chore: update style

---

packages/notifi-dapp-example/src/app/notifi/ftu/page.tsx
packages/notifi-dapp-example/src/app/notifi/signup/layout.tsx
packages/notifi-dapp-example/src/components/DashboardDestinations.tsx

https://notifi.atlassian.net/jira/software/c/projects/MVP/boards/1?selectedIssue=MVP-4850

add destination disclaimer

---

packages/notifi-dapp-example/src/app/layout.tsx
packages/notifi-dapp-example/src/app/notifi/layout.tsx
packages/notifi-dapp-example/src/app/page.tsx
packages/notifi-dapp-example/src/context/NotifiContextWrapper.tsx
packages/notifi-dapp-example/src/context/NotifiTenantConfigContext.tsx

MVP-4852: secret white-list alert topics for ODF

---

package-lock.json
packages/notifi-react/lib/context/NotifiTopicContext.tsx

chore: handle the error case when the format of 'inputs' is incorrect

---

packages/notifi-dapp-example/src/app/notifi/dashboard/layout.tsx
packages/notifi-dapp-example/src/app/notifi/dashboard/page.tsx
packages/notifi-dapp-example/src/app/notifi/expiry/layout.tsx
packages/notifi-dapp-example/src/app/notifi/ftu/layout.tsx
packages/notifi-dapp-example/src/app/notifi/page.tsx
packages/notifi-dapp-example/src/app/notifi/signup/layout.tsx
packages/notifi-dapp-example/src/hooks/useNotifiRouter.ts

As title. Demo below:
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/40ee5128-92df-4b3e-9c1d-ee4f55006bb4
No need
MVP-4931

MVP-4931: ODF secret link fast follow#2 (users entered with secret link should be landed to subscription view)

---

packages/notifi-dapp-example/src/components/InputFieldEmail.tsx
packages/notifi-dapp-example/src/hooks/useNotifiRouter.ts

As title
No need
MVP-4966
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/33457e3d-bc5e-4f10-81b8-d289d1d30128

MVP-4966: fix odf email regex issue

---

packages/notifi-react-example-v2/src/app/notifi/components-example/page.tsx
packages/notifi-react/lib/components/Connect.tsx
packages/notifi-react/lib/components/Expiry.tsx
packages/notifi-react/lib/components/HistoryDetail.tsx
packages/notifi-react/lib/components/HistoryRow.tsx
packages/notifi-react/lib/components/NotifiCardModal.tsx
packages/notifi-react/lib/components/TargetStateBanner.tsx
packages/notifi-react/lib/style/connect.css
packages/notifi-react/lib/style/history.css
packages/notifi-react/lib/style/index.css
packages/notifi-react/lib/style/nav-header.css
packages/notifi-react/lib/style/target-list.css
packages/notifi-react/lib/style/target-state-banner.css
packages/notifi-react/lib/style/topic-list.css
packages/notifi-react/lib/utils/constants.ts

As title, address UAT#3 p59 - p71
No need
MVP-4984

notifi-react/MVP-4984: Address UAT#3 

---

packages/notifi-react/README.md

MVP-4718: Add doc for notifi-react

---

packages/notifi-graphql/lib/gql/fragments/Web3TargetFragment.gql.ts
packages/notifi-react/lib/context/NotifiTargetContext.tsx
packages/notifi-react/lib/hooks/useTargetWallet.tsx
packages/notifi-react/lib/utils/target.ts

notifi-react/MVP-5038+4710-refactor: Optimize senderAddress section in useTargetWallet/ NotifiTargetContext

---

packages/notifi-react-example-v2/src/context/NotifiContextWrapper.tsx
packages/notifi-react/lib/components/TopicOptions.tsx
packages/notifi-react/lib/components/TopicStack.tsx
packages/notifi-react/lib/hooks/useUserInputParmToFilterOption.tsx
packages/notifi-react/lib/style/topic-list.css
packages/notifi-react/lib/utils/topic.ts

MVP-4709: fix gain suffix / fix topic options type conversion issue/ center custom input value

---

package-lock.json
packages/notifi-wallet-provider/lib/context/NotifiWallets.tsx
packages/notifi-wallet-provider/lib/hooks/usePhantom.ts
packages/notifi-wallet-provider/lib/types.ts
packages/notifi-wallet-provider/lib/utils/localStorageUtils.ts
packages/notifi-wallet-provider/lib/utils/solana.type.ts
packages/notifi-wallet-provider/lib/utils/wallet.ts
packages/notifi-wallet-provider/package.json

MVP-5077: Add Phantom Solana support in notifi-wallet-provider

---

packages/notifi-wallet-provider/lib/hooks/usePhantom.ts
packages/notifi-wallet-provider/lib/utils/solana.type.ts

MVP-5077-patch: fix notifi-wallet-provider phantom solana signArb return type

---

packages/notifi-react/lib/components/Connect.tsx
packages/notifi-react/lib/components/FtuAlertEdit.tsx
packages/notifi-react/lib/components/FtuAlertList.tsx
packages/notifi-react/lib/components/FtuTargetEdit.tsx
packages/notifi-react/lib/components/FtuTargetList.tsx
packages/notifi-react/lib/components/HistoryList.tsx
packages/notifi-react/lib/components/InboxConfigTargetEdit.tsx
packages/notifi-react/lib/components/TopicStackRowInput.tsx
packages/notifi-react/lib/style/connect.css
packages/notifi-react/lib/style/ftu.css
packages/notifi-react/lib/style/history.css
packages/notifi-react/lib/style/inbox.css
packages/notifi-react/lib/style/index.css
packages/notifi-react/lib/style/loading-animation.css
packages/notifi-react/lib/style/topic-list.css
packages/notifi-react/lib/utils/constants.ts

MVP-5076-2: allow specific view spinner css to be overridden

---

packages/notifi-react-example-v2/.env.local.example
packages/notifi-react/lib/components/SubscriptionValueInput.tsx
packages/notifi-react/lib/components/TargetInputField.tsx
packages/notifi-react/lib/components/TargetInputs.tsx
packages/notifi-react/lib/components/TargetList.tsx
packages/notifi-react/lib/components/TopicRow.tsx
packages/notifi-react/lib/components/TopicStackRowInput.tsx
packages/notifi-react/lib/context/NotifiFrontendClientContext.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx
packages/notifi-react/lib/context/NotifiTenantConfigContext.tsx
packages/notifi-react/lib/context/NotifiTopicContext.tsx
packages/notifi-react/lib/context/NotifiUserSettingContext.tsx
packages/notifi-react/lib/style/connect.css
packages/notifi-react/lib/style/inbox.css
packages/notifi-react/lib/style/index.css
packages/notifi-react/lib/style/nav-header.css
packages/notifi-react/lib/style/target-list.css
packages/notifi-react/lib/style/topic-list.css
packages/notifi-react/lib/utils/constants.ts
packages/notifi-react/lib/utils/target.ts

- Refactor target validation
- Optimize error handling
- address todo items
- update .env.local.example
MVP-5076

MVP-5076-3: Optimization and Refactor

---

packages/notifi-react/lib/components/HistoryDetail.tsx
packages/notifi-react/lib/components/TopicOptions.tsx
packages/notifi-react/lib/hooks/useUserInputParmToFilterOption.tsx
packages/notifi-react/lib/style/history.css
packages/notifi-react/lib/style/topic-list.css
packages/notifi-react/lib/utils/topic.ts

-  fix left border radius of history row
- fix the date time format in history detail view
- fix the history detail a tag show open a new browser tab
- update custom input suffix & prefix style slightly
- optimize custom input not to allow leading 0
MVP-5093

MVP-5093: Address feedback p74 - p77

---

packages/notifi-frontend-client/lib/models/FusionEvent.ts

As title. detail check the MVP-5094 spike doc
MVP-5094

MVP-5094-1: new interface in userInputParam for custom input constraints

---

packages/notifi-react/lib/components/TopicOptions.tsx
packages/notifi-react/lib/style/history.css

MVP-5094: Add customInputConstraints feature

---

packages/notifi-dapp-example/src/app/notifi/layout.tsx
packages/notifi-dapp-example/src/components/TopicOptions.tsx
packages/notifi-dapp-example/src/components/TopicStackRowInput.tsx
packages/notifi-dapp-example/src/hooks/useUserInputParmToFilterOption.tsx

Refactor suffix and prefix support in GMX

---

package-lock.json
packages/notifi-react-example-v2/next.config.mjs
packages/notifi-react-example-v2/package.json
packages/notifi-react/lib/components/NotifiCardModal.tsx

As title: Current bundled size (Considered acceptable):
- bundle size: ~600KB
- packed size: ~200KB
- gzipped size: ~60 KB
MVP-5156

MVP-5156: Add next bundle analyzer script for analyzing bundle efficiency

---

packages/notifi-react-example-v2/cypress.config.ts

Add test retries to avoid Network condition or cypress async handling issue
On-going
MVP-4717

MVP-4717-3: Add cypress retry mechanism 

---

packages/notifi-react/README.md

MVP-5161: chore: update README (Add migration guide)

---

packages/notifi-react/README.md

Update Docs (README) - Notifi-React

---

packages/notifi-react/lib/components/TopicList.tsx
packages/notifi-react/lib/components/TopicStack.tsx
packages/notifi-react/lib/components/TopicStackRow.tsx
packages/notifi-react/lib/components/TopicStackRowInput.tsx
packages/notifi-react/lib/context/NotifiTenantConfigContext.tsx
packages/notifi-react/lib/context/NotifiTopicContext.tsx
packages/notifi-react/lib/hooks/useTopicStackRowInput.tsx
packages/notifi-react/lib/utils/index.ts
packages/notifi-react/lib/utils/math.ts
packages/notifi-react/lib/utils/topic.ts

MVP-5163: group stack topic 

---

packages/notifi-dapp-example/src/app/globals.css
packages/notifi-dapp-example/src/components/SubscriptionValueInput.tsx
packages/notifi-dapp-example/src/components/TopicList.tsx
packages/notifi-dapp-example/src/components/TopicOptions.tsx
packages/notifi-dapp-example/src/components/TopicRow.tsx
packages/notifi-dapp-example/src/components/TopicStack.tsx
packages/notifi-dapp-example/src/components/TopicStackRow.tsx
packages/notifi-dapp-example/src/components/TopicStackRowInput.tsx
packages/notifi-dapp-example/src/context/NotifiContextWrapper.tsx
packages/notifi-dapp-example/src/hooks/useUserInputParmToFilterOption.tsx
packages/notifi-dapp-example/tailwind.config.ts
packages/notifi-frontend-client/lib/models/FusionEvent.ts
packages/notifi-react/lib/context/NotifiTenantConfigContext.tsx
packages/notifi-react/lib/context/NotifiTopicContext.tsx
packages/notifi-react/lib/utils/index.ts
packages/notifi-react/lib/utils/math.ts
packages/notifi-react/lib/utils/topic.ts

Support net fee alert - add group topic support to topic stack row

---

packages/notifi-react-example-v2/package.json
packages/notifi-react/README.md

- Add back missing dependency
- Add guide section of auto login in READMD.md)
MVP-5178

MVP-5178: Add guide section of auto login in READMD.md 

---

packages/notifi-react-example-v2/src/app/globals.css
packages/notifi-react-example-v2/src/app/notifi/components-example/page.tsx
packages/notifi-react-example-v2/src/hooks/useSignTransaction.tsx
packages/notifi-react/lib/context/NotifiFrontendClientContext.tsx
packages/notifi-react/lib/context/NotifiHistoryContext.tsx

As title
No need
MVP-5176 / MVP-5177
DEMO:
https://github.com/user-attachments/assets/b40a7c46-4409-436b-808a-01d9399e0486

MVP-5176+5177: Auto login feature

---

package-lock.json
packages/notifi-react-example-v2/package.json
packages/notifi-react/lib/context/NotifiFrontendClientContext.tsx
packages/notifi-react/lib/utils/frontendClient.ts
packages/notifi-react/package.json

- Update `notifi-react` dependencies to avoid xmtp related modules not found issue
- Optimize package.json files for `notifi-react` and `notifi-react-example-v2`
No impact
MVP-5023
> **NOTE** 
> - Pre-release canary version: [1.1.1-alpha.1](https://www.npmjs.com/package/@notifi-network/notifi-react/v/1.1.1-alpha.1)
> - No impact to package size (< 0.01MB)
> - Test result ([1.1.1-alpha.1](https://www.npmjs.com/package/@notifi-network/notifi-react/v/1.1.1-alpha.1)):
>    - cypress test: ✅ PASS
>    - npm install test:  ✅ PASS
>    - yarn install test: ✅ PASS
>    - pnpm install test: ✅ PASS

MVP-5203: `notifi-react` dependency enhancement

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts

MVP-5254: simplify nonce format (beginLoginViaTransaction)

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts

Remove the leading 3 bytes to fit EVM slot size
MVP-5332

MVP-5332: frontendClient.completeLoginViaTransaction return format update

---

packages/notifi-frontend-client/README.md
packages/notifi-react/README.md

As mentioned on title:
1. Update Doc for more auto-login details
2. Update `notifi-frontend-client` README.md which had been outdated 
MVP-5336

MVP-5336: Update doc for 'notifi-react' and 'notifi-frontend-client'

---

packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/mutations/logInByOidc.gql.ts
packages/notifi-graphql/lib/gql/mutations/loginByOAuth.gql.ts
packages/notifi-graphql/lib/operations/LogInByOAuth.ts
packages/notifi-graphql/lib/operations/LogInByOidc.ts
packages/notifi-graphql/lib/operations/index.ts

MVP-5364 (+MVP-5394-1): Add new Service method logInByOAuth

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts
packages/notifi-frontend-client/lib/storage/InMemoryStorageDriver.ts
packages/notifi-frontend-client/lib/storage/LocalForageStorageDriver.ts
packages/notifi-react/lib/context/NotifiFrontendClientContext.tsx
packages/notifi-react/lib/utils/frontendClient.ts

MVP-5365+3566+568: frontendClient / notifi-react  update for loginByOidc

---

packages/notifi-dapp-example/src/components/HistoryList.tsx
packages/notifi-dapp-example/src/context/NotifiContextWrapper.tsx
packages/notifi-graphql/lib/gql/queries/getFusionNotificationHistory.gql.ts
packages/notifi-react/lib/context/NotifiHistoryContext.tsx

add unread filter toggle

---

package-lock.json
packages/notifi-react-example-v2/package.json
packages/notifi-react-example-v2/src/app/globals.css
packages/notifi-react-example-v2/src/app/notifi/context-example/page.tsx
packages/notifi-react-example-v2/src/app/notifi/page.tsx
packages/notifi-react-example-v2/src/app/page.tsx
packages/notifi-react-example-v2/src/components/OidcGoogle.tsx
packages/notifi-react-example-v2/src/context/NotifiWalletContextWrapper.tsx
packages/notifi-react/lib/style/index.css

1. Add OIDC example in `notifi-react-example-v2`
2. Allow only localhost enviornment to use OIDC section in `notifi-react-example`
> Need to doc more detail flow for OIDC in upcoming ticket `MVP-5371`
MVP-5370
- Demo video
https://github.com/user-attachments/assets/6e914168-8674-4cbb-adab-65338f2f2de5

MVP-5370: OIDC example in @notifi-network/notifi-react-example-v2

---

packages/notifi-frontend-client/README.md
packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-react-example-v2/README.md
packages/notifi-react/README.md

- Add document for OIDC
- Add optional arg `gqlClientRequestConfig` in instantiateFrontendClient CC: @kai-notifi 
> Known issue: the cypress CI fails because of tenant specific issue (investigating)
MVP-5371

MVP-5371: Add document for OIDC

---

packages/notifi-frontend-client/README.md
packages/notifi-react-example-v2/README.md
packages/notifi-react/README.md

- notifi-react
- notifi-frontend-client
- notifi-react-example-v2)
MVP-5371

MVP-5371: Add documentation for OIDC 

---

packages/notifi-web-push-service-worker/lib/notifi-service-worker.ts
packages/notifi-web-push-service-worker/lib/notifi-service/analytics.ts
packages/notifi-web-push-service-worker/lib/notifi-service/index.ts
packages/notifi-web-push-service-worker/lib/types/index.ts
packages/notifi-web-push-service-worker/lib/utils/service-worker.ts

Add user interaction analytics to service worker

Add analytics to service worker

---

packages/notifi-web-push-service-worker/README.md

MVP-5461: Update doc of notifi-web-push-service-worker

---

packages/notifi-react/lib/components/HistoryRow.tsx

MVP-5319: Fix history row possibly contains noon & midnight

---

packages/notifi-react/lib/utils/constants.ts

As title
MVP-5318
- Demo video
https://github.com/user-attachments/assets/5793e8b1-aa2a-449a-9db2-a21e41d7f047

MVP-5318: Update the tooltip link 'more info' for Wallet target

---

packages/notifi-dapp-example/src/components/HistoryList.tsx

fix unread toggle on hide history header bug

---

packages/notifi-wallet-provider/lib/hooks/useBinance.ts
packages/notifi-wallet-provider/lib/hooks/useKeplr.ts
packages/notifi-wallet-provider/lib/hooks/usePhantom.ts
packages/notifi-wallet-provider/lib/hooks/useWagmiWallet.ts

…potential risk of infinite loading
- fix logging out unnecessary wallet uninstall error
- fix potential wallet infinite loading
MVP-5505

MVP-5505-patch: fix: wallet provider related issues

---

packages/notifi-react-example-v2/next.config.mjs
packages/notifi-react-example-v2/src/app/globals.css
packages/notifi-react-example-v2/src/app/notifi/context-example/page.tsx
packages/notifi-react-example-v2/src/app/notifi/page.tsx
packages/notifi-react-example-v2/src/app/page.tsx
packages/notifi-react-example-v2/src/components/OidcGoogle.tsx
packages/notifi-react/lib/components/Connect.tsx
packages/notifi-react/lib/components/FtuAlertEdit.tsx
packages/notifi-react/lib/components/FtuTargetEdit.tsx
packages/notifi-react/lib/components/FtuTargetList.tsx
packages/notifi-react/lib/components/InboxConfigTargetEdit.tsx
packages/notifi-react/lib/components/InboxConfigTargetList.tsx
packages/notifi-react/lib/components/TargetStateBanner.tsx
packages/notifi-react/lib/style/index.css

- Refactor `notifi-react` not to have global css override to avoid overriding consumer projects' style
- Add css source map for debug
MVP-5402

MVP-5402: refactor notifi-react global css override/ Add css source map for debug

---

README.md
packages/notifi-react-example-v2/cypress/component/NotifiCardModal.cy.tsx
packages/notifi-react-example-v2/cypress/support/commands.tsx
packages/notifi-react-example-v2/src/app/notifi/components-example/page.tsx
packages/notifi-react/README.md
packages/notifi-react/lib/components/Connect.tsx
packages/notifi-react/lib/components/NotifiCardModal.tsx
packages/notifi-react/lib/style/connect.css

As title
- Add test section in `Connect view` block
- MVP-5069
- Demo view

MVP-5069: Add customizable connect view footer

---

packages/notifi-react/lib/hooks/useConnect.tsx

Fixed: Connect Screen Stuck Issue
https://notifi.atlassian.net/browse/MVP-5582

fixed useEffect dependency

---

packages/notifi-dataplane/lib/types/FusionMessage.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/NotifiSubscriptionService.ts
packages/notifi-node/lib/client/NotifiNodeClient.ts

MVP-5589: Refactor NotifiNodeClient & give fusionMessage strong type

---

packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/queries/getActiveAlerts.gql.ts
packages/notifi-graphql/lib/operations/GetActiveAlerts.ts
packages/notifi-node/lib/client/NotifiNodeClient.ts

MVP-5620: support getActiveAlerts for notifi-node & notifi-graphql

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-react-example-v2/src/app/notifi/components-example/page.tsx
packages/notifi-react-example-v2/src/context/NotifiContextWrapper.tsx
packages/notifi-react-example-v2/src/hooks/useSignTransaction.tsx
packages/notifi-react/lib/context/NotifiFrontendClientContext.tsx

- Update `loginViaTransaction` (Avoid heating endpoint too often) - Expose new prop for `NotifiFrontendClient`: `isLogInViaTransactionAvailable` (Breaking change)
- Update `notifi-react-example-v2` (for new mechanism + enable EVM loginViaTransaction )
> Known issue: logInViaTransaction will fail with the following error: CC: @nimesh-notifi 
```bash
{
"errors": [
{
"message": "An unexpected error has occurred",
"extensions": {
"code": "ERROR_UNEXPECTED"
}
}
]
}
```
MVP-4558

MVP-5448: Update loginViaTransaction (Avoid heating endpoint too often)

---

packages/notifi-graphql/lib/gql/queries/getActiveAlerts.gql.ts

MVP-5620-patch: Make fusionEventId as non-potional argument

---

packages/notifi-graphql/lib/NotifiSubscriptionService.ts

As title and check the detail on below comments (code-highlighting)

MVP-5673-patch: prevent mis-emitting wsError event while from server refactor Type of getSubscriptionData

---

packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/NotifiSubscriptionService.ts
packages/notifi-node-sample/README.md
packages/notifi-node-sample/lib/index.ts
packages/notifi-node-sample/package.json
packages/notifi-node/README.md
packages/notifi-node/lib/client/NotifiNodeClient.ts

MVP-5592: Update documentation for `notifi-node` & `notifi-node-sample`

---

packages/notifi-dataplane/lib/types/FusionMessage.ts
packages/notifi-node-sample/README.md
packages/notifi-node/README.md

MVP-5592-4: polish README.md (notifi-node / notifi-node-sample / fusionMessage)

---

.husky/pre-push
.prettierrc
README.md
package-lock.json
package.json
packages/notifi-graphql/lib/operations/BeginLogInWithWeb3.ts
packages/notifi-node-sample/lib/middleware/notifiService.ts
packages/notifi-react/lib/components/FtuTargetEdit.tsx
packages/notifi-react/lib/components/HistoryRow.tsx
packages/notifi-react/lib/components/InboxConfigTargetEdit.tsx
packages/notifi-react/lib/components/SubscriptionValueInput.tsx
packages/notifi-react/lib/components/TargetInputField.tsx
packages/notifi-react/lib/components/TargetInputToggle.tsx
packages/notifi-react/lib/components/TargetStateBanner.tsx
packages/notifi-react/lib/context/NotifiHistoryContext.tsx
packages/notifi-react/lib/hooks/useConnect.tsx
packages/notifi-react/lib/hooks/useTargetWallet.tsx
packages/notifi-wallet-provider/lib/hooks/usePhantom.ts
packages/notifi-wallet-provider/lib/utils/localStorageUtils.ts

As title (Also Update the root README.md for related usage)
--> `Contribute to the repository (for contributors)` section.
MVP-5592

MVP-5592-patch#2: implement git pre-push event to ensure codebase format

---

packages/notifi-graphql/lib/NotifiService.ts

Add gzip & br as Accept-Encoding (http request header)

---

.prettierignore
packages/notifi-graphql/lib/NotifiService.ts

Revert accept encoding header / prettier ignore the auto generated type file

---

packages/notifi-node/__test__/NotifiNodeClient.test.ts

MVP-5700-2: Draft unit test case and script for notifi-node

---

.github/workflows/unitest.yml
packages/notifi-frontend-client/__test__/NotifiFrontendClient.test.ts
packages/notifi-frontend-client/jest.config.js
packages/notifi-frontend-client/package.json

MVP-5701: Draft unit test case and script for notifi-frontend-client

---

.github/workflows/unitest.yml
packages/notifi-frontend-client/__test__/NotifiFrontendClient.test.ts
packages/notifi-frontend-client/jest.config.js
packages/notifi-node/__test__/NotifiNodeClient.test.ts
packages/notifi-node/jest.config.js

> 100 times’ local test conducted with 0 100% success rate (0 failures)
MVP-5702

MVP-5702: Unitest Refactor / test/ Debug

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-graphql/lib/NotifiSubscriptionService.ts
packages/notifi-graphql/lib/gql/subscriptions/stateChanged.gql.ts
packages/notifi-react/lib/components/TopicStackRow.tsx

MVP-5742: Support new features in notifi-graphql & frontendClient 

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-react/lib/context/NotifiHistoryContext.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx

MVP-5743: Replace window.focus Event with addEventListener

---

packages/notifi-react/lib/components/HistoryDetail.tsx
packages/notifi-react/lib/style/history.css

replaced subject with topic name in inbox message detail UI
https://notifi.atlassian.net/browse/MVP-5730

replaced subject with topic-name

---

package-lock.json
packages/notifi-frontend-client/README.md
packages/notifi-frontend-client/__test__/NotifiFrontendClient.test.ts
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-frontend-client/package.json
packages/notifi-graphql/lib/NotifiEventEmitter.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/NotifiSubscriptionService.ts
packages/notifi-node-sample/lib/index.ts
packages/notifi-node-sample/lib/middleware/notifiService.ts
packages/notifi-node/README.md
packages/notifi-node/lib/client/NotifiNodeClient.ts
packages/notifi-react-example-v2/cypress/support/commands.tsx
packages/notifi-react-example-v2/src/app/notifi/components-example/page.tsx
packages/notifi-react-example-v2/src/components/OidcGoogle.tsx
packages/notifi-react-example-v2/src/hooks/useSignTransaction.tsx
packages/notifi-react/lib/context/NotifiHistoryContext.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx

- stop exposing subscription object. Instead, handle unsubscribe in emitter
- Update notifi-node & notifi-frontend-client
- Impl Unit test/ Fix frontendClient not supporting nodejs env issue
- Cleanup & minor refactor
MVP-5744

MVP-5744-2: Test/ Debug/ update corresponding changed packages - node, node-sample, notifi-react.

---

packages/notifi-frontend-client/README.md
packages/notifi-node/README.md

MVP-5745: Update doc

---

packages/notifi-dapp-example/src/context/NotifiContextWrapper.tsx

MVP-5635: fix useQuery interface break after 2.1.0 (dapp-example)

---

packages/notifi-react/lib/context/NotifiTopicContext.tsx

MVP-5800: subscribeAlertsDefault should not support subscribing stackable topic

---

packages/notifi-react/lib/components/TargetList.tsx
packages/notifi-react/lib/components/TargetListItem.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx

Reform the targetListItem and targetList (Disable toggle targets rendering for now)
MVP-5810

MVP-5810: Update targetListItem & TargetList

---

packages/notifi-react/lib/components/TargetListItem.tsx
packages/notifi-react/lib/utils/target.ts

As title.
Cypress test Failure is expected since the change of Ftu & target flow. The cypress test script update will updated once the feature is done.

MVP-5811 Update FormTargets rendering logic

---

packages/notifi-react/lib/components/TargetList.tsx
packages/notifi-react/lib/components/TargetListItem.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx

- add 'signupCtaProps' var for un-registered targets 
- Reuse TargetCTA for un-registered target 
- draft prototype of toggle target 
> Known issue: Cypress component test test failure is expected because of target ftu flow updated

MVP-5812: Update ToggleTargets rendering logic

---

packages/notifi-react/lib/components/FtuTargetList.tsx
packages/notifi-react/lib/components/TargetCta.tsx
packages/notifi-react/lib/components/TargetInputField.tsx
packages/notifi-react/lib/components/TargetList.tsx
packages/notifi-react/lib/components/TargetListItem.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx
packages/notifi-react/lib/style/target-list.css
packages/notifi-react/lib/utils/target.ts

MVP-5814: pdate TargetStateBanner & target removeable render logic

---

packages/notifi-react/lib/components/TargetListItem.tsx
packages/notifi-react/lib/components/TargetListItemAction.tsx
packages/notifi-react/lib/components/TargetListItemForm.tsx
packages/notifi-react/lib/components/TargetListItemToggle.tsx
packages/notifi-react/lib/hooks/useTargetListItem.tsx

MVP-5815: Target related component restructure (TargetListItem)

---

packages/notifi-react/lib/components/TargetCta.tsx
packages/notifi-react/lib/components/TargetList.tsx
packages/notifi-react/lib/components/TargetListItemForm.tsx
packages/notifi-react/lib/components/TargetListItemToggle.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx
packages/notifi-react/lib/hooks/useTargetListItem.tsx
packages/notifi-react/lib/style/index.css
packages/notifi-react/lib/style/target-inputs.css
packages/notifi-react/lib/style/target-list.css
packages/notifi-react/lib/style/target-state-banner.css
packages/notifi-react/lib/style/topic-list.css
packages/notifi-react/lib/utils/constants.ts

MVP-5816-1 : MVP-5816 [SDK: notifi-react] Update Style POC

---

packages/notifi-react-example-v2/cypress/component/NotifiCardModal.cy.tsx
packages/notifi-react/lib/components/HistoryList.tsx
packages/notifi-react/lib/components/InboxConfigTargetList.tsx
packages/notifi-react/lib/components/TargetList.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx
packages/notifi-react/lib/hooks/useTargetListItem.tsx
packages/notifi-react/lib/style/connect.css
packages/notifi-react/lib/style/error.css
packages/notifi-react/lib/style/ftu.css
packages/notifi-react/lib/style/history.css
packages/notifi-react/lib/style/inbox.css
packages/notifi-react/lib/style/index.css
packages/notifi-react/lib/style/target-inputs.css
packages/notifi-react/lib/style/target-state-banner.css
packages/notifi-react/lib/style/tooltip.css
packages/notifi-react/lib/style/topic-list.css
packages/notifi-react/lib/utils/constants.ts

- Optimize CSS
- Initial test script for CICD test & local test. 
MVP-5817

MVP-5817-1: Optimize style & add component test script 

---

packages/notifi-react/lib/components/TopicRow.tsx
packages/notifi-react/lib/components/TopicStackRow.tsx
packages/notifi-react/lib/style/tooltip.css
packages/notifi-react/lib/style/topic-list.css

MVP-5930 new target flow - M2 [SDK: notifi-react] reform topic list tooltip

---

packages/notifi-frontend-client/lib/client/blockchains.ts

Add Blockchains Rome and Sonic to list of supported wallets

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts

trying use new SDK card with the added new chains in the integration and getting the error ' Unsupported wallet blockchain: ROME'. Finding out we need to adding the chains in login method to avoid this error message.
tested in notifi-react-example-v2

Fix adding Rome and Sonic chain

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-react/lib/components/TargetList.tsx
packages/notifi-react/lib/components/TargetListItem.tsx
packages/notifi-react/lib/components/TargetListItemToggle.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx
packages/notifi-react/lib/hooks/useTargetListItem.tsx
packages/notifi-react/lib/utils/target.ts

- Migrate TG from form target to toggle target
- refactor related components
> **KNOW ISSUE** Cypress CICD fails because it requires updating test script (upcoming ticket)

MVP-5933: update TG target component & target context

---

packages/notifi-react/lib/components/TopicOptions.tsx
packages/notifi-react/lib/components/TopicStackRowInput.tsx

MVP-5984: Optimize reaction speed when switching between topic options

---

packages/notifi-react/lib/components/Inbox.tsx
packages/notifi-react/lib/components/InboxNavTabs.tsx

MVP-6004: discover-tab:  Scaffold the components

---

packages/notifi-frontend-client/lib/client/blockchains.ts
packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts
packages/notifi-react/lib/hooks/useTargetWallet.tsx

-  Describe the purpose of the change
As title

MVP-5971: LoginWithWeb3 type patch: conflict EVM chains & wallet target conflict

---

packages/notifi-react/lib/components/Inbox.tsx
packages/notifi-react/lib/components/InboxDiscover.tsx
packages/notifi-react/lib/utils/constants.ts

MVP-6005: Create new components for the Discover view & reform the PoC structure

---

README.md
packages/notifi-react-example-v2/cypress/component/NotifiCardModal.cy.tsx
packages/notifi-react-example-v2/cypress/support/commands.tsx
packages/notifi-react-example-v2/src/app/notifi/components-example/page.tsx
packages/notifi-react/lib/components/Inbox.tsx

- Update doc
- Update Cypress test (CICD)
Update component test case
https://github.com/user-attachments/assets/705bdf69-b5a2-4995-81e7-164e0a50d978

MVP-6007: M3 - Testing/ debug/ Refactor/ CICD test (cypress)/ Documentation 

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-frontend-client/lib/models/TenantConfig.ts

As title
> KNOW ISSUE:
> All tests CICD failed. Reason: WalletBlockchain type is removed (Fixing on BE) CC: @vaishali-notifi @nimesh-notifi

MVP-6029: Tenant config v2 poc

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/models/FusionEvent.ts
packages/notifi-frontend-client/lib/models/TenantConfig.ts
packages/notifi-frontend-client/lib/utils/index.ts
packages/notifi-frontend-client/lib/utils/tenant.ts
packages/notifi-react-example-v2/cypress/utils/topic-utils.ts
packages/notifi-react/lib/components/TopicList.tsx
packages/notifi-react/lib/components/TopicOptions.tsx
packages/notifi-react/lib/components/TopicRow.tsx
packages/notifi-react/lib/components/TopicStackRowInput.tsx
packages/notifi-react/lib/context/NotifiTopicContext.tsx
packages/notifi-react/lib/hooks/useTopicStackRowInput.tsx
packages/notifi-react/lib/hooks/useUserInputParmToFilterOption.tsx
packages/notifi-react/lib/utils/topic.ts

As title
> Will need to have  an final V2 tenant config payload to do verification. @marukohao

MVP-6031: update component test script/ Optimize frontendClient (WIP)

---

packages/notifi-frontend-client/lib/models/TenantConfig.ts
packages/notifi-frontend-client/lib/utils/tenant.ts
packages/notifi-react/lib/context/NotifiTenantConfigContext.tsx

MVP-6031-patch: rename TenantConfigMetadata to CardConfigItemV2

---

packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/fragments/ErrorFragments.gql.ts
packages/notifi-graphql/lib/gql/mutations/deleteDiscordTarget.gql.ts
packages/notifi-graphql/lib/gql/mutations/deleteEmailTarget.gql.ts
packages/notifi-graphql/lib/gql/mutations/deleteSlackChannelTarget.gql.ts
packages/notifi-graphql/lib/gql/mutations/deleteSmsTarget.gql.ts
packages/notifi-graphql/lib/gql/mutations/deleteTelegramTarget.gql.ts
packages/notifi-graphql/lib/gql/mutations/deleteWeb3Target.gql.ts
packages/notifi-graphql/lib/operations/DeleteDiscordTarget.ts
packages/notifi-graphql/lib/operations/DeleteEmailTarget.ts
packages/notifi-graphql/lib/operations/DeleteSlackChannelTarget.ts
packages/notifi-graphql/lib/operations/DeleteSmsTarget.ts
packages/notifi-graphql/lib/operations/DeleteTelegramTarget.ts
packages/notifi-graphql/lib/operations/DeleteWeb3Target.ts
packages/notifi-graphql/lib/operations/index.ts

MVP-6145:  Implement deleteTarget client methods 

---

packages/notifi-frontend-client/lib/client/alterTarget.ts

MVP-6146: New alterTarget method to replace ensureTarget 

---

packages/notifi-frontend-client/lib/client/alterTargetGroup.ts

MVP-6147: Implement alterTargetGroup to replace ensureTargetGroup

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/ensureTarget.ts
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-react-example-v2/cypress/component/NotifiCardModal.cy.tsx
packages/notifi-react/README.md
packages/notifi-react/lib/components/Connect.tsx
packages/notifi-react/lib/components/LoadingGlobal.tsx
packages/notifi-react/lib/components/NotifiCardModal.tsx
packages/notifi-react/lib/components/TargetInputField.tsx
packages/notifi-react/lib/components/TargetList.tsx
packages/notifi-react/lib/components/TargetListItemToggle.tsx
packages/notifi-react/lib/components/TopicList.tsx
packages/notifi-react/lib/components/TopicRow.tsx
packages/notifi-react/lib/components/TopicStackRow.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx
packages/notifi-react/lib/hooks/useTargetListItem.tsx
packages/notifi-react/lib/style/tooltip.css
packages/notifi-react/lib/style/topic-list.css
packages/notifi-react/lib/utils/constants.ts
packages/notifi-react/lib/utils/target.ts
packages/notifi-solana-hw-login/README.md

sdk4 m2 for UAT - content as title. The video attached herewith 
https://github.com/user-attachments/assets/f601699f-5094-4ed5-9560-36ca3818d2e2
- ~~TG verification will not not go through until endpoint supports it CC: @kai-notifi~~
- 250112 update: ready on dev. Prod is not ready. DO NOT MERGE before bing ready on prod.
> Canary version: [4.0.2-alpha.24](https://www.npmjs.com/package/@notifi-network/notifi-react/v/4.0.2-alpha.24)

SDK4-new-target-flow STAGE (M2) 

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/alterTarget.ts
packages/notifi-frontend-client/lib/client/alterTargetGroup.ts
packages/notifi-react/lib/context/NotifiTargetContext.tsx

MVP-6148: update targetGroup related components and contexts (notifi-react)

---

README.md
packages/notifi-frontend-client/README.md
packages/notifi-frontend-client/__test__/NotifiFrontendClient.test.ts
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/alterTarget.ts
packages/notifi-frontend-client/lib/client/alterTargetGroup.ts
packages/notifi-frontend-client/lib/client/ensureTarget.ts
packages/notifi-react/lib/context/NotifiTargetContext.tsx

MVP-6149: Target refactor -  Polish /cypress test/ debug/ document

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/blockchains.ts

Add Sei, Swellchain, BOB

---

packages/notifi-graphql/codegen.yml
packages/notifi-react/lib/hooks/useTargetListItem.tsx

MVP-6255:  Open target verify link w/ current window if popup is blocked

---

LICENSE
README.md
packages/notifi-react-wallet-target-plugin/README.md
packages/notifi-react/README.md

MVP-6218: Wallet Target plugin Documentation (xmtp-isolation)

---

package-lock.json
packages/notifi-react-wallet-target-plugin/package.json

MVP-6214-patch: Modify peer dependency version of plugin to fix lerna publish failure

---

packages/notifi-dapp-example/src/hooks/useTargetWallet.ts

MVP-6214-patch1: Add back mis-deleted useTargetWallet.ts to dapp-example

---

packages/notifi-frontend-client/__test__/NotifiFrontendClient.test.ts

MVP-6275: fix frontend-client unittest flaky issue

---

.eslintignore
.gitattributes
.prettierignore

MVP-6301-patch: chore: optimize .gitattributes & ignores files for auto generated docs

---

packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/queries/getSmartLinkConfig.gql.ts
packages/notifi-graphql/lib/operations/GetSmartLinkConfig.ts
packages/notifi-graphql/lib/operations/index.ts

MVP-6285: Support SmartLink related services-getSmartLinkConfig

---

packages/notifi-react/lib/components/Tooltip.tsx
packages/notifi-react/lib/style/tooltip.css

Update tooltip class name to be more specific

Update tooltip class name

---

packages/notifi-frontend-client/lib/models/SmartLinkConfig.ts
packages/notifi-react/lib/components/NotifiSmartLink.tsx
packages/notifi-react/lib/components/index.ts
packages/notifi-react/lib/context/NotifiSmartLinkContext.tsx
packages/notifi-react/lib/context/index.ts

- MVP-6290: Implement NotifiSmartLinkContext
- MVP-6291: Create Dummy NotifiSmartLink Component ( No style)

MVP-6290+6291: init SmartLink  support in notifi-react

---

packages/notifi-dataplane/lib/types/SmartLinkAction.ts
packages/notifi-frontend-client/lib/models/SmartLinkConfig.ts
packages/notifi-react-example-v2/src/app/notifi/smart-link-example/page.tsx
packages/notifi-react-example-v2/src/context/NotifiContextWrapper.tsx
packages/notifi-react/lib/components/ActionInputTextBoxNumber.tsx
packages/notifi-react/lib/components/NotifiSmartLink.tsx
packages/notifi-react/lib/components/SmartLinkAction.tsx
packages/notifi-react/lib/style/index.css
packages/notifi-react/lib/style/smartlink.css

MVP-6293: Dummy Page in notifi-react-example-v2 with rendering plian html action items w/o styling

---

packages/notifi-react-example-v2/src/app/link/[slug]/page.tsx
packages/notifi-react-example-v2/src/app/link/layout.tsx
packages/notifi-react-example-v2/src/components/NotifiSmartLinkExample.tsx
packages/notifi-react/lib/components/NotifiSmartLink.tsx
packages/notifi-react/lib/components/SmartLinkAction.tsx
packages/notifi-react/lib/context/NotifiSmartLinkContext.tsx

- Update Example pkg for the real use case.
- Support preAction that enable users to validate or do things before actually execute the Action. 
https://github.com/user-attachments/assets/daf35680-8f14-45d5-abac-4b6f6473f9d4

MVP-MVP-6295-patch: support preAction feat. / Update example pkg

---

packages/notifi-react-example-v2/src/app/link/[slug]/page.tsx
packages/notifi-react-example-v2/src/components/NotifiSmartLinkExample.tsx
packages/notifi-react/lib/components/ActionInputCheckBox.tsx
packages/notifi-react/lib/components/ActionInputTextBoxNumber.tsx
packages/notifi-react/lib/components/ActionInputTextBoxString.tsx
packages/notifi-react/lib/components/NotifiSmartLink.tsx
packages/notifi-react/lib/components/SmartLinkAction.tsx
packages/notifi-react/lib/context/NotifiSmartLinkContext.tsx
packages/notifi-react/lib/style/smartlink.css

MVP-6329: Construct data structure for updating Action User Inputs

---

packages/notifi-react-example-v2/src/app/link/[slug]/page.tsx
packages/notifi-react-example-v2/src/components/NotifiSmartLinkExample.tsx
packages/notifi-react/lib/components/SmartLinkAction.tsx

MVP-6330-patch: Optimize pre-action 

---

packages/notifi-react-example-v2/src/app/link/layout.tsx
packages/notifi-react/lib/components/ActionInputCheckBox.tsx
packages/notifi-react/lib/components/ActionInputTextBoxNumber.tsx
packages/notifi-react/lib/components/ActionInputTextBoxString.tsx
packages/notifi-react/lib/components/NotifiSmartLink.tsx
packages/notifi-react/lib/components/SmartLinkAction.tsx
packages/notifi-react/lib/context/NotifiSmartLinkContext.tsx

- Add smartLink inactive rendering logic 
- bug fix & refactor

MVP-6348: Add SmartLink inactive rendering logic

---

packages/notifi-react-example-v2/src/app/globals.css
packages/notifi-react-example-v2/src/app/link/layout.tsx
packages/notifi-react-example-v2/src/components/NotifiSmartLinkExample.tsx
packages/notifi-react/lib/components/ActionInputCheckBox.tsx
packages/notifi-react/lib/components/ActionInputTextBoxNumber.tsx
packages/notifi-react/lib/components/ActionInputTextBoxString.tsx
packages/notifi-react/lib/components/NotifiSmartLink.tsx
packages/notifi-react/lib/components/SmartLinkAction.tsx
packages/notifi-react/lib/context/NotifiSmartLinkContext.tsx
packages/notifi-react/lib/style/smartlink.css
packages/notifi-react/lib/style/theme-dark.css
packages/notifi-react/lib/style/theme-light.css

As title
https://github.com/user-attachments/assets/61b96ecd-f592-4e5d-91be-9ba567bbb6cc

MVP-6348-2: Polish SmartLink component styles / Address the UAT#1 feedbacks 

---

packages/notifi-react-example-v2/src/components/NotifiSmartLinkExample.tsx
packages/notifi-react/lib/components/SmartLinkAction.tsx
packages/notifi-react/lib/style/smartlink.css

MVP-6355-patch2: Support loading state for action buttons 

---

packages/notifi-react/lib/components/ActionInputCheckBox.tsx
packages/notifi-react/lib/components/ActionInputTextBoxNumber.tsx
packages/notifi-react/lib/components/ActionInputTextBoxString.tsx

- Optimize ActionInput components ( adhere SSOT of ActionUserInputs)
- address UAT feedbacks (number constraint)

MVP-6355-patch3: Refactor & Address UAT feedbacks

---

packages/notifi-react-example-v2/src/components/NotifiSmartLinkExample.tsx
packages/notifi-react/lib/components/SmartLinkAction.tsx
packages/notifi-react/lib/style/smartlink.css

- Make `hidden` class name more specific to avoid conflict with post css class name
- Optimize example

MVP-6355-patch5: chore - chore

---

.eslintrc.json
packages/notifi-frontend-client/__test__/NotifiSmartLinkClient.test.ts
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/NotifiSmartLinkClient.ts
packages/notifi-frontend-client/package.json
packages/notifi-react-example-v2/.env.local.example
packages/notifi-react-example-v2/src/app/link/layout.tsx
packages/notifi-react/lib/components/ActionInputTextBoxString.tsx

- address UAT - constraint prompt font weight
- SmartLink jest unit test
- Use production smartLink & Parser
- tenant: `otifi.network.unitest`
- smartLink ID: `1e74002c84f3445480c54424a145a62a`

MVP-6355: smartlink unit test

---

packages/notifi-react-example-v2/cypress.config.ts
packages/notifi-react-example-v2/cypress/component/NotifiSmartLink.cy.tsx
packages/notifi-react-example-v2/cypress/support/commands.tsx
packages/notifi-react-example-v2/package.json

Pre-MVP-6356: Config SmartLink Cypress env & spec with Github action workflow pipeline

---

packages/notifi-react-example-v2/cypress.config.ts
packages/notifi-react-example-v2/cypress/component/NotifiSmartLink.cy.tsx
packages/notifi-react-example-v2/cypress/support/commands.tsx
packages/notifi-react-example-v2/src/app/link/[slug]/page.tsx
packages/notifi-react-example-v2/src/components/NotifiSmartLinkExample.tsx

MVP-6356: SmartLink Component type & CICD pipline 

---

package-lock.json

chore: Add missing lock file from previous commit

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-react/lib/components/TopicStackRow.tsx

MVP-6369: Fix conflict & Rebase & Minor fix

---

packages/notifi-frontend-client/__test__/NotifiFrontendClient.test.ts
packages/notifi-react-example-v2/cypress.config.ts

MVP-6370: Update unit test & cy test card id info

---

packages/notifi-graphql/lib/gql/fragments/AlertFragment.gql.ts
packages/notifi-graphql/lib/gql/mutations/createFusionAlerts.gql.ts

MVP-6379: expose subscriptionValue & fusionEventId from getAlerts API

---

packages/notifi-react-example-v2/src/components/NotifiSmartLinkExample.tsx
packages/notifi-react/lib/utils/topic.ts

MVP-6382: Optimize userInputParams comparison mechanism

---

packages/notifi-frontend-client/lib/models/FusionEvent.ts
packages/notifi-react-example-v2/src/components/NotifiSmartLinkExample.tsx
packages/notifi-react/lib/utils/topic.ts

Topic Group Enhancement STAGE --> MAIN

---

packages/notifi-dataplane/lib/NotifiDataplaneClient.ts
packages/notifi-react-example-v2/cypress/component/NotifiSmartLink.cy.tsx

MVP-6346: Update SmartLink dataplane api url lowercases

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/models/Blockchain.ts

Add Botanix Blockchain

---

packages/notifi-react-example-v2/cypress/component/NotifiCardModal.cy.tsx

MVP-6445: Update Cypress component tests

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-react/lib/context/NotifiFrontendClientContext.tsx
packages/notifi-react/lib/utils/frontendClient.ts
packages/notifi-react/lib/utils/index.ts

MVP-6447: Move Solana hardware login logic into `logIn` method

---

packages/notifi-frontend-client/__test__/AuthManager.test.ts
packages/notifi-frontend-client/__test__/NotifiFrontendClient.test.ts
packages/notifi-frontend-client/__test__/NotifiSmartLinkClient.test.ts
packages/notifi-frontend-client/__test__/constants.ts
packages/notifi-frontend-client/lib/client/auth/AptosAuthStrategy.ts
packages/notifi-frontend-client/lib/client/auth/AuthManager.ts
packages/notifi-frontend-client/lib/client/auth/CosmosAuthStrategy.ts
packages/notifi-frontend-client/lib/client/auth/EvmAuthStrategy.ts
packages/notifi-frontend-client/lib/client/auth/SolanaAuthStrategy.ts
packages/notifi-frontend-client/lib/client/auth/index.ts
packages/notifi-frontend-client/package.json

MVP-6453: Strategy Auth Jest Scaffold and implement EVM test case

---

package-lock.json
packages/notifi-frontend-client/__test__/AuthManager.test.ts
packages/notifi-frontend-client/package.json

MVP-6507: APTOS AuthManager test case 

---

package-lock.json
packages/notifi-frontend-client/__test__/AuthManager.test.ts
packages/notifi-frontend-client/package.json

MVP-6509: SUI Unit test (For legacy auth)

---

README.md
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/auth/AptosAuthStrategy.ts
packages/notifi-frontend-client/lib/client/auth/AuthManager.ts
packages/notifi-frontend-client/lib/client/auth/CosmosAuthStrategy.ts
packages/notifi-frontend-client/lib/client/auth/EvmAuthStrategy.ts
packages/notifi-frontend-client/lib/client/auth/SolanaAuthStrategy.ts
packages/notifi-frontend-client/lib/client/auth/SuiAuthStrategy.ts
packages/notifi-frontend-client/lib/client/auth/index.ts

MVP-6510: Final refactor &  Documentation

---

README.md
package-lock.json
packages/notifi-frontend-client/__test__/AuthManager.test.ts
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/auth/AptosAuthStrategy.ts
packages/notifi-frontend-client/lib/client/auth/AuthManager.ts
packages/notifi-frontend-client/lib/client/auth/CosmosAuthStrategy.ts
packages/notifi-frontend-client/lib/client/auth/EvmAuthStrategy.ts
packages/notifi-frontend-client/lib/client/auth/SolanaAuthStrategy.ts
packages/notifi-frontend-client/lib/client/auth/SuiAuthStrategy.ts
packages/notifi-frontend-client/lib/client/auth/index.ts
packages/notifi-frontend-client/lib/models/Blockchain.ts
packages/notifi-frontend-client/package.json

Auth V2 M2 STAGE --> MAIN 

---

package-lock.json
package.json
packages/notifi-frontend-client/__test__/AuthManager.test.ts
packages/notifi-frontend-client/package.json
packages/notifi-react-example-v2/package.json
packages/notifi-react/package.json
packages/notifi-solana-hw-login/package.json

MVP-6527: Fixing deprecation &  Replace light-server with http-server to fix vulnerability

---

packages/notifi-frontend-client/__test__/NotifiFrontendClient.test.ts

MVP-6537: fix hitting rate limit issue in NotifiFrontendClient.test.ts

---

packages/notifi-dapp-example/src/app/notifi/layout.tsx
packages/notifi-dapp-example/src/components/Disconnect.tsx
packages/notifi-react/lib/components/NotifiCardModal.tsx

As title.
> ⚠️ KNOWN ISSUE: CICD failure occurring now duo to Smart Link DP endpoint server error. (BE is working on it)

MVP-6544: Support logout (clean jwt) while disconnecting wallet in notifi-dapp-example

---

packages/notifi-dapp-example/src/app/notifi/ftu/page.tsx
packages/notifi-dapp-example/src/components/FtuTargetList.tsx
packages/notifi-dapp-example/src/components/TargetList.tsx
packages/notifi-dapp-example/src/components/TopicList.tsx
packages/notifi-dapp-example/src/components/TopicOptions.tsx
packages/notifi-dapp-example/src/components/TopicRow.tsx
packages/notifi-dapp-example/src/components/TopicStackRowInput.tsx
packages/notifi-dapp-example/src/hooks/useUserInputParmToFilterOption.tsx

MVP-6546: support Tenant configV2 for notifi-dapp-example

---

packages/notifi-dapp-example/src/app/notifi/dashboard/layout.tsx
packages/notifi-dapp-example/src/context/NotifiContextWrapper.tsx
packages/notifi-dapp-example/src/hooks/useNotifiRouter.ts
packages/notifi-wallet-provider/lib/hooks/useInjectedWallet.ts

MVP-6548: Enhance wallet account switching (dapp-example)

---

package-lock.json

Update pakcage.json auto generated from MVP-6557 change.

MVP-6557-patch: Update package.json

---

packages/notifi-react/lib/context/NotifiHistoryContext.tsx

MVP-6560: History Filtering Logic Enhancement

---

packages/notifi-dapp-example/src/hooks/useTargetListItem.tsx
packages/notifi-react/lib/hooks/useTargetListItem.tsx

MVP-6567: Resolve unhandled error cases 

---

packages/notifi-dapp-example/src/components/LoadingSpinner.tsx
packages/notifi-dapp-example/src/components/TopicList.tsx
packages/notifi-dapp-example/src/components/TopicOptions.tsx
packages/notifi-dapp-example/src/components/TopicStack.tsx
packages/notifi-frontend-client/lib/models/FusionEvent.ts
packages/notifi-frontend-client/lib/models/TenantConfig.ts
packages/notifi-node/__test__/NotifiNodeClient.test.ts
packages/notifi-react-example-v2/src/components/OidcGoogle.tsx
packages/notifi-react-example-v2/src/context/NotifiContextWrapper.tsx
packages/notifi-react-example-v2/src/hooks/useSignTransaction.tsx
packages/notifi-react/lib/components/Connect.tsx
packages/notifi-react/lib/components/TopicStack.tsx
packages/notifi-react/lib/context/NotifiHistoryContext.tsx
packages/notifi-react/lib/context/NotifiSmartLinkContext.tsx
packages/notifi-react/lib/context/NotifiTopicContext.tsx

- MVP-6568 :Update or remove outdated todos 
- MVP-6569 :Structural update - Optimize utility type location: `HistoryFusionEventVariables` in `frontend-client`

MVP-6568+6569: Update or remove outdated todos/   Optimize utility type location

---

package-lock.json
package.json
packages/notifi-dapp-example/next.config.mjs
packages/notifi-dapp-example/src/app/notifi/ftu/page.tsx
packages/notifi-dapp-example/tailwind.config.ts
packages/notifi-react-example-v2/next.config.mjs

- update next.config.mjs and related parts
- Update browser-list db for next.js
- fix dapp-example tailwind config conflict - content & purge

MVP-6570: Update next.config.mjs and related parts for dapp-example 

---

packages/notifi-node/README.md

Update NotifiNodeClient instantiation section

MVP-6576: chore - Update notifi-node README.md
