package-lock.json
packages/notifi-node-sample/lib/index.ts
packages/notifi-node-sample/package.json
packages/notifi-node/lib/client/NotifiClient.spec.ts
packages/notifi-node/lib/client/NotifiClient.ts
packages/notifi-node/lib/client/index.ts
packages/notifi-node/lib/mutations/deleteUserAlertImpl.ts
packages/notifi-node/lib/mutations/index.ts
packages/notifi-node/lib/mutations/sendMessageImpl.ts

This mutation allows the service user to, on behalf of a user, delete an
alert which is owned by a user on the tenant.
This enables the use case for Mango to minimize integration footprint.
I've updated the sample
- Add new example for deleteUserAlert
- dedupe some logic via refactor to middleware

Add DeleteUserAlert to node sdk

---

packages/notifi-react-hooks/lib/utils/ensureTarget.spec.ts
packages/notifi-react-hooks/lib/utils/ensureTarget.ts

For emails specifically, we should be case-insensitive to the input.
When sending values to the server, also lower case the emails.

Lower case emails in ensureTarget

---

package-lock.json
packages/notifi-core/lib/NotifiClient.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

When deleting an Alert, we previously had always cleaned up the attached SourceGroup / TargetGroup. Allow the client to control this behavior by exposing some parameters to deleteAlert.
Also, remove parallel calls in the SDK. I think there are some undefined behaviors since both of the parallel calls are modifying the same object. In the future, refactor those calls to be without side-effect.

Add params to keep Source/TargetGroup

---

package-lock.json
packages/notifi-react-hooks/lib/hooks/useNotifiJwt.ts
packages/notifi-react-hooks/package.json

Using localStorage has some limitations. Namely:
- storage limits can become contentious
- we must serialize / deserialize ourselves since only strings are supported
Move to [localForage](https://github.com/localForage/localForage) as a storage driver, which:
- exposes a localStorage-like API (but async)
- wraps IndexedDB or LocalStorage underneath, based on browser support

Move JWT storage to localforage

---

packages/notifi-axios-adapter/lib/fragments/index.ts
packages/notifi-axios-adapter/lib/fragments/supportedTargetTypesFragment.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

For some reason we were returning the in-memory (non-altered) copy.

Return updated alert from SDK

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/operations/CreateSource.ts
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/lib/utils/AlertConfiguration.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Some Alert configurations need to create Sources before they can subscribe
Add a `createSource` configuration for this.
This will be a minor release, as it is non-breaking new functionality

Add Create Source

---

packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

When the source is created, we should add its applicableFilters to the data filters
When we create a source for the Alert, we may need to re-use it for other alerts, so we shouldn't filter on the name when matching to an existing one.

Minor bugfixes for createSource flow

---

packages/notifi-react-card/README.md
packages/notifi-react-card/lib/utils/AlertConfiguration.ts

This is a utility method to subscribe to "Broadcast" sources on the
provided "topicName".
For now, integrators should speak with Notifi to receive a topic name to
use.

Add Broadcast Message configuration

---

package-lock.json
packages/notifi-core/lib/NotifiClient.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

In order to improve flexibility as well as enable rendering of existing
targets, expose these targets on the Notifi Client.

Expose targets on NotifiClient

---

packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/package.json
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Hyperspace was saying our bundle is too big
I agree, and it should really be an optional plugin
Until we can fix the ESM (from tsc) so that we can get nice tree shaking, let's remove it for now and default to USA
Clients can still implement stronger validation by passing the full string, including `+CountryCode`

Remove libPhonenumber-JS

---

.vscode/settings.json
packages/notifi-axios-utils/lib/utils/axiosRequest.ts
packages/notifi-core/lib/NotifiClient.ts
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Changes:
* Add `ensureTargetGroup` to `NotifiClient`
* When `subscribe` is called use `ensureTargetGroup` to update targets when all alerts are disabled
* Append `resultKey` to GQL path to improve dev experience when troubleshooting network requests

MVP-813: Allow users to edit targets when all alerts are disabled

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Allow clients to describe additional variables through the broadcast
method
before:
```
broadcastMessage({
topic,
subject: 'Hello World',
message: 'This is my body',
isHolderOnly: false,
});
```
after:
```
broadcastMessage({
topic,
subject: 'Hello World',
message: 'This is my body',
isHolderOnly: false,
variables: {
foo: 'bar',
baz: 'bat',
},
});
```

Add extra variables to broadcast

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Right now, it's not possible to re-use the same target group across
multiple alerts that use the client. Allow the input to specify the
target group name (optionally, falling back to name) to override the
target behavior.

Allow users to specify target group name

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-react-hooks/lib/utils/packFilterOptions.ts

This key allows us to configure with either an `and` or `or` to evaluate
some values. Each item has a `key` `op` and `value`.
example:
```
const filterOptions = {
values: {
and: [
{ key: "foo", op: "eq", value: "A" },
{ key: "price", op: "gt", value: "0" },
{ key: "price", op: "lte", value: "1" },
],
}
}
```

Add `values` key to filterOptions

---

packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

When calling ensureTargetGroup, it doesn't update the data properly.
Call setInternalData in order to return the result to subscribers of
`client.data`

Render the new data from ensureTargetGroup

---

package-lock.json
packages/notifi-node-sample/lib/index.ts
packages/notifi-node/lib/client/NotifiClient.ts
packages/notifi-node/lib/mutations/broadcastMessageImpl.ts

Now that TenantUsers are able to send broadcast messages, expose the functionality through the Node SDK.

Support broadcastMessage from Node SDK

---

packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription card views/EditCardView.tsx
packages/notifi-react-card/lib/components/subscription/subscription card views/HistoryCardView.tsx
packages/notifi-react-card/lib/hooks/useFetchedCardState.ts

the current card will need different presentational views after the data has fetched. my plan of attack is to start with the edit view and based off the presence of target group data from the useNotifiSubscriptionContext, update the state on first load

creates a new card to split up state

---

packages/notifi-graphql/lib/gql/fragments/NotificationHistoryEntryFragment.gql.ts

We need read history for Pontem notification alert history.
This adds the read value to Notification History fragment in GraphQL and as a result will update the node value from `getNotificationHistory` function in the frontend client.

Add Read Value to Notification History Fragment

---

packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCard.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCardContainer.tsx
packages/notifi-react-card/lib/context/NotifiContext.tsx

as subscription card and intercom card have it's own target group, instead of using `NotifiSubscriptionContextProvider` on the entire React Card, we need to wrap this provider on subscription card and intercom card individually. 
this PR has the context refactor on the subscription card and will have the `NotifiSubscriptionContextProvider` added for intercom card in another PR(intercom FTU)
Test:

[MVP-1570] refactor react card context

---

packages/notifi-axios-adapter/lib/fragments/convMessagePageInfoFragment.ts
packages/notifi-axios-adapter/lib/fragments/conversationMessagePageInfoFragment.ts
packages/notifi-axios-adapter/lib/queries/getConversationMessagesImpl.ts
packages/notifi-react-card/lib/components/intercom/ChatMessageDate.tsx
packages/notifi-react-card/lib/components/intercom/ChatMessageSection.tsx
packages/notifi-react-card/lib/components/intercom/ChatWindowIntroSection.tsx
packages/notifi-react-card/lib/components/intercom/MessageGroup.tsx
packages/notifi-react-card/lib/components/intercom/MessageList.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomChatWindowContainer.tsx
packages/notifi-react-card/lib/components/subscription/defaults.css
packages/notifi-react-card/lib/hooks/useIntercomChat.ts
packages/notifi-react-card/lib/utils/datetimeUtils.ts

hard coding(used existing conversation id to get one conversation thread) a conversation messages
updated logics in useIntercomChat to get the correct data structure to render messages
implement pagination
hide sender name and sender avatar component until we have the correct field exposed in the future.
need to ask Sam with a design of loading message state but using wording "Loading..." for now as the state.
will implement polling or apollo subscriptions in another PR.
Test:
Story:
https://notifi.atlassian.net/browse/MVP-1599

[MVP-1599] - [2/2] render of Intercom conversation messages - without polling

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/operations/CreateSource.ts
packages/notifi-react-card/lib/components/NotifiEmailInput.tsx
packages/notifi-react-card/lib/components/NotifiTelegramInput.tsx
packages/notifi-react-card/lib/components/intercom/IntercomCard.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomCard.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomFTUNotificationTargetSection.tsx
packages/notifi-react-card/lib/components/intercom/NotifiStartChatButton.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCardContainer.tsx
packages/notifi-react-card/lib/components/subscription/defaults.css
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/lib/utils/AlertConfiguration.ts

Enable subscribe to chat alerts when user inputs their information
Test:
initial subscribe(when user use intercom chat for the first time):
if the user has subscribed the chat alert and come back to use intercom:
show error message when subscribe is failed:
Story:
https://notifi.atlassian.net/browse/MVP-1583

[MVP-1583] Enable subscribe to chat alerts 

---

packages/notifi-react-card/lib/components/NotifiEmailInput.tsx
packages/notifi-react-card/lib/components/NotifiTelegramInput.tsx
packages/notifi-react-card/lib/components/intercom/IntercomCard.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomFTUNotificationTargetSection.tsx
packages/notifi-react-card/lib/components/intercom/NotifiStartChatButton.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/useIntercomCardState.ts
packages/notifi-react-card/lib/hooks/useIntercomChat.ts
packages/notifi-react-card/lib/utils/datetimeUtils.ts

implement polling for intercom chat
update intercom chat flow, when users come back to use intercom, bring them directly to the chat view instead of to the start chat view.
Test:
Story:
https://notifi.atlassian.net/browse/MVP-1649

[MVP-1649] implement polling for intercom chat

---

packages/notifi-react-card/lib/components/subscription/defaults.css

update the font family in textarea to match other component
Test:
before:
after:
Story:
https://notifi.atlassian.net/browse/MVP-1635

[MVP-1635] update the font family in textarea to match other component

---

packages/notifi-react-card/lib/components/intercom/ChatWindowHeader.tsx
packages/notifi-react-card/lib/components/intercom/SendMessageSection.tsx

fix chat window header layout
changed className in chat window header component to match in css
add onKeyDown in textarea, user can send message by hitting enter key.
before:
after:

[MVP-1691] fix chat window header layout

---

package-lock.json
packages/notifi-react-example/package.json
packages/notifi-react-example/src/App.css
packages/notifi-react-example/src/App.tsx
packages/notifi-react-example/src/NotifiCard/NotifiCard.css
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx
packages/notifi-react-example/src/SolanaWalletProvider.tsx

Updates the `react-example` to use the react card for development. We had a lengthier method to build and test; hopefully this should ease some pain in developing on the sdk card.

brings react card into react example repo

---

packages/notifi-react-card/README.md

Preview: https://github.com/notifi-network/notifi-sdk-ts/blob/526da541e5d3c3b57f21f9d7a69b278ee67ce068/packages/notifi-react-card/README.md
- Add Acala code snippet
- Add Binance and Arbitrum as EVM chains
- Add toggle dropdown of code snippets for readability (instead of scrolling to see the chain code snippet that most pertains to you)

Add Acala, Binance, and Arbitrum to React Card Docs

---

packages/notifi-react-card/lib/components/intercom/ChatMessageDate.tsx
packages/notifi-react-card/lib/components/subscription/defaults.css

adjust bold dark fonts to match design: intro message and support staff ‘name’ 
Increase width of support staff message bubble
center the date component
Test:
before:
after:
Story:
https://notifi.atlassian.net/browse/MVP-1697

[MVP-1697] chat window css polish

---

packages/notifi-react-card/lib/components/intercom/ChatMessageSection.tsx
packages/notifi-react-card/lib/components/intercom/IntercomCard.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomCard.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomCardContainer.tsx
packages/notifi-react-card/lib/components/subscription/defaults.css
packages/notifi-react-example/src/NotifiCard.tsx

update:
use same style of container for all three views
instead of removing the sms section in intercom card, we decided to to keep the code for flexibility and prevent tenant to turn on the sms toggle in config tool. But still need to fix the layout on settingView.
update create alert error message ‘Error to subscribe, please try again’ to ‘An error occurred, please try again.’
Test:
update:
Story:
https://notifi.atlassian.net/browse/MVP-1694

[MVP-1964] fix setting view layout

---

package-lock.json
packages/notifi-react-card/lib/components/index.ts
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionContextWrapper.tsx
packages/notifi-react-card/lib/components/subscription/index.ts
packages/notifi-react-card/lib/components/subscription/subscription-card-views/index.ts
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/index.ts
packages/notifi-react-card/lib/context/index.ts

to approach creating a more globalized context where users can use hooks throughout the application, we'd need to open up the context to more than just a card. this will allow the user to create a separate context that use react card components without having to use the notifi react card

creates a context wrapper

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/operations/LogInFromDapp.ts
packages/notifi-react-card/lib/context/NotifiContext.tsx
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Please note: There seems to an existing bug with alert history showing first even before a user signs in. 
To-Do:
- We should update the signature message to be consistent with the other chains, will request BE.
Test:
https://user-images.githubusercontent.com/108922885/206565130-aa3d7464-09b3-48bc-9350-7d327b7d79db.mov
Please note:
- NEAR users do not need to manually "sign" a message in their wallet. Once the user connects their wallet, they have authorized the dapp to sign for them. 
I used `jt/near-login` to test in the `notifi-react-example`.
Next: Add documentation

Add NEAR Login

---

packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx

For some reason the card was always going to the alert history view.

Set state to 'edit' if data is missing

---

packages/notifi-react-card/lib/components/defaults.css

we have position absolute on a child and the parent didn't have any position prop so it was using the viewport width the edit button color also didn't have enough contrast so i updated it to match the subscribe button
- updated settings icons colors through through property 
- added a max height to alert details container, it was spilling over without it.
Before:
After:
Header:
Before:
Settings Icons Colors:
max-height before:
max-height after:

small updates for positioninig and button colors

---

packages/notifi-react-card/README.md

- Correct setState function and variables names
- Pass in the correct signMessage function
- Add comment on assumption to have `NEARWalletContextProvider` set up
TO-DO: Set up an example repo to showcase NEAR

Fix: Typos in NEAR Docs

---

packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/EventTypeHealthCheckRow.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/AlertListPreview.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/AlertsPanel.tsx
packages/notifi-react-card/lib/hooks/SubscriptionCardConfig.ts
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx

Add Liquidation LTV Alert Selection to SDK React Card
Toggle: If toggle is turned ON, then the notification buttons drop down. The user can select or enter per 
Button 1: XX%
Button 2: YY%
Button 3: Custom entry of a percent ranging from 1%-99%
https://notifi.atlassian.net/jira/software/c/projects/MVP/boards/1?modal=detail&selectedIssue=MVP-1810&sprint=63

[MVP-1810] add liquidation alert selection to SDK react card - UI

---

packages/notifi-react-card/README.md

- Aptos sign-in code in current documentation returns an error because our Aptos sign message function requires a string while the Aptos sign message function itself returns either a `string` or `SignMessageResponse` type. 
- Since our Aptos sign message function is typed to string, if the `result` of `signMessage` is a string, then we return `result`. If not, then we should return the `signature` value of `result.` 
https://user-images.githubusercontent.com/108922885/208219350-225e4dda-0f98-48fc-8efa-09dcafb6667a.mov
Please reference https://github.com/notifi-network/notifi-aptos-example for confirmation.

Fix: Aptos Sign Message in Documentation

---

packages/notifi-core/lib/models/TargetGroup.ts
packages/notifi-react-hooks/lib/utils/ensureSourceGroup.spec.ts
packages/notifi-react-hooks/lib/utils/ensureTargetGroup.spec.ts
packages/notifi-react-hooks/lib/utils/ensureTargetIds.spec.ts
packages/notifi-react-hooks/lib/utils/fetchDataImpl.spec.ts

ensureTargetGroup spec was failing due to webhook targets. updated as i wanted to update inputs in the future discord and twitter
can run test by using:
`npm run test ensureTargetGroup.spec.ts`

updates unit tests for webhooks

---

packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/intercom/IntercomCard.tsx
packages/notifi-react-card/lib/components/intercom/SendMessageSection.tsx

disabled send button when the user input string are all spaces
increase left and right padding in the message bubble
update to get email, telegram and sms for intercom from useNotifiForm
fixed the 'light mode' disabled button color
before:
after:
test:

[MVP-1855] fix intercom issue with padding and empty strings

---

packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

when calling subscribe, login would cause re-renders in the forms due to logging in also calling on the `render` method. as a small change, we can conditionally call login based off isAuthenticated.
in the future, we may not need this due to the card not being available if the user is not isAuthenticated.

updates code to conditionally call logIn

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-react-card/lib/assets/DeleteIcon.tsx
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/intercom/NotifiIntercomFTUNotificationTargetSection.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeBroadcastRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeDirectPushRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeTradingPairsRow.tsx
packages/notifi-react-card/lib/components/subscription/FetchedStateCard.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCard.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/resolveRef.ts
packages/notifi-react-card/lib/components/subscription/subscription-card-views/PreviewCard.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/AlertsPanel.tsx
packages/notifi-react-card/lib/hooks/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/utils/AlertConfiguration.ts

For now, add a tradingPair renderer which subscribes to Direct Tenant Messages.
This is the first instance where we have one "EventItem" that resutls in many Alerts. We need to be able to associate it to the one EventItem, so for now encode the information within alert.name.

Implement tradingPair renderer

---

packages/notifi-react-card/lib/components/NotifiEmailInput.tsx
packages/notifi-react-card/lib/components/NotifiSmsInput.tsx
packages/notifi-react-card/lib/components/NotifiTelegramInput.tsx
packages/notifi-react-card/lib/components/intercom/IntercomCard.tsx
packages/notifi-react-card/lib/context/NotifiFormContext.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx

When a user does not have chat alerts set up,
the form should be prepopulated with the user information if they currently have the SDK setup on their application.
how to test:
create a new wallet
sign up for sdk alerts on react card
refresh on intercom card to see if user info is pre-populated

Prepopulate form

---

packages/notifi-react-card/lib/components/subscription/EventTypeHealthCheckRow.tsx
packages/notifi-react-card/lib/hooks/SubscriptionCardConfig.ts

Currently, we allow tenant to select alert frequency for health check in admin tool
update in SDK subscription card to get alertFrequency for health check from config data

use alertFrequency from config data to create health check alert

---

packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/mutations/deleteWebhookTarget.gql.ts
packages/notifi-graphql/lib/operations/DeleteWebhookTarget.ts
packages/notifi-graphql/lib/operations/index.ts
packages/notifi-node/lib/client/NotifiClient.ts

Key on the `name` parameter to create an alert with a BALANCE filter using the webhook parameters that are passed in. The method tries its best to return (optimistically) the existing entities when appropriate.
Remaining work:
- Update this method not to return Sources from SourceGroup (probably)
- Expose Sources connection
- Expose addSourceToSourceGroup / removeSourceFromSourceGroup

Implement createTenantBalanceChangeAlert

---

packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/mutations/addSourceToSourceGroup.gql.ts
packages/notifi-graphql/lib/gql/mutations/removeSourceFromSourceGroup.gql.ts
packages/notifi-graphql/lib/operations/AddSourceToSourceGroup.ts
packages/notifi-graphql/lib/operations/RemoveSourceFromSourceGroup.ts
packages/notifi-graphql/lib/operations/index.ts
packages/notifi-node-sample/lib/index.ts
packages/notifi-node/lib/client/NotifiClient.ts

This operation will be useful for clients who are managing SourceGroups with a lot of Sources.
Remaining work:
- expose `sources` Connection
- make sure SourceGroups with a lot of sources don't go through the array field on SourceGroup

Expose add/remove Source to/from SourceGroup

---

packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/intercom/IntercomCard.tsx
packages/notifi-react-card/lib/components/intercom/MessageGroup.tsx
packages/notifi-react-card/lib/components/intercom/MessageList.tsx

We are currently have the avatar and sender name for each incoming message
should only show the sender name and avatar for the first incoming message in messages group
also fix the loading... content on loading view to be centered
test:

[MVP-2002] only show avatar and sender name for the first message

---

packages/notifi-react-card/README.md

With the new aptos library, update the README sample to reflect the new types. Main change is that result is nullable and `signature` could be an array.

Update Aptos README

---

packages/notifi-react-example/src/App.tsx
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx
packages/notifi-react-example/src/Potem.css

[MVP-2121](https://notifi.atlassian.net/browse/MVP-2121)
- Add custom styling potem to Notifi example
[MVP-2121]: https://notifi.atlassian.net/browse/MVP-2121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

MVP 2121 add custom styling potem to notifi example

---

packages/notifi-react-card/lib/components/subscription/subscription-card-views/AlertListPreview.tsx

Labels would show up in the preview panel because they're technically an 'event type' from the config tool.

updates alert labels from showing up in the preview view

---

packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx

https://notifi.atlassian.net/jira/software/c/projects/MVP/boards/1?modal=detail&selectedIssue=MVP-2186&assignee=70121%3Aa07d66f3-c306-4b82-ae4a-d5b0022e56dc
After clicking “Edit” under “Manage Alerts” to change the contact details, the back button in the edit form takes the user to the alert history view instead of the “Manage Alerts” view.

updates back-navigation

---

packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/NotifiToggle.tsx

Previously we tried using css to update the Input but it's actually not visible,
instead we should add another class to the span when it's disabled that can be targeted.

updates react card css to add progress spinner

---

packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/UserInfoPanel.tsx

https://user-images.githubusercontent.com/105258726/222253937-d3955319-795b-4d58-957c-c8b460fd4404.mov
Users wouldn't have "felt" that they sent an email confirmation.
This was previously built in another implementation.

Email confirmation link update

---

package-lock.json
package.json
packages/notifi-react-card/README.md
packages/notifi-react-card/lib/components/NotifiHwWalletToggle.tsx
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/subscription-card-views/InputFields.tsx
packages/notifi-react-card/lib/context/NotifiContext.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/lib/index.ts
packages/notifi-react-card/lib/plugins/HardwareLoginPlugin.ts
packages/notifi-react-card/lib/plugins/index.ts
packages/notifi-react-card/package.json
packages/notifi-react-example/package.json
packages/notifi-react-example/src/MultiWalletTest/MultiWalletTest.tsx
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx
packages/notifi-solana-hw-login/README.md
packages/notifi-solana-hw-login/lib/index.ts
packages/notifi-solana-hw-login/lib/plugin/MemoProgramHardwareLoginPlugin.ts
packages/notifi-solana-hw-login/lib/plugin/index.ts
packages/notifi-solana-hw-login/package-lock.json
packages/notifi-solana-hw-login/package.json
packages/notifi-solana-hw-login/tsconfig.build.json
packages/notifi-solana-hw-login/tsconfig.json

I've been running into some trouble with the @solana/web3.js peer
dependency when working on non-Solana integrations. Completely pull out
the dependency to a separate package and implement it as a plugin so
that only people who use Solana will have to pull them in.

Remove solana dependency from react-card 

---

packages/notifi-react-card/lib/components/common/ErrorStateCard.tsx
packages/notifi-react-card/lib/components/common/LoadingStateCard.tsx
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/FetchedStateCard.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCard.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCardContainer.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/AlertListPreview.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/EditCardView.tsx
packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx

We already had some fields which were configurable thru the frontend integration. Make some additional fields configurable (and fix some discovered bugs).
For now, we are just passing it through from the top level, but in the future we should consider pulling these values in from the fetched CardConfig.

Make copy configurable from top level

---

packages/notifi-core/lib/operations/CreateSource.ts
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/EventTypePriceChangeRow.tsx
packages/notifi-react-card/lib/components/subscription/index.ts
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/AlertsPanel.tsx
packages/notifi-react-card/lib/hooks/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/utils/AlertConfiguration.ts

This row was implemented in the Vue integration of Pontem (and thus, in the notifi-frontend-client), but was never ported to the React SDK. Add support for this new row.

Port PriceChange row

---

packages/notifi-react-card/lib/components/WalletList/ConnectWalletRow.tsx
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

We have an error handling flow for ConnectWallet where the user is prompted when the wallet they are trying to connect is already associated with another Notifi account.
Implement this as an in-line error message and secondary action link.
The copy is taken from the Notifi Hub copy
|verify|connected elsewhere|verified|
|---|---|---|
|<img width="404" alt="Screen Shot 2023-03-12 at 2 01 23 PM" src="https://user-images.githubusercontent.com/100658137/224573620-a3a192e9-7742-42db-930b-59fc19e1e36f.png">|<img width="403" alt="Screen Shot 2023-03-12 at 2 02 50 PM" src="https://user-images.githubusercontent.com/100658137/224573636-22fa798f-1591-4407-aaee-6ffd7383aa3c.png">|<img width="405" alt="Screen Shot 2023-03-12 at 2 00 52 PM" src="https://user-images.githubusercontent.com/100658137/2245736 …

Add support for disconnecting ConnectedWallet

---

packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/EditCardView.tsx
packages/notifi-react-card/lib/utils/AlertConfiguration.ts

The new types were missing from AlertConfiguration.createConfigurations -- we should figure out a good way to dedupe this logic from the EventTypeRows

Fix alert creation on signup

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-react-card/lib/components/WalletList/ConnectWalletRow.tsx
packages/notifi-react-example/src/MultiWalletTest/MultiWalletTest.tsx

Allow the consumer to specify an optional displayName for each ownedWallet

Add support for displayName on ownedWallets

---

packages/notifi-react-card/lib/components/NotifiSmsInput.tsx

When the focus is lost from the country code dropdown, hide it.
Capture the focus on the immediate parent of the options so that we can actually click on the options.

Hide country codes onBlur

---

packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx

https://user-images.githubusercontent.com/105258726/225474544-774cfdac-9aea-459d-89c8-6a9e890b9071.mov
added a resetFormState method when back is pressed from the subscription card.
thought about adding it to form context but i think i want to keep formContext clean and not necessarily dependent on the subscriptionContext JIC someone wants to use them separately... maybe it should go in there.

adds reset method

---

packages/notifi-react-card/lib/components/WalletList/ConnectWalletRow.tsx
packages/notifi-react-card/lib/components/WalletList/WalletList.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/VerifyWalletView.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

In the multi-wallet flow, we cannot actually subscribe until after the verifyonboarding step, as the user may connect additional wallets during this step.
Split up the two functions and make a network call on the Confirm button inside verify view

Split subscription in multi-wallet flow

---

packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

There are various places where we want to copy the authorization to various keys. For every connected wallet, we should copy the authorization token to the storage of that wallet

Copy Authorization when using multi-wallet

---

packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx

Add a new hook, useNotificationHistory, for the following 3 purposes:
1. Filter out the unsupported detailEntryType so that unsupported Entry will not be shown on historyCard. 
> *[Recommended approach](https://virtuoso.dev/troubleshooting/) from Virtuoso:*
> ```
> If you have zero-height items, you need to filter those out before passing them to the component. 
> The internal data structure needs a distinct position for each item. There's no way to fix this.
> ```
2. Add the fallback renderer (But this should never happen):
3. Consolidate all the custom EventDetailRenderer components: we can get the associated props to pass into AlertNotificationRow by using this hook.

Add fallback renderer/ Filter out unsupported notification (MVP-2289)

---

packages/notifi-react-card/lib/components/defaults.css

If title or description is long, let it take up to two rows. See the following example of Direct Push notification alert.

Make Alert history title / description take up two rows (MVP-2286)

---

packages/notifi-react-card/lib/context/NotifiDemoPreviewContext.tsx
packages/notifi-react-card/lib/context/NotifiFormContext.tsx

Linting error when building
```
lerna ERR! npm run build stderr:
lib/components/intercom/NotifiIntercomCard.tsx(46,8): error TS2559: Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'.
```

Fix linting issues caused by lack of PropsWithChildren

---

packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/hooks/useSubscriptionCard.ts

This patch makes the dummy preview card re-render when the demoPreview args passed in is changed. 
See below demonstration.
https://user-images.githubusercontent.com/127958634/230322096-e49c4c2e-d396-429a-929b-6260b0265ca9.mov

eric/MVP-2257-patch: Auto re-render dummy preview when config data is changed

---

package-lock.json
packages/notifi-react-card/lib/components/subscription/EventTypeBroadcastRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeDirectPushRow.tsx
packages/notifi-react-card/lib/context/NotifiFormContext.tsx

We want to use the same card in multiple pages on the dApp, parameterized by some value, to provide notifications.
When we use the same alert name, the configurations will step on each other, resulting in one page's settings overriding another page's.
If the ID is an input value, parameterize the alert name in order to avoid this situation

Add a name when the id is parameterized

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts

The backend verification for these chains uses hex instead of b64.

Use hex rather than b64

---

packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/EditCardView.tsx
packages/notifi-react-card/lib/context/NotifiDemoPreviewContext.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

There was no loading indicator to the user when submitting the card.
also, because we had `logIn` setting loading to false, it'd prematurely flicker back to the card.
https://user-images.githubusercontent.com/105258726/232606571-edf84b91-2041-4f7e-a680-974efd4c39ec.mov

adds loading state card for edit card

---

packages/notifi-react-example/src/NotifiCard/DemoPreviewCard.tsx

This sample is no longer valid, since 'error' is not a valid value for DemoPreviewContextProvider `view`

Remove the error sample

---

packages/notifi-react-card/package.json

We are already generating .mjs files, we should allow customers to use them so we can better support tree-shaking (e.g. date-fns)

Set module on react-card

---

packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/fragments/ConnectedWalletFragment.gql.ts
packages/notifi-graphql/lib/gql/mutations/connectWallet.gql.ts
packages/notifi-graphql/lib/operations/ConnectWallet.ts
packages/notifi-graphql/lib/operations/index.ts

`connectWallet` services method is missing inside the `notifi-graphql`. 
Add it back it

MVP-2496:  Add `connectWallet` service method back in `notifi-graphql`

---

packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/queries/getConnectedWallets.gql.ts
packages/notifi-graphql/lib/operations/GetConnectedWallets.ts
packages/notifi-graphql/lib/operations/index.ts

Add `getConnectedWallets` service back in notifi-graphql

MVP-2511: Add GetConnectedWalletsService back in notifi-graphql

---

packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/fragments/ConvMessagePageInfoFragment.gql.ts
packages/notifi-graphql/lib/gql/fragments/ConversationMessageFragment.gql.ts
packages/notifi-graphql/lib/gql/fragments/ParticipantFragment.gql.ts
packages/notifi-graphql/lib/gql/mutations/createSupportConversation.gql.ts
packages/notifi-graphql/lib/gql/mutations/sendConversationMessages.gql.ts
packages/notifi-graphql/lib/gql/queries/getConversationMessages.gql.ts
packages/notifi-graphql/lib/operations/CreateSupportConversation.ts
packages/notifi-graphql/lib/operations/GetConversationMessages.ts
packages/notifi-graphql/lib/operations/SendConversationMessages.ts
packages/notifi-graphql/lib/operations/index.ts

As title, add back the following 3 services so that FrontendClient can consume the service method.
1. getConversationMessage
2. sendConversationMessages
3. createSupportConversation

MVP-2514: Add intercom related services back in notifi-graphql

---

packages/notifi-react-example/src/walletProviders/SolanaWalletProvider.tsx

phantom was added directly to the wallet standard kit.
wanted to remove. here's the warning:
act_devtools_backend.js:2655 Phantom was registered as a Standard Wallet. The Wallet Adapter for Phantom can be removed from your app.

no longer need to include phantom

---

packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-frontend-client/lib/utils/resolveRef.ts

Implement missing TradingPairEventTypeItem type and its related helper functions that will be consumed by notifi-react-card

MVP-2527: Add TradingPairEventTypeItem type in notifi-frontend-client

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-react-example/src/FrontendClient/FrontendClient.tsx

1. Implement fetchData to NotifiFrontendClient (This will be replacing the fetching data method in `useNotifiClient` in notifi-react-hooks)
2. Showcase `fetchData` method and `useState` getter in react-example. See the demo video below:
https://user-images.githubusercontent.com/127958634/234154114-63797871-69fc-401c-a88c-a53ffcb0a15c.mov

MVP-2513: Implement fetchData method in NotifiFrontendClient

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts

Migrate the three intercom related methods consumed by notifi-react-card in `useNotifiClient` (notifi-react-hooks). 
- getConversationMessages
- sendConversationMessages
- createSupportConversation

MVP-2523: Implement Itercom related methods consumed by notifi-react-card

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts
packages/notifi-react-example/src/App.tsx
packages/notifi-react-example/src/FrontendClient/KeplrFrontendClient.tsx
packages/notifi-react-example/src/FrontendClient/PolkadotFrontendClient.tsx
packages/notifi-react-example/src/FrontendClient/SolanaFrontendClient.tsx
packages/notifi-react-example/src/FrontendClient/SuiFrontendClient.tsx
packages/notifi-react-example/src/FrontendClient/WalletConnectFrontendClient.tsx
packages/notifi-react-example/src/FrontendClient/index.tsx

- DRY NotifiFrontendConfiguration --> replace the blockchain specific config generator with a common `newFrontendConfig` generator
- DRY clientFactory --> replace the blockchain specific client factory with a common `newFrontendClient` factory.
- DRY NotifiFrontendClient --> extract common throw error logic
Add multi-chain options in notifi-react-example's FrontendClient section.
See the video demo below:
https://user-images.githubusercontent.com/127958634/235072470-8fb0359a-4d54-4fde-a5c3-6f76918c5cfa.mp4

MVP-2537 + MVP- 2538: multi-chain option & DRY

---

packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-react-example/src/FrontendClient/KeplrFrontendClient.tsx
packages/notifi-react-example/src/FrontendClient/PolkadotFrontendClient.tsx
packages/notifi-react-example/src/FrontendClient/SolanaFrontendClient.tsx
packages/notifi-react-example/src/FrontendClient/SuiFrontendClient.tsx
packages/notifi-react-example/src/FrontendClient/WalletConnectFrontendClient.tsx

Instead of two-step operation (get config by newFrontendConfig and pass it into newFrontendClient), It might be more intuitive for user to just call "newFrontendClient" to get client object.
So change the newFrontendConfig as an internal call into newFrontendClient.

MVP-2537-patch: Move newFrontendConfig as internal call

---

packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCardContainer.tsx
packages/notifi-react-card/lib/context/NotifiClientContext.tsx
packages/notifi-react-card/lib/context/NotifiContext.tsx

1. Make fronttendClient object accessible in NotifiClientContext: for now both client object will be available until frontendClient can completely replace hooks' client.
2. Replace old `isInitalized` method in `NotifiSubscriptionCardContainer` using frontendClient

MVP-2556: frontendClient object accessible in notifi-react-card

---

packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-frontend-client/lib/utils/resolveRef.ts

Implement missing HealthCheckEventTypeItem type and its related helper functions that will be consumed by notifi-react-card

MVP-2558: HealthCheckEventTypeItem event type and its related methods in FrontendClient

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts

The userState is not updated in the following two initialized case :
- 'logOut'
- 'expired'
Update the userState when .initialize() return 'logOut' or 'expired'

MVP-2556-patch: Fix frontendClient initalize() does not update userstate

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/models/IntercomCardConfig.ts
packages/notifi-frontend-client/lib/models/index.ts
packages/notifi-react-card/lib/components/intercom/IntercomCard.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomFTUNotificationTargetSection.tsx
packages/notifi-react-card/lib/hooks/useIntercomCard.ts

1. Add 'IntercomCardConfig' type into frontendClient package
2.  Migrate the all intercomCardConfig related types to use frontendClient 
3.  Implement optional 'fetchSubscriptionCard' using frontendClient in 'useIntercomCard.

MVP-2575: 'IntercomCardConfigV1' added (notifi-frontend-client)

---

packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx

Subscription adopts frontendClient's logic when enableCanary is true. Otherwise, keeps original flow

MVP-2577: 'frontendClient' object available in SubscriptionCardV1 component (notifi-react-card)

---

packages/notifi-react-card/lib/components/subscription/EventTypeBroadcastRow.tsx
packages/notifi-react-card/lib/utils/frontendClient.ts

Implement alternative 'subscribeAlter' method using frontendClient in EventTypeBroadcastRow component

MVP-2585:  'subscribeAlter' with frontendClient in EventTypeBroadCastRow (notifi-react-card)

---

packages/notifi-react-card/lib/components/subscription/EventTypeBroadcastRow.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx

1. Expose render method from `NotifiSubscriptionContext`
2. render after alter is subscribed / unsubscribed

MVP-2585-patch: re-render data after subscribe/ unsubscribe alter

---

packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-react-card/lib/components/subscription/EventTypeCustomHealthCheckRow.tsx

- Add Fallback val in 'getCustomFilterOptions' allows customFilterOption able to fallback to checkRatios[0] if client does not pass in either `threshold` or `value`
- This also helps when dapp wants to ensure multiple alerts at the same time (alternative method of `subscribe` in `useNotifiSubscribe`
**NOTE**
Blocker of MVP-2610

MVP-2609-patch: 'getCustomFilterOptions' fallback value (frontend-client)

---

packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/components/intercom/IntercomCard.tsx

1. Have `notifi-forntend-client` package support createSupportConversationEventType
2. In `notifi-react-card` add the following two feature to allow switching between frontendClient and client
- subscribeAlert
- createSupportConversation

MVP-2612: New eventType createSupportConversationEvent to support intercom using frontendClient

---

packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCard.tsx
packages/notifi-react-card/lib/context/NotifiContext.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx

this is primarily to allow users higher level contexts that the subscription card consumes. without it, we might have weird interactions with multiple instances of contexts existing.

we want to have conditional contexts.

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts

Remove notifi-core imports from notifi-frontendClient. Migrate the following types to `notifi-frontend-client` so that it no longer depends on notifi-core (will be deprecated later):
- SignMessageParams
- WalletWithSignParams
- WalletWithSignMessage
- ConnectWalletParams

MVP-2659: Remove notifi-core dependency from notifi-frontendClient

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/models/ConnectedWallet.ts
packages/notifi-core/lib/models/ConversationMessages.ts
packages/notifi-core/lib/models/EmailTarget.ts
packages/notifi-core/lib/models/SmsTarget.ts
packages/notifi-core/lib/models/TelegramTarget.ts
packages/notifi-react-card/lib/components/WalletList/WalletList.tsx
packages/notifi-react-card/lib/components/intercom/MessageGroup.tsx
packages/notifi-react-card/lib/components/intercom/MessageList.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/useIntercomChat.ts
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/lib/utils/AlertConfiguration.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts
packages/notifi-react-hooks/lib/utils/ensureTarget.spec.ts
packages/notifi-react-hooks/lib/utils/ensureTarget.ts
packages/notifi-react-hooks/lib/utils/ensureTargetIds.ts

In order to being able to completely deprecate notifi-core in notifi-react-card, firstly we need to consolidate types of notifi-core and notifi-graphql (targets).
Accordingly, also adjust corresponding parts

MVP-2660: Consolidate targetGroup types in notifi-core and notifi-graphql

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/models/Alert.ts
packages/notifi-core/lib/models/ConnectedWallet.ts
packages/notifi-core/lib/models/DiscordTarget.ts
packages/notifi-core/lib/models/SmsTarget.ts
packages/notifi-core/lib/models/SourceGroup.ts
packages/notifi-core/lib/models/TargetGroup.ts
packages/notifi-core/lib/models/TelegramTarget.ts
packages/notifi-core/lib/operations/CreateSource.ts
packages/notifi-core/lib/operations/GetSources.ts
packages/notifi-react-card/lib/components/WalletList/WalletList.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/lib/utils/AlertConfiguration.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts
packages/notifi-react-hooks/lib/utils/ensureSource.ts
packages/notifi-react-hooks/lib/utils/fetchDataImpl.ts

Optimization: Use the type with `Fragment` suffix instead of extracting the same types from `FetchQuery`

MVP-2660-patch: follow graphql-codegen convention using Fragment type

---

.gitignore
packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/components/subscription/EventTypeFusionHealthCheckRow.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/AlertsPanel.tsx
packages/notifi-react-card/lib/hooks/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/utils/AlertConfiguration.ts
packages/notifi-react-example/src/NotifiCard/DemoPreviewCard.tsx

Add fusionHealthCheck event type
**NOTE**
Merge it after MVP-2745 since it changes the way how SDK resolve the config of fusion event type. The config generate by current AP is not able to work with this new approach.
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/86456317-99e7-42b0-89e6-e8fd27f162d4

MVP-2744: Add fusionHealthCheck eventType

---

packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/AlertsPanel.tsx
packages/notifi-react-card/lib/hooks/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/utils/AlertConfiguration.ts

Make it backward compatible for those existing tenant configs using 'fusionToggle' type

MVP-2744-patch:  Backward compatibility for 'fusionToggle' Type

---

packages/notifi-frontend-client/package.json
packages/notifi-graphql/package.json
packages/notifi-react-card/package.json
packages/notifi-solana-hw-login/package.json

1. The following error will be thrown if using `commonJS` require.
```bash
./node_modules/@notifi-network/notifi-react-card/dist/index.js Can't import the named export 'GqlError' from non EcmaScript module (only default export is available)
```
> The same issue also happens on graphql and forntend-client
2. The CSS is not exported from package.json. It could possibily cause the error below:
```bash
Module not found: Error: Package path ./dist/index.css is not exported from package /path-to-module/notifi-sdk-ts/node_modules/@notifi-network/notifi-react-card (see exports field in /path-to-module/notifi-sdk-ts/node_modules/@notifi-network/notifi-react-card/package.json)
```

MVP-2766: Address regression -> Capability using CommonJS require in notifi packages

---

packages/notifi-react-card/lib/components/subscription/subscription-card-views/preview-panel/UserInfoPanel.tsx

there was a new update in discord where some usernames no longer have discriminators. we should display the discriminator if the # does not = 0.

updates discord username logic

---

packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx
packages/notifi-react-example/src/NotifiCard/WalletConnectCard.tsx
packages/notifi-react-example/src/NotifiContextWrapper/WalletConnectNotifiContextWrapper.tsx
packages/notifi-react-example/src/NotifiContextWrapper/index.ts

Add WalletConnect example of consuming `useNotifiSubscriptionContext`/ `useNotifiClientCotext` outside of `NotifiSubscriptionCard`

MVP-2773#2: WalletConnect example consuming  useNotifiSubscriptionContext/NotifiClientContext

---

packages/notifi-react-example/src/NotifiCard/NotifiCard.tsx
packages/notifi-react-example/src/NotifiCard/PolkadotCard.tsx
packages/notifi-react-example/src/NotifiContextWrapper/AcalaNotifiContextWrapper.tsx
packages/notifi-react-example/src/NotifiContextWrapper/index.ts

Add Acala (Polkadot) example of consuming `useNotifiSubscriptionContext`/ `useNotifiClientCotext` outside of `NotifiSubscriptionCard`
**NOTE**
> Originally missing Card section --> Add back

MVP-2773#3: Acala example consuming useNotifiSubscriptionContext/NotifiClientContext 

---

packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/EditCardView.tsx

Allow FTU to login w/o filling targets. See the detail flow below:
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/5bdee7b0-2fbb-49f8-9a11-73be9d44f532
**NOTE**
Not to merge until BE supports ~`isContactInfoRequired` in CardConfig (MVP-2714)~ MVP-2715. Otherwise, those users will not be able to get notification history

MVP-2716: Allow FTU login w/o targets

---

packages/notifi-react-card/lib/assets/BellIcon.tsx
packages/notifi-react-card/lib/components/AlertHistory/AlertIcon.tsx
packages/notifi-react-card/lib/components/SignupBanner.tsx
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/PreviewCard.tsx

Add SignupBanner component for those users who want to sign up after logging in anonymously.
- Case#1: notification history page
- Case#2: Edit page

MVP-2718: Add new SignupBanner component

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/ensureTarget.ts
packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx

When using frontendClient,
1. it will create the different discordId name (`default`) than the one created by `react-hooks` (`Default`). We need to make them consistent.
2. same situation as #339 while `enableCanary={true}`.
**NOTE**
This is rev#2.
Take the suggestion of previous PR (#340) comment

MVP-2842-rev: fix FrontendClient Discord verification fails 

---

packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

1. Signup a new wallet
2. Clean the browser cache
3. get in card and signup view will prompt up (expected because browser cache is cleaned)
4. toggle on the discord and signup.
5. Gql error 505See the error video demo attached herewith
See error video demo attched
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/e56f788a-5f12-49f1-80f0-7341af1450ad

MVP-2860: re-signup fails when discord target enabled

---

packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCard.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

Now the discord confirmation link still remain the same even the users have already accepted the invitation. Like below.
This PR is to fix this issue.

MVP-2839: Fix confirm link (discord/ tg) not update after enabling bot

---

packages/notifi-react-card/lib/components/NotifiDisclosureStatement.tsx
packages/notifi-react-card/lib/components/NotifiFooter.tsx
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/PreviewCard.tsx

- Consolidate `signup` banner
- Styling
- fix MVP-2822 (powered by Notifi)
Checkout demo below (Prod env):
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/b2f40036-8708-475f-8127-61717d863338
**TODO (POST ACTION)**
- Update SDK ver in AP Repo (MVP-2719)

MVP-2733:  login w/o targets refactor & style

---

packages/notifi-react-card/lib/utils/frontendClient.ts

We should use `eventType.name` to filter out the directPush event instead of using `filterType`

Fix directPush event unsubscribe by frontendClient

---

packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx

Set title of History & Alert Details View not correctly shown in sdk card. see image below
**ACTION LATER**
Need to update SDK in AP(Admin panel)

MVP-2882: SDK card title not sync with AP setting

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts

Allow passing in a custom TargetGroup name durint ensureAlert in NotifiFrontendClient codepath.

Support custom targetGroupName in ensureAlert

---

packages/notifi-react-card/README.md

1. Update the tutorial video link (original link is outdated)
2. Update doc for `notifi-react-card`

MVP-2905: Fix react-card vidoe link & update react-card doc

---

packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/context/NotifiClientContext.tsx

The regular users (Not FTU) should be able to routed to “HistoryView” when opening the card. 
However, the regular users will be routed to SingupView every time they open the card.
> ℹ️ This happens only with using frontendClient
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/a1a78eba-e669-4369-b63b-4717b7da7be9

MVP-2762: Regular users being not able to re-direct to historyView 

---

packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/components/subscription/EventTypeFusionToggleRow.tsx
packages/notifi-react-card/lib/hooks/SubscriptionCardConfig.ts

1. Fix alertFrequency in fusionToggleConfiguration
2. Use frontend-client's cardConfig instead of hooks in card
3. Sync the cardConfig in hooks and frontend-client

Fix alertFrequency in fusionToggleConfiguration

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-core/lib/models/WalletBlockchain.ts
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/ensureSource.ts
packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts
packages/notifi-node/lib/types/WalletBlockchain.ts
packages/notifi-react-card/lib/context/NotifiContext.tsx
packages/notifi-react-card/lib/utils/walletUtils.ts
packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

Aside from adding the ENUMs, how do we ensure that the wallet is supported?
In this case for ZkSync we're using Metamask 
@marukohao

Support ZKSYNC

---

package-lock.json
packages/notifi-react-hooks/package.json

As title.
After checking through all packages, we should move "typedoc-plugin-missing-exports" package to devDependencies.

Move un-runtime dependencies to devDependencies

---

packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/PreviewCard.tsx

the react card showing the sign up banner instead of alert destinations list when sign up only with discord
Currently, we should have both id and discordAccountId available to show the destinations list, but the discordAccountId can't be available until after the account is verified
remove the condition !!discordTargetData?.discordAccountId in isTargetsExist logic

fix: logic in isTargetsExist

---

packages/notifi-react-card/lib/components/subscription/EventTypeHealthCheckRow.tsx

As title, fix the issue that the `filterOption` -> `threshold` gets wrong data.

Fix: Worng healthCheck filterOption (threshold)

---

packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

Sometimes, the alert subscription toggle pumps back to "unsubscribe" state after trying to subscribe w/o the reason. 
Throwing error in this case would help user (or dev) to get the hint.

MVP-3062: Throw error explicitly when failing subscribe alert

---

packages/notifi-react-card/lib/components/subscription/EventTypeCustomHealthCheckRow.tsx

1. If custom health value set as percentage in AP, card row always show invalid value
2. Percentage & integrate conversion not correct

MVP-3051: EventTypeCustomHealthCheckRow not allows to input percentage

---

packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/components/subscription/EventTypeCustomHealthCheckRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeFusionHealthCheckRow.tsx

1. Render prefix '$' when new numberType='price'
2. Refactor HealthCheck EventType 
Will be adapted to the following eventTypes:
- fusionHealthCheck
- customHealthCheck
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/86ae7860-aebc-4d06-b8ea-4a3be6a2520f

MVP-3125: show "$" sign for healthCheck event with "Price" value type

---

packages/notifi-react-card/lib/assets/CircleBellIcon.tsx
packages/notifi-react-card/lib/components/defaults.css

when the email address is too long, the 'resend link' is broken down into two line
also fixed the 'invalid DOM property' warning from CircleBellIcon
before:
after:

fix line break issue in destination section

---

packages/notifi-core/lib/NotifiClient.ts
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-hooks/lib/utils/ensureTargetIds.ts

We have various assumptions about this in the UI. Let's make it explicit in much of the API.
This also fixes an issue where we were conflating `id` and `name` in the Discord target due to a parameter name in the API.

Only support one Discord target per user

---

packages/notifi-react-card/lib/components/AlertHistory/AlertDetailsCard.tsx
packages/notifi-react-card/lib/components/defaults.css

Use more general CSS approach to preserve white space and break line sign (`\n`) in History List View and History Detail View.
See demo video attached herewith.
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/1301b00c-a7ae-48b5-9751-30503fa5bbd5

MVP-3163: Alert History line break issues

---

packages/notifi-react-card/lib/components/WalletList/ConnectWalletRow.tsx
packages/notifi-react-card/lib/components/WalletList/WalletList.tsx
packages/notifi-react-card/lib/components/intercom/MessageGroup.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeCustomHealthCheckRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeHealthCheckRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeWalletBalanceRow.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/ExpiredTokenViewCard.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx
packages/notifi-react-card/lib/context/NotifiContext.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/hooks/useIntercomChat.ts
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/lib/hooks/useSubscriptionCard.ts
packages/notifi-react-card/lib/utils/AlertConfiguration.ts
packages/notifi-react-card/lib/utils/NotificationHistoryUtils.tsx
packages/notifi-react-card/lib/utils/frontendClient.ts
packages/notifi-react-card/lib/utils/walletUtils.ts

We do not need to use type defs in notifi-core anymore since notifi-graphql introduces 1:1 replacement. 
This PR replace all type defs `import xx from 'notifi-core'` with `import xx from notifi-graphql`

MVP-3105: Migrate type def from notifi-core to notifi-graphql

---

packages/notifi-react-card/lib/components/intercom/IntercomCard.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeBroadcastRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeCustomHealthCheckRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeCustomToggleRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeDirectPushRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeFusionHealthCheckRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeFusionToggleRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeHealthCheckRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypePriceChangeRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeTradingPairsRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeWalletBalanceRow.tsx
packages/notifi-react-card/lib/components/subscription/EventTypeXMTPRow.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCard.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/ExpiredTokenViewCard.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/VerifyWalletView.tsx
packages/notifi-react-card/lib/context/NotifiClientContext.tsx
packages/notifi-react-card/lib/context/NotifiContext.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/useIntercomCard.ts
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-card/lib/hooks/useSubscriptionCard.ts

Change the card to use frontend-client as default.
It can be switched back to using hooks by passing in `isUsingFrontendClient=false` (default is true).

MVP-3104: Default behavior with frontendClient. Optional API to switch back to hooks if needed

---

packages/notifi-axios-adapter/lib/mutations/markFusionNotificationHistoryAsRead.ts
packages/notifi-axios-adapter/lib/queries/getFusionNotificationHistoryImpl.ts
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-graphql/lib/gql/mutations/markFusionNotificationHistoryAsRead.gql.ts
packages/notifi-graphql/lib/gql/queries/getFusionNotificationHistory.gql.ts
packages/notifi-react-example/src/FrontendClient/SolanaFrontendClient.tsx
packages/notifi-react-example/src/NotifiCard/SolanaCard.tsx

Since we need to support “Clear all” feature for Osmosis, new state “HIDDEN” is supported on BE.
SDK also need to have corresponding modification to support mutate and query “HIDDEN” state.
Do not merge until being tested in dev.

MVP-3250: Update UreadHistory related client methods to support 'hide' feature

---

packages/notifi-react-card/lib/components/AlertHistory/AlertDetailsCard.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx
packages/notifi-react-card/lib/utils/NotificationHistoryUtils.tsx

- Adopt new `fusionNotificationHistoryEntry` (`includeHidden=false`) endpoint for frontendClient by default (`isUsingFrontendClient=true`)
- Legacy `notificationHistoryEntry` will be used while using `hooks` (`isUsingFrontendClient=false`)

MVP-3202: adopt new fusionNotificationHistory (default)

---

packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/VerifyWalletView.tsx

This change adds the ability to opt out single events from signing up at user signup. This can be enabled by passing `true` through the optional `optOutAtSignup` field through a custom JSON card config

allow opting out from default signup at first time signup for single events 

---

packages/notifi-react-card/lib/utils/NotificationHistoryUtils.tsx

Fix the following case:
When concatenating history nodes, it will throws error if nodes is an empty array.

MVP-3202-patch: empty array case issue

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts

The History will not show if users re-signup for some reason. Ex. losing jwt token (change browser/ pc ..etc) or token expiry.
This only happens when using frontend-client (which is default). Not happens in hooks (isUsingFrontendClient=false)
Visit Ticket page for more detail (issue video)

MVP-3315: Fix history not show if users re-signup

---

packages/notifi-react-hooks/lib/hooks/useNotifiClient.ts

if using `notifi-react-hook` (`isUsingFrontendClient=false`) in Card, multiple targetGroups with alert topic name will be created while signing up.
For more detail checkout the video in MVP-3388 ticket
> This issue does not happen under frontendClient (`isUsingFrontendClient=true` --> default)  since the targetGroup name is  always `Default` while the `ensureAlert` is called: https://github.com/notifi-network/notifi-sdk-ts/blob/e8aa23fb395f1bd28106a33c17b8b90baee8e796/packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts#L650

MVP-3388: fix 'notifi-react-hooks' creates mutliple targetGroups while signing up

---

lerna.json
nx.json
package-lock.json
package.json

We can use lerna's built-in nx support to cache and speed up local build time.
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/77437648-2fba-48da-b6d0-e119152753d2

MVP-3254: Make use of Nx-build to speed up build time

---

package-lock.json
package.json

According to the [official doc](https://nx.dev/recipes/adopting-nx/lerna-and-nx#use-nx-for-task-scheduling-without-changing-the-lerna-setup), we should just install "nx" as dev dependency instead of the `@nrwl/nx-darwin-x64` which is specifically for macOS.

MVP-3254-patch: replace devDependency '@nrwl/nx-darwin-x64' with more general one 'nx'

---

packages/notifi-react-card/lib/components/subscription/subscription-card-views/EditCardView.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/InputFields.tsx
packages/notifi-react-card/lib/hooks/useUnreadState.ts

In the react-card, when “Require Destinations” is turned off the signup page does not render the input fields including the “use hardware wallet” toggle for Solana with the hw wallet package. However the user needs to sign a message to login so will end up in a locked state where they cannot register at all. This will prevent any Solana users using a hw wallet from signing up to any dapp notifications. We should render the “use hardware wallet” toggle even if require destination is turned off.

MVP-3445: Fix Solana 'use hardwallet' not showing when destination is not required

---

packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/mutations/publishFusionMessage.gql.ts
packages/notifi-graphql/lib/operations/PublishFusionMessage.ts
packages/notifi-graphql/lib/operations/index.ts
packages/notifi-node/lib/client/NotifiClient.ts

The publish message API is used by tenantMessenger to publish to arbitrary Event IDs with arbitrary variables.
It supports filtering via specificWallets, which is optional

Add publishFusionMessage to notifi-node

---

packages/notifi-react-card/lib/components/common/LoadingStateCard.tsx
packages/notifi-react-card/lib/components/intercom/NotifiIntercomCardContainer.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscriptionCard.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx

Opening the alert history moves the user through a loading screen, then it shows ‘no notification’, before showing the full history. User should see loading icon if payload has not been received.
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/60c4f2fd-4ce5-4171-8438-f8cb17b269c8

MVP-3387: show loading view while fetching history

---

packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx

Before implementing new FTU flow, we better clean up the redundant code from `SubscriptionCardV1` to avoid potential PR conflicts.

Pre-MVP-3437: Refactor and remove redundant code from SubscriptionCardV1

---

packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts

The button had unnecessary logic for resolving the discord target.
This is probably stemming from the misnamed "discordId" param
Simply rely on ensureTargetGroup to do the right thing

Fix discord target in NotifiSubscribeButton

---

packages/notifi-react-example/src/NotifiCard/KeplrCard.tsx
packages/notifi-react-example/src/NotifiCard/MetamaskCard.tsx
packages/notifi-react-example/src/NotifiCard/PolkadotCard.tsx
packages/notifi-react-example/src/NotifiCard/SolanaCard.tsx
packages/notifi-react-example/src/NotifiCard/SuiNotifiCard.tsx
packages/notifi-react-example/src/NotifiCard/WalletConnectCard.tsx

As title, fixing the error when using `isUsingFrontendClient=false` for `notifi-react-example`

MVP-3466: fix error while switching to consuming hooks (react-example)

---

packages/notifi-graphql/lib/NotifiService.ts

Adding the ability to track the SDK version from each gql request to debug more efficiently.
See the demo video herewith:
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/6d156e23-a755-4dcf-a5a5-1b9defa5c78f

MVP-3529: Add 'X-Notifi-Client-Version' into gql request header

---

packages/notifi-react-card/lib/components/ConfigAlertModal.tsx
packages/notifi-react-card/lib/components/ConfigDestinationModal.tsx
packages/notifi-react-card/lib/components/subscription/NotifiSubscribeButton.tsx
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-example/cypress/component/NotifiSubscriptionCard.cy.tsx
packages/notifi-react-example/cypress/fixtures/userSettingsFtuAlerts.json
packages/notifi-react-example/cypress/fixtures/userSettingsFtuDestinations.json
packages/notifi-react-example/cypress/fixtures/userSettingsFtuNull.json
packages/notifi-react-example/cypress/support/commands.tsx

1. Remove "x" button from FTU flow
2.  Page persists if a user hasn’t yet finished FTU process
3. E2E cypress test script
Ready
MVP-3669+3670+3644
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/f76d7956-a6b4-42ab-839b-6df73c8a15b2

MVP-3669+3670+3644: presist FTU state & e2e test

---

packages/notifi-react-card/lib/components/VerifyBanner.tsx

Change the Banner content text to the correct format:
from
to
No need
MVP-3820

MVP-3820: Update the the text format in VerifyBanner

---

packages/notifi-react-card/lib/components/AlertHistory/AlertDetailsCard.tsx
packages/notifi-react-card/lib/components/defaults.css
packages/notifi-react-card/lib/components/subscription/SubscriptionCardV1.tsx
packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx
packages/notifi-react-card/lib/hooks/useFetchedCardState.ts

As the the following situations of history cardView , it becomes more and more difficult to follow and maintain.
includes not only history but also history detail view.
too much conditional logic between history and detail view
To get around this situation, we need to refactor history section in SubscriptionCardV1 by separating to hisotry & historyDetail.
PASS
MVP-3643

MVP-3643: new cardView historyDetail

---

packages/notifi-react-card/lib/utils/NotificationHistoryUtils.tsx

We do not have rendering DirectTenantMessageEventDetails logic, add it back
NO NEED
MVP-3877
- Demo video
https://github.com/notifi-network/notifi-sdk-ts/assets/127958634/ba25c59b-2c82-4ee2-8c63-ad43fd85ae31

MVP-3877: Support rendering DirectTenantMessageEventDetails in card

---

packages/notifi-react-card/lib/context/NotifiClientContext.tsx

Calling object's Async method in `useMemo` before returning it could cause [potential racing issue](https://github.com/notifi-network/notifi-sdk-ts/blob/a38ed62e3d6fb09b0a6b1f3e1a6dda8c6ccb860a/packages/notifi-react-card/lib/context/NotifiClientContext.tsx#L54).  
We should use `useEffect` instead 
No need. (Test PASSED)
MVP-3829

MVP-3829: Optimize NotifiClientContext (potential racing issue)

---

package-lock.json
packages/notifi-react-card/lib/components/subscription/subscription-card-views/HistoryCardView.tsx
packages/notifi-react-card/lib/utils/NotificationHistoryUtils.tsx

As title, fix  disappearing Notifications on scroll
> REASON:  card is not able to parse the correct notificationHistory type using `__typename`. Seems BE is no longer output `__typename` for `FusionNotificationHistoryEntry` and `NotificationHistoryEntry`.
No need (PASSED)
CS-379

CS-379: fix  disappearing Notifications on scroll

---

packages/notifi-react-card/lib/components/subscription/subscription-card-views/ExpiredTokenViewCard.tsx
packages/notifi-react-card/lib/context/NotifiClientContext.tsx
packages/notifi-react-card/lib/hooks/index.ts
packages/notifi-react-card/lib/hooks/useFrontendClientLogin.ts

(notifi-react-card) To reflect the frontendClient status changes, add `frontendClientStatus` in NotifiClientContext. By doing this, developer using this context variables will be able to get the effect when frontendClient status changes
No need (TEST PASSED)
MVP-3984

MVP-3984: Add frontendClientStatus in NotifiClientContext

---

packages/notifi-dataplane/lib/types/CommunityManagerVariablesJsonPayload.ts
packages/notifi-dataplane/lib/types/FusionMessage.ts
packages/notifi-node-sample/README.md

- Events attached to Community Manager have a specific message shape that segregates data by platform, while events of type "Sent from my server" have no such shape restriction.
- Hence, change the type of `variablesJson` in FusionMessage to `object` and remove `CommunityManagerJsonPayload`

Allow variables in FusionMessage to have any shape

---

packages/notifi-axios-utils/lib/utils/notifiConfigs.ts
packages/notifi-dapp-example/src/context/NotifiFrontendClientContext.tsx
packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts
packages/notifi-frontend-client/lib/storage/InMemoryStorageDriver.ts
packages/notifi-frontend-client/lib/storage/LocalForageStorageDriver.ts
packages/notifi-node-sample/lib/index.ts
packages/notifi-node/README.md
packages/notifi-node/lib/client/createNotifiService.ts
packages/notifi-node/lib/client/createSubscriptionClient.ts
packages/notifi-react-card/lib/context/NotifiClientContext.tsx
packages/notifi-react-card/lib/context/NotifiContext.tsx
packages/notifi-react-card/lib/context/NotifiSubscriptionContext.tsx
packages/notifi-react-card/lib/hooks/useNotifiSubscribe.ts
packages/notifi-react-example/cypress.config.ts
packages/notifi-react-example/package.json

'Production' is now the only setting for NotifiEnvironment that is used by external customers. Therefore, in all places where a NotifiEnvironment is passed (React card, frontend configuration, Node.js clients, etc.), make omitting the NotifiEnvironment parameter default to 'Production'.

Make NotifiEnvironment default to Production

---

packages/notifi-frontend-client/lib/models/FilterOptions.ts
packages/notifi-frontend-client/lib/models/FusionEvent.ts
packages/notifi-frontend-client/lib/models/index.ts

Define the interface for fusionEventDescriptor.metadata
> Located in `frontend-client`'s modal. This way other repo can also make use of it. ex. AP, `notifi-dapp-example`
No need
MVP-4329

MVP-4329: Define the interface for fusion Event Metadata

---

packages/notifi-react/lib/context/NotifiTopicContext.tsx
packages/notifi-react/lib/utils/topic.ts

- Update NotifiTopicContext: Support `convertOptionValue`
- Update `subscribeAlertsDefault`: utilize `convertOptionValue`
> This Ticket is the blocker of  MVP-4621 (Also GMX valueType render component logic). Need to merge this first then impl condition valueType rendering logic. 
> CC: @marukohao 
No need
MVP-4621

MVP-4620: Update NotifiTopicContext valueType render logic

---

packages/notifi-react/lib/context/NotifiHistoryContext.tsx

Set the `isLoading` as true to resolve the issue of seeing a glance of empty inbox view before getting into HistoryList. 
No need
MVP-4331

MVP-4331-patch: Set the inital isLoading value as true to avoid flickering

---

packages/notifi-react/lib/context/NotifiHistoryContext.tsx
packages/notifi-react/lib/context/NotifiTopicContext.tsx
packages/notifi-react/lib/utils/topic.ts

As title -> context update for using using `fusionEventId` as `alert.name`.
> This is the blocker of MVP-4752 & MVP-4753 
>  **Breaking change** - `notifi-react` and `notifi-dapp-example` need to change accordingly @marukohao 
No need
MVP-4751

MVP-4751: Migrate Alert Name Identifier - notifi-react context

---

packages/notifi-frontend-client/lib/models/FusionEvent.ts
packages/notifi-react/lib/utils/topic.ts

As title. 
> This is the blocker for AP & `notifi-react` to support custom prefix & suffix
> CC: @nimesh-notifi @marukohao 
No need
MVP-4708

pre-MVP-4708: Update fusionEventMetadata to support PrefixAndSuffix

---

packages/notifi-react/lib/components/HistoryRow.tsx
packages/notifi-react/lib/components/TopicOptions.tsx
packages/notifi-react/lib/components/TopicRow.tsx
packages/notifi-react/lib/components/TopicStackRow.tsx
packages/notifi-react/lib/hooks/useTopicStackRowInput.tsx
packages/notifi-react/lib/hooks/useUserInputParmToFilterOption.tsx

Update Topic and History related components (notifi-react) according to the the change of migrating alert.name from topicName to fusionEventTypeId
> This is the for migrating alert.name from topicName to fusionEventTypeId 2nd part - Components update. 
> Per discussed, we can also adopt this change to GMX (`notifi-dapp-example`) CC: @marukohao @nimesh-notifi

notifi-react/MVP-4752: Update Topic and History related components

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/queries/fetchFusionData.gql.ts
packages/notifi-graphql/lib/operations/FetchFusionData.ts
packages/notifi-react/lib/components/Connect.tsx
packages/notifi-react/lib/components/NotifiCardModal.tsx
packages/notifi-react/lib/components/TargetStateBanner.tsx
packages/notifi-react/lib/context/NotifiFrontendClientContext.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx
packages/notifi-react/lib/context/NotifiTopicContext.tsx
packages/notifi-react/lib/style/target-list.css
packages/notifi-react/lib/style/target-state-banner.css
packages/notifi-react/lib/utils/constants.ts

- Expose new frontendClient method `fetchFusionData` which is consumed by `notifi-react` (CC: @nimesh-notifi  for viz)
- Address Wallet target UAT feedbacks
MVP-4975/ MVP-5067

MVP-4975+5067: new frontendClient method `fetchFusionData` & CBW target UAT feedbacks 

---

packages/notifi-graphql/codegen.yml
packages/notifi-react/lib/components/TopicRow.tsx
packages/notifi-react/lib/context/NotifiHistoryContext.tsx

- workaround to display history display name
- also make use of fusionEventMetadata topic display name then fallback to card ui config for topic display name
> **NOTE**
> Temporary use prod gql schema to get rid of  dev breaking change (connectWallet being removed 20240710) 
MVP-5114

MVP-5114: workaround to display history display name

---

packages/notifi-dapp-example/src/components/SignUpButton.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx

As title.
Will be appreciated if can double confirm if @marukohao   the `notifi-dapp-example` will be working as expected so that integration can rebase it without issue.
No need
MVP-5037

MVP-5037: de-expose refreshTargetDocument from NotifiTargetContext

---

packages/notifi-axios-adapter/README.md
packages/notifi-axios-utils/README.md
packages/notifi-core/README.md
packages/notifi-react-card/README.md
packages/notifi-react-example/README.md
packages/notifi-react-hooks/README.md

The pre PR of MVP-5936 by adding the deprecate warning to legacy packages
This will be published to npm as `v1.1.2`, the final version of these legacy package.
No need
MVP-5396

MVP-5396-1: Add deprecated warning into legacy packages

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/fragments/WebPushTargetFragment.gql.ts
packages/notifi-graphql/lib/gql/mutations/createWebPushTarget.gql.ts
packages/notifi-graphql/lib/gql/mutations/deleteWebPushTarget.gql.ts
packages/notifi-graphql/lib/gql/mutations/updateWebPushTarget.gql.ts
packages/notifi-graphql/lib/gql/queries/getWebPushTargets.gql.ts
packages/notifi-graphql/lib/operations/CreateWebPushTarget.ts
packages/notifi-graphql/lib/operations/DeleteWebPushTarget.ts
packages/notifi-graphql/lib/operations/GetWebPushTargets.ts
packages/notifi-graphql/lib/operations/UpdateWebPushTarget.ts
packages/notifi-graphql/lib/operations/index.ts

Support the following 4 service calls in `notifi-graphql` and `notifi-frontend-client`
- `createWebPushTarget`  (Mutation)
- `updateWebPushTarget` (Mutation)
- `deleteWebPushTarget` (Mutation)
- `webPushTargets`  (Query)
The pre-release canary version is available [herewith](https://www.npmjs.com/package/@notifi-network/notifi-frontend-client/v/1.1.3-alpha.3). See the usage below:
```ts
frontendClient.createWebPushTarget(/* args */)
frontendClient.updateWebPushTarget(/* args */)
frontendClient.deleteWebPushTarget(/* args */)
frontendClient.getWebPushTargets(/* args */)
```
MVP-5423
- TODOs

MVP-5423: Add new frontend-client and graphql methods for webPushTarget

---

packages/notifi-react-example-v2/cypress/component/NotifiCardModal.cy.tsx
packages/notifi-react/lib/hooks/useConnect.tsx

This is new behavior introduced from this (`EnsureSystemNotificationsForUser()`) fn in UserManager service, which upon user creation, will ensure the user is subscribed to certain internal events (this wasn't happening properly before).
When we subscribe to system events, it uses `CreateFusionAlert` path, 
**which ensures creation of the Default target group.**
So, the cypress test needs to skip the request check of creating new targetGroup.
Update FTU related test blocks
MVP-5434

MVP-5434: Fix cypress test according to the BE update

---

packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/NotifiSubscriptionService.ts
packages/notifi-graphql/lib/gql/index.ts
packages/notifi-graphql/lib/gql/subscriptions/index.ts
packages/notifi-graphql/lib/gql/subscriptions/stateChanged.ts
packages/notifi-graphql/lib/gql/subscriptions/tenantEntityChanged.ts
packages/notifi-node/lib/client/NotifiNodeClient.ts
packages/notifi-node/lib/client/index.ts

1. Instead of having separated websocket client instances in both `notifi-node` and `notifi-graphql`, now we leverage the same on in `notifi-graphql`. Benefits:
-  **Single responsibility**: only `notifi-graphql` takes care of webscoket client instance logic
-  **Remove the vulnerability**: one of the legacy vulnerability is from the deprecated websocket packaged adopted by `notifi-node` --> subscriptions-transport-ws
2. Instead of putting subscription query in different places, we create a new module `lib/gql/subscription` to centrally mange them.
MVP-5586

MVP-5586: GQL subscription refactor #1 - restructure

---

packages/notifi-frontend-client/lib/configuration/NotifiFrontendConfiguration.ts

As title
> I assume only `Local` env will use `http` . Others are still https, Hope that makes sense. If there is any other cases, please kindly let me know 🙏 CC: @nimesh-notifi

fix: when env set as 'local', endpoint should be http instead of https

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-graphql/lib/gql/queries/getUnreadNotificationHistoryCount.gql.ts
packages/notifi-react-example-v2/src/context/NotifiContextWrapper.tsx
packages/notifi-react/README.md
packages/notifi-react/lib/context/NotifiContextProvider.tsx
packages/notifi-react/lib/context/NotifiHistoryContext.tsx

As title
> **DO NOT MERGE** UNDER TEST
> - ~~DEV TEST FAILING: even passing card id, it still responds tenant wise unread count~~
> - ~~GITHUB ACTION FAILING: Not yet on prod.~~
> **20241106 Update:**
>  - ~~PROD TEST FAILING: even passing card id, it still responds tenant wise unread count~~
MVP-5630

MVP-5630: allow unread count to be card specific

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-graphql/lib/NotifiEventEmitter.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/NotifiSubscriptionService.ts
packages/notifi-node/lib/client/NotifiNodeClient.ts
packages/notifi-react/lib/context/NotifiHistoryContext.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx

- Reform NotifiEventEmitter to assign each listener an id
- Deprecate SubscriptionStatusEvent & WebsocketStatusEvent
- Add ability to handle subscription error in addEventListener
MVP-5744

MVP-5744-1: Refrom NotifiEventEmitter

---

package-lock.json
packages/notifi-frontend-client/README.md
packages/notifi-frontend-client/__test__/NotifiFrontendClient.test.ts
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-frontend-client/package.json
packages/notifi-graphql/lib/NotifiEventEmitter.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/NotifiSubscriptionService.ts
packages/notifi-graphql/lib/gql/subscriptions/stateChanged.gql.ts
packages/notifi-node-sample/lib/index.ts
packages/notifi-node-sample/lib/middleware/notifiService.ts
packages/notifi-node/README.md
packages/notifi-node/lib/client/NotifiNodeClient.ts
packages/notifi-react-example-v2/cypress/support/commands.tsx
packages/notifi-react-example-v2/src/app/notifi/components-example/page.tsx
packages/notifi-react-example-v2/src/components/OidcGoogle.tsx
packages/notifi-react-example-v2/src/hooks/useSignTransaction.tsx
packages/notifi-react/lib/components/TopicStackRow.tsx
packages/notifi-react/lib/context/NotifiHistoryContext.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx

- MVP-5744: Fix EventEmitter issue & refactor realtime history part (addEventListener)
MVP-5557

SDK state change stage --> MAIN

---

packages/notifi-dapp-example/next.config.mjs
packages/notifi-react-example-v2/next.config.mjs

The `trailingSlash` config in `next.config.mjs` generates the the build folder allowing trailingSlash `/` to be end of the url instead of using `.html`. This could be the solution of routing issue. 
@marukohao & @ankush-notifi, you might want to cherry pick this commit to integration repos to see if can fix the routing issue.

chore: enable trailingSlash in next.config.mjs

---

.github/workflows/publish.yml

Rather than only stopping a specific `step`, this change skips the entire `job`.
> **NOTE:** Stopping only the `step` allows the remaining steps to continue running, which causes the action to fail.

MVP-5956: skip publish.yml action under notifi-sdk-ts repo

---

packages/notifi-frontend-client/__test__/NotifiFrontendClient.test.ts
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/fragments/ErrorFragments.gql.ts
packages/notifi-graphql/lib/gql/mutations/createFusionAlerts.gql.ts
packages/notifi-graphql/lib/gql/mutations/createWebPushTarget.gql.ts
packages/notifi-graphql/lib/gql/mutations/deleteAlerts.gql.ts
packages/notifi-graphql/lib/gql/mutations/deleteWebPushTarget.gql.ts
packages/notifi-graphql/lib/gql/mutations/updateWebPushTarget.gql.ts
packages/notifi-graphql/lib/operations/DeleteAlerts.ts
packages/notifi-graphql/lib/operations/index.ts
packages/notifi-react/lib/components/TopicRow.tsx
packages/notifi-react/lib/components/TopicStack.tsx
packages/notifi-react/lib/context/NotifiTopicContext.tsx

- Support 'deleteAlerts' endpoint
- deprecate deleteAlert/ use deleteAlerts to optimize topic toggle
- Leverage new deleteAlerts to optimize topic options & toggle reaction
Unit test updated

MVP-5986: Topic subscription CTA optimization M2 

---

packages/notifi-frontend-client/__test__/NotifiFrontendClient.test.ts
packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-graphql/lib/gql/fragments/ErrorFragments.gql.ts
packages/notifi-graphql/lib/gql/mutations/createWebPushTarget.gql.ts
packages/notifi-graphql/lib/gql/mutations/deleteAlerts.gql.ts
packages/notifi-graphql/lib/gql/mutations/deleteWebPushTarget.gql.ts
packages/notifi-graphql/lib/gql/mutations/updateWebPushTarget.gql.ts
packages/notifi-graphql/lib/operations/DeleteAlerts.ts
packages/notifi-graphql/lib/operations/index.ts
packages/notifi-react/lib/components/TopicOptions.tsx
packages/notifi-react/lib/components/TopicRow.tsx
packages/notifi-react/lib/components/TopicStack.tsx
packages/notifi-react/lib/components/TopicStackRowInput.tsx
packages/notifi-react/lib/context/NotifiTopicContext.tsx

- notifi-graphql: new deleteAlerts service method
- notifi-frontend-client & notifi-react: deprecate `deleteAlert` and utilize new method. (topic & unit test)
https://github.com/user-attachments/assets/773ab7ac-b179-4d3e-a127-16679b4e8353

MVP-5984: Optimize topic subscription CTAs STAGE --> MAIN

---

.github/workflows/cypress.yml
.github/workflows/unitest.yml
package-lock.json
packages/notifi-react/package.json

- remove legacy dependency notifi-core
- cypress & jest test cases only run on `notifi-sdk-ts repo

MVP-5998: clean up dependency/  Optimize github action

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-frontend-client/lib/client/ensureTarget.ts
packages/notifi-frontend-client/lib/models/SubscriptionCardConfig.ts
packages/notifi-react-example-v2/cypress/component/NotifiCardModal.cy.tsx
packages/notifi-react/README.md
packages/notifi-react/lib/components/Connect.tsx
packages/notifi-react/lib/components/LoadingGlobal.tsx
packages/notifi-react/lib/components/NotifiCardModal.tsx
packages/notifi-react/lib/components/TargetInputField.tsx
packages/notifi-react/lib/components/TargetList.tsx
packages/notifi-react/lib/components/TargetListItemToggle.tsx
packages/notifi-react/lib/components/TopicList.tsx
packages/notifi-react/lib/context/NotifiTargetContext.tsx
packages/notifi-react/lib/hooks/useTargetListItem.tsx
packages/notifi-react/lib/utils/constants.ts
packages/notifi-react/lib/utils/target.ts
packages/notifi-solana-hw-login/README.md

The last ticket of sdk4 m2 for UAT - content as title. The video attached herewith 
https://github.com/user-attachments/assets/f601699f-5094-4ed5-9560-36ca3818d2e2
- ~~TG verification will not not go through until endpoint supports it CC: @kai-notifi~~
- 250112 update: ready on dev. Prod is not ready. DO NOT MERGE before bing ready on prod.
> Canary version: [4.0.2-alpha.24](https://www.npmjs.com/package/@notifi-network/notifi-react/v/4.0.2-alpha.24)

MVP-5934: 1-step tg verify: update cypress test cicd/ optimize & debug/ update documentation

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-react/lib/context/NotifiFrontendClientContext.tsx

Enable notifi-react context (NotifiFrontnedClientContext) to logout frontendClient.
```ts
const { logout  } = useNotifiFrontendClientContext();
// Consume logout method
```
This unblocks MVP-6076.
CC: @marukohao

MVP-6184: Support logout method for NotifiFrontendClientContext 

---

package-lock.json
packages/notifi-react-wallet-target-plugin/lib/context/NotifiContextProviderWithWalletTargetPlugin.tsx
packages/notifi-react-wallet-target-plugin/lib/context/index.ts
packages/notifi-react-wallet-target-plugin/package.json
packages/notifi-react/lib/context/NotifiTargetContext.tsx
packages/notifi-react/package.json

-  Describe the purpose of the change
As title.
> ⚠️ KNOWN ISSUE: This change introduces a circular dependency warning due to mutual references between notifi-react and the plugin package. A fix is planned for an upcoming ticket.

MVP-6223: Impl NotifiContextProviderWithWalletTargetPlug context in new notifi-react-wallet-target-plugin

---

package.json
packages/notifi-dapp-example/package.json
packages/notifi-dataplane/package.json
packages/notifi-graphql/package.json
packages/notifi-node-sample/package.json
packages/notifi-react-wallet-target-plugin/package.json
packages/notifi-react/package.json
packages/notifi-solana-hw-login/package.json
packages/notifi-wallet-provider/package.json

MVP-6270-patch: exec packages' tests concurrently / remove unneeded npm test script

---

packages/notifi-dataplane/lib/types/SmartLinkAction.ts
packages/notifi-frontend-client/lib/models/SmartLinkConfig.ts
packages/notifi-react/lib/components/ActionInputCheckBox.tsx
packages/notifi-react/lib/components/ActionInputTextBoxNumber.tsx
packages/notifi-react/lib/components/ActionInputTextBoxString.tsx
packages/notifi-react/lib/components/NotifiSmartLink.tsx
packages/notifi-react/lib/components/SmartLinkAction.tsx
packages/notifi-react/lib/context/NotifiSmartLinkContext.tsx
packages/notifi-react/lib/utils/constants.ts

Follow-up ticket for #832 
- New fields for SmartLinkConfig: `tenantName` & `bannerImgUrl`
- New fields for SmartLinkAction: `id` in inputs
> ⚠️  NOTE:
> - Test needed once BE supports tenantName & bannerImgUrl in SmartLinkConfig
CC: @kai-notifi

MVP-6294-patch: Update SmartLinkConfig & SmartLinkAction interface

---

packages/notifi-react-example-v2/src/app/notifi/smart-link-example/page.tsx
packages/notifi-wallet-provider/lib/context/NotifiWallets.tsx
packages/notifi-wallet-provider/lib/hooks/useBinance.ts
packages/notifi-wallet-provider/lib/hooks/useInjectedWallet.ts
packages/notifi-wallet-provider/lib/hooks/useWagmiWallet.ts
packages/notifi-wallet-provider/lib/types.ts

This adds `sendTransaction` method support in notifi-wallet-provider. (Only Support EVM as MVP)
Under test, once done, merge and publish a canary version.

MVP-6295: Support sendTransaction for EVM chains in notifi-wallet-provider

---

packages/notifi-react-example-v2/src/components/NotifiSmartLinkExample.tsx
packages/notifi-react/lib/components/ActionInputCheckBox.tsx
packages/notifi-react/lib/components/ActionInputTextBoxNumber.tsx
packages/notifi-react/lib/components/ActionInputTextBoxString.tsx
packages/notifi-react/lib/context/NotifiSmartLinkContext.tsx

- **Describe the purpose of the change**  
- Allows resetting `userInputs` by omitting the `userInput` argument when calling `updateActionUserInputs`. This enables consuming projects to reset input fields to their initial values.  
- Optimizes `ActionInput` components by addressing certain edge cases.

MVP-6355-patch: support reseting userInput to initial state/  handle edge cases of user inputs

---

packages/notifi-react/lib/components/ActionInputTextBoxNumber.tsx
packages/notifi-react/lib/style/smartlink.css

Address the following two UAT feedbacks:
1. Bold the number input constraint prompt
2. Block character 'e' & 'E' in input type number

MVP-6355-patch4: address UAT feedbacks

---

packages/notifi-dapp-example/src/hooks/useTargetListItem.tsx

Some wallet app browsers prevent to open link which with the deep link, for this case, we'll open the link on current page instead of opening the new window

Fix tg/discord confirmation page redirect issue

---

packages/notifi-react-wallet-target-plugin/package.json

- **Describe the purpose of the change**
The current `peerDependencies` in `notifi-react-wallet-target-plugin` use a strict version range (`^6.0.0`), which blocks monorepo packages from publishing a major update.
This change relaxes the constraint to `>=6.0.0` to allow compatibility with future major versions.

patch: fix peerDependencies conflict

---

packages/notifi-frontend-client/lib/client/clientFactory.ts
packages/notifi-graphql/lib/NotifiService.ts
packages/notifi-react/lib/context/NotifiFrontendClientContext.tsx

This PR ensures that all outgoing GraphQL requests from the SDK include a consistent and meaningful `X-Notifi-Client-Version` header, even when the source package may vary.
* Moved version control of `X-Notifi-Client-Version` header up to the `notifi-react` layer.
* Introduced a fallback mechanism to prevent the version header from being empty:
* Use the version of `notifi-react` if available.
* If not, fall back to `notifi-frontend-client`.
* If neither is available, fall back to `notifi-graphql`.
This simplifies backend version handling by avoiding the need to track separate versions per package.

MVP-6027-patch: Move version header logic to notifi-react with fallback to avoid empty values

---

packages/notifi-react/lib/components/Connect.tsx

This PR addresses an issue where the topic display name override is not applied on the Connect view (`Connect.tsx`) in versions ≤ 7.2.1.

MVP-6417-patch: fix Connect.tsx view missing topic display name override fallback mechanism

---

package.json

As title.
> ⚠️ KNOWN ISSUE: CICD failure due to `500 internal error` from Smartlink Action

MVP-6557: Add engines in project package.json to fix vercel preview error

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-react-example-v2/cypress/utils/topic-utils.ts

MVP-6559: Update Fusion Event identification to use fusionEventId (with legacy support via resolveStringRef) instead of event.name

---

packages/notifi-frontend-client/lib/client/NotifiFrontendClient.ts
packages/notifi-react-example-v2/cypress/utils/topic-utils.ts
packages/notifi-react/lib/context/NotifiHistoryContext.tsx

TopicName -> FusionEventId STAGE -> MAIN
